### ISSUE TITLE
Can't recognize runtime TestNG version

### ISSUE THREAD

**Issue by manguram** [cbeust/testng#1012]
After upgrading to 6.9.11 from Eclipse marketplace, the error message is displayed as "Can't recognize runtime TestNG version" while running any test case.

When I add "testng.jar" to the build path, below exception is displayed in console.

```
java.lang.AbstractMethodError: org.testng.remote.support.RemoteTestNG6_9_10$DelegatingTestRunnerFactory.newTestRunner(Lorg/testng/ISuite;Lorg/testng/xml/XmlTest;Ljava/util/Collection;)Lorg/testng/TestRunner;
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:587)
	at org.testng.SuiteRunner.init(SuiteRunner.java:161)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:114)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1290)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1277)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1131)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:75)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:46)
```

**Comment by mhenley-uk** [comment]
+1

**Comment by juherr** [comment]
Ping @missedone

**Comment by missedone** [comment]
hi @manguram, @mhenley-uk 
where did you get the testng.jar?

could you paste the content of MANIFEST.MF?

for example, with command `unzip -c testng-6.9.10.jar META-INF/MANIFEST.MF` (remember to replace with your testng jar file name), here is the output of testng-6.9.10:

```
Archive:  testng-6.9.10.jar
  inflating: META-INF/MANIFEST.MF
Manifest-Version: 1.0
Bundle-Description: TestNG is a testing framework.
Bundle-License: http://apache.org/licenses/LICENSE-2.0
Build-Date: 2015-12-16
Bundle-SymbolicName: org.testng
Built-By: beust
Bundle-ManifestVersion: 2
Bnd-LastModified: 1450151080000
Specification-Title: testng
Import-Package: bsh;version="[2.0.0,3.0.0)";resolution:=optional,com.b
 eust.jcommander;version="[1.7.0,3.0.0)";resolution:=optional,com.beus
 t.jcommander.converters;version="[1.7.0,3.0.0)";resolution:=optional,
 com.google.inject;version="[1.2,1.3)";resolution:=optional,junit.fram
 ework;version="[3.8.1, 5.0.0)";resolution:=optional,org.junit;resolut
 ion:=optional,org.junit.runner;resolution:=optional,org.junit.runner.
 manipulation;resolution:=optional,org.junit.runner.notification;resol
 ution:=optional,org.apache.tools.ant;version="[1.7.0, 2.0.0)";resolut
 ion:=optional,org.apache.tools.ant.taskdefs;version="[1.7.0, 2.0.0)";
 resolution:=optional,org.apache.tools.ant.types;version="[1.7.0, 2.0.
 0)";resolution:=optional,org.apache.tools.ant.types.resources;version
 ="[1.7.0, 2.0.0)";resolution:=optional,org.apache.tools.ant.types.sel
 ectors;version="[1.7.0, 2.0.0)";resolution:=optional,org.yaml.snakeya
 ml;version="[1.6,2.0)";resolution:=optional,org.yaml.snakeyaml.constr
 uctor;version="[1.6,2.0)";resolution:=optional,org.yaml.snakeyaml.nod
 es;version="[1.6,2.0)";resolution:=optional,javax.xml.parsers,javax.x
 ml.xpath,org.w3c.dom,org.xml.sax,org.xml.sax.helpers
Tool: Bnd-2.1.0.20130426-122213
Export-Package: com.beust.testng;version="6.9.10";uses:="org.testng",o
 rg.testng;version="6.9.10";uses:="com.beust.jcommander,com.beust.jcom
 mander.converters,com.google.inject,javax.xml.parsers,org.apache.tool
 s.ant,org.apache.tools.ant.taskdefs,org.apache.tools.ant.types,org.te
 stng.annotations,org.testng.internal,org.testng.internal.annotations,
 org.testng.internal.junit,org.testng.internal.thread.graph,org.testng
 .xml,org.xml.sax",org.testng.annotations;version="6.9.10";uses:="com.
 google.inject,org.testng,org.testng.internal.annotations",org.testng.
 asserts;version="6.9.10",org.testng.collections;version="6.9.10",org.
 testng.internal;version="6.9.10";uses:="com.google.inject,org.testng,
 org.testng.annotations,org.testng.collections,org.testng.internal.ann
 otations,org.testng.internal.thread,org.testng.internal.thread.graph,
 org.testng.junit,org.testng.reporters,org.testng.xml",org.testng.inte
 rnal.annotations;version="6.9.10";uses:="org.testng,org.testng.annota
 tions,org.testng.xml",org.testng.internal.collections;version="6.9.10
 ",org.testng.internal.invokers;version="6.9.10";uses:="org.testng",or
 g.testng.internal.junit;version="6.9.10",org.testng.internal.remote;v
 ersion="6.9.10";uses:="org.testng.remote",org.testng.internal.thread;
 version="6.9.10",org.testng.internal.thread.graph;version="6.9.10";us
 es:="org.testng,org.testng.internal",org.testng.junit;version="6.9.10
 ";uses:="junit.framework,org.junit.runner,org.testng,org.testng.inter
 nal,org.testng.internal.annotations,org.testng.xml",org.testng.log;ve
 rsion="6.9.10",org.testng.log4testng;version="6.9.10",org.testng.must
 ache;version="6.9.10",org.testng.remote;version="6.9.10";uses:="com.b
 eust.jcommander,org.testng,org.testng.internal,org.testng.internal.re
 mote,org.testng.remote.adapter,org.testng.xml",org.testng.remote.adap
 ter;version="6.9.10";uses:="org.testng,org.testng.xml",org.testng.rem
 ote.strprotocol;version="6.9.10";uses:="org.testng,org.testng.interna
 l,org.testng.xml",org.testng.reporters;version="6.9.10";uses:="org.te
 stng,org.testng.internal,org.testng.xml",org.testng.reporters.jq;vers
 ion="6.9.10";uses:="org.testng,org.testng.reporters,org.testng.xml",o
 rg.testng.reporters.util;version="6.9.10";uses:="org.testng",org.test
 ng.util;version="6.9.10";uses:="org.testng",org.testng.xml;version="6
 .9.10";uses:="javax.xml.parsers,org.testng,org.testng.remote.strproto
 col,org.testng.reporters,org.testng.xml.dom,org.xml.sax,org.xml.sax.h
 elpers",org.testng.xml.dom;version="6.9.10";uses:="javax.xml.parsers,
 javax.xml.xpath,org.testng,org.testng.internal.collections,org.testng
 .xml,org.w3c.dom,org.xml.sax"
Bundle-Name: testng
Bundle-Version: 6.9.10
Build-Time: 01:14:26.500+0400
Created-By: 1.8.0_25 (Oracle Corporation 25.25-b02)
Specification-Version: 6.9.10
```

**Comment by manguram** [comment]
@missedone 
Here are the contents MANIFEST.MF
```
Manifest-Version: 1.0
Bundle-Description: TestNG is a testing framework.
Bundle-License: http://apache.org/licenses/LICENSE-2.0
Build-Date: 2016-03-26
Bundle-SymbolicName: org.testng
Built-By: beust
Bundle-ManifestVersion: 2
Bnd-LastModified: 1450151080000
Specification-Title: testng
Import-Package: bsh;version="[2.0.0,3.0.0)";resolution:=optional,com.b
 eust.jcommander;version="[1.7.0,3.0.0)";resolution:=optional,com.beus
 t.jcommander.converters;version="[1.7.0,3.0.0)";resolution:=optional,
 com.google.inject;version="[1.2,1.3)";resolution:=optional,junit.fram
 ework;version="[3.8.1, 5.0.0)";resolution:=optional,org.junit;resolut
 ion:=optional,org.junit.runner;resolution:=optional,org.junit.runner.
 manipulation;resolution:=optional,org.junit.runner.notification;resol
 ution:=optional,org.apache.tools.ant;version="[1.7.0, 2.0.0)";resolut
 ion:=optional,org.apache.tools.ant.taskdefs;version="[1.7.0, 2.0.0)";
 resolution:=optional,org.apache.tools.ant.types;version="[1.7.0, 2.0.
 0)";resolution:=optional,org.apache.tools.ant.types.resources;version
 ="[1.7.0, 2.0.0)";resolution:=optional,org.apache.tools.ant.types.sel
 ectors;version="[1.7.0, 2.0.0)";resolution:=optional,org.yaml.snakeya
 ml;version="[1.6,2.0)";resolution:=optional,org.yaml.snakeyaml.constr
 uctor;version="[1.6,2.0)";resolution:=optional,org.yaml.snakeyaml.nod
 es;version="[1.6,2.0)";resolution:=optional,javax.xml.parsers,javax.x
 ml.xpath,org.w3c.dom,org.xml.sax,org.xml.sax.helpers
Tool: Bnd-2.1.0.20130426-122213
Export-Package: com.beust.testng;version="6.9.11";uses:="org.testng",o
 rg.testng;version="6.9.11";uses:="com.beust.jcommander,com.beust.jcom
 mander.converters,com.google.inject,javax.xml.parsers,org.apache.tool
 s.ant,org.apache.tools.ant.taskdefs,org.apache.tools.ant.types,org.te
 stng.annotations,org.testng.internal,org.testng.internal.annotations,
 org.testng.internal.junit,org.testng.internal.thread.graph,org.testng
 .xml,org.xml.sax",org.testng.annotations;version="6.9.11";uses:="com.
 google.inject,org.testng,org.testng.internal.annotations",org.testng.
 asserts;version="6.9.11",org.testng.collections;version="6.9.11",org.
 testng.internal;version="6.9.11";uses:="com.google.inject,org.testng,
 org.testng.annotations,org.testng.collections,org.testng.internal.ann
 otations,org.testng.internal.thread,org.testng.internal.thread.graph,
 org.testng.junit,org.testng.reporters,org.testng.xml",org.testng.inte
 rnal.annotations;version="6.9.11";uses:="org.testng,org.testng.annota
 tions,org.testng.xml",org.testng.internal.collections;version="6.9.11
 ",org.testng.internal.invokers;version="6.9.11";uses:="org.testng",or
 g.testng.internal.junit;version="6.9.11",org.testng.internal.reflect;
 version="6.9.11";uses:="org.testng,org.testng.internal",org.testng.in
 ternal.thread;version="6.9.11",org.testng.internal.thread.graph;versi
 on="6.9.11";uses:="org.testng,org.testng.internal",org.testng.junit;v
 ersion="6.9.11";uses:="junit.framework,org.junit.runner,org.testng,or
 g.testng.internal,org.testng.internal.annotations,org.testng.xml",org
 .testng.log;version="6.9.11",org.testng.log4testng;version="6.9.11",o
 rg.testng.mustache;version="6.9.11",org.testng.reporters;version="6.9
 .11";uses:="org.testng,org.testng.internal,org.testng.xml",org.testng
 .reporters.jq;version="6.9.11";uses:="org.testng,org.testng.reporters
 ,org.testng.xml",org.testng.reporters.util;version="6.9.11";uses:="or
 g.testng",org.testng.util;version="6.9.11";uses:="org.testng",org.tes
 tng.xml;version="6.9.11";uses:="javax.xml.parsers,org.testng,org.test
 ng.reporters,org.testng.xml.dom,org.xml.sax,org.xml.sax.helpers",org.
 testng.xml.dom;version="6.9.11";uses:="javax.xml.parsers,javax.xml.xp
 ath,org.testng,org.testng.internal.collections,org.testng.xml,org.w3c
 .dom,org.xml.sax"
Bundle-Name: testng
Bundle-Version: 6.9.11
Build-Time: 09:31:35.506+0400
Created-By: 1.8.0_73 (Oracle Corporation 25.73-b02)
Specification-Version: 6.9.11
```

**Comment by missedone** [comment]
hi @manguram 
the content looks pretty normal.

do you see any relate log in "Error Log" view, you can open it by clicking "Window (on the top level menu)  -> Show View -> Other... -> Error Log"

thanks

**Comment by manguram** [comment]
Hello @missedone 
This is coming up in error logs: Session Data
```
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product
```

**Comment by missedone** [comment]
hi @manguram 
sorry, the log you provided is not relate, do you see something else?
thanks

**Comment by manguram** [comment]
@missedone There is no exception stack trace: An exception stack trace is not available.
I have tried uninstalling TestNG plugin from eclipse, did a fresh install of eclipse as well, but it's not working.

This just came up after upgrading to 6.9.11. Is there any workaround so that I can continue my tests?

**Comment by missedone** [comment]
@manguram 
could you share your classpath, it's available on the Error Log view as well. see log entry of '[TestNGLaunchConfigurationDelegate] Launching:'.

i need to understand the issue so that can suggest the workaround.
thanks for your patience

**Comment by cbeust** [comment]
@misedone Should I revert the Eclipse plug-in to the previous version while
you sort this out?

-- 
Cédric

**Comment by manguram** [comment]
@missedone 
[TestNGLaunchConfigurationDelegate] Launching:
  `Classpath: C:\Users\sushant.soni\Downloads\eclipse-jee-mars-2-win32-x86_64\eclipse\configuration\org.eclipse.osgi\334\data\-1824065564\plugins\org.testng.eclipse_6.9.11.201603260617\lib\testng-remote.jar C:\Users\sushant.soni\New Workspace\OA\bin C:\Users\sushant.soni\Documents\Selenium\selenium-server-standalone-2.52.0.jar C:\Users\sushant.soni\Documents\Selenium\IEDriverServer_Win32_2.53.0.zip C:\Users\sushant.soni\Downloads\eclipse-jee-mars-2-win32-x86_64\eclipse\configuration\org.eclipse.osgi\334\data\-1824065564\plugins\org.testng.eclipse_6.9.11.201603260617\lib\testng.jar`

**Comment by manguram** [comment]
![image](https://cloud.githubusercontent.com/assets/3597767/14132649/db808dfa-f665-11e5-8a31-6865f6eb2286.png)

This error is also coming in error logs.

**Comment by missedone** [comment]
hi @cbeust 
could you post the old update-site link so that people can rollback to the previous version?
thanks

**Comment by manguram** [comment]
@missedone Thank you.

**Comment by cbeust** [comment]
Done, I reverted the update site to 6.9.10.

**Comment by missedone** [comment]
thanks @cbeust

**Comment by manguram** [comment]
Thank you guys. It is working now!

**Comment by missedone** [comment]
hi @manguram 
if you don't mind, could you install the new beta plugin http://testng.org/eclipse-beta , help verifying if it works for you or not
thanks

**Comment by manguram** [comment]
Hi @missedone 
The Beta version is working fine for me.

**Comment by missedone** [comment]
cool, thanks
