### ISSUE TITLE
Non static methods from external data providers are not working without @Guice

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1022]
See http://stackoverflow.com/questions/36565014/testng-non-static-data-provider-method-not-working/36569677#36569677

**Comment by Klemsus** [comment]
Any chance to have a fix for this issue? I wanted to use `@Factory` annotation for test class constructor with non-static data provider.
And I need non-static DataProvider to have injections inside DataProvider class.

```
public class FactoryTest {

  String s;
  
  @Factory(dataProviderClass = DPClass.class, dataProvider = "dp")
  public FactoryTest(String s) {
    this.s = s;    
  }
```
If `dp` is non-static method it gives me an error for `DPClass` like in linked question. If I add `@Guice` annotation it also gives an guice error for `FactoryClass`: "Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private."

**Comment by juherr** [comment]
Your case is a bit different but both are linked.

To be honest, the best way to see it fixed is trying to fix it by yourself. I can help you to try if you are ok with that.

First step: adding new test cases that show issues.

**Comment by juherr** [comment]
Well, in fact, it was easier than expected.

**Comment by Hari-Shetty** [comment]
Hello juherr I tried using Guice as well to avoid static. But still no luck as i'm getting Null pointer exception.Please find below code and error logs are as below
If I run GetExcelData.java separately then its working fine by fetching ll data  from excel

[RemoteTestNG] detected TestNG version 6.14.2
java.lang.NullPointerException
[Utils] [ERROR] [Error] org.testng.TestNGException: 
Data Provider public java.lang.String[][] mypack.RegisterTest2.FormData() returned a null value
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:133)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

FAILED: register
org.testng.TestNGException: 
Data Provider public java.lang.String[][] mypack.RegisterTest2.FormData() returned a null value
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:133)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)


===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================





GetExcelData.java
package resources;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.xssf.usermodel.XSSFCell;
//import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.testng.annotations.Guice;

@Guice
public class GetExcelData 
{
		//public static XSSFSheet ExcelWSheet;
		//public static XSSFWorkbook ExcelWBook;
		//public static XSSFCell Cell;
		public XSSFSheet ExcelWSheet;
		public XSSFWorkbook ExcelWBook;
		public XSSFCell Cell;
	

		public String[][] getTableArray(String FilePath, String SheetName) throws Exception 
		{   
			String[][] tabArray = null;

			try 
			{
				FileInputStream ExcelFile = new FileInputStream(FilePath);

				// Access the required test data sheet

				ExcelWBook = new XSSFWorkbook(ExcelFile);

				ExcelWSheet = ExcelWBook.getSheet(SheetName);

				int startRow = 1;

				int startCol = 1;

				int ci,cj;

				int totalRows = ExcelWSheet.getLastRowNum();

				// you can write a function as well to get Column count

				int colcount = ExcelWSheet.getRow(startRow).getPhysicalNumberOfCells();
				int totalCols = colcount-1;
				System.out.println(totalCols);
	   
				tabArray=new String[totalRows][totalCols];


				ci=0;

				for (int i=startRow;i<=totalRows;i++, ci++) 
	            {           	   

					cj=0;

					for (int j=startCol;j<=totalCols;j++, cj++)
					{

						tabArray[ci][cj]=getCellData(i,j);

						System.out.println(tabArray[ci][cj]);  

					}

	            }

			}

			catch (FileNotFoundException e)
			{

				System.out.println("Could not read the Excel sheet");

				e.printStackTrace();

			}

			catch (IOException e)
			{
				System.out.println("Could not read the Excel sheet");

				e.printStackTrace();

			}

			return(tabArray);

			}


public String getCellData(int RowNum, int ColNum) throws Exception 
{
	try
	{
		DataFormatter df = new DataFormatter();
		Cell = ExcelWSheet.getRow(RowNum).getCell(ColNum);

		CellType dataType = Cell.getCellTypeEnum();
		String celldata;
		if  (dataType == CellType.NUMERIC) 
		{
			celldata = df.formatCellValue(Cell);
		}
		else
		{
			celldata = Cell.getStringCellValue();
		}
		return celldata;
	}
		catch (Exception e)
		{
		System.out.println(e.getMessage());
		throw (e);
		}
	}   
}
	




RegisterTest.java

package mypack;

import java.io.IOException;
import java.util.ArrayList;
//import java.util.List;
import java.util.Random;

import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Guice;
import org.testng.annotations.Test;

import pageObjects.RegisterPage;
import resources.BaseClass;
//import resources.ExcelReader;
//import resources.ExcelData;
import resources.GetExcelData;

//import resources.*;

@Guice
public class RegisterTest extends BaseClass{
	
	//public String[][] str = null;
	String[][] str ;
	GetExcelData ex;
	RegisterPage reg = new RegisterPage(driver);

	
	@Test(dataProvider = "takleef") //, dataProviderClass = ExcelReader.class)
	public void register(String first, String last, String addr, String email, String phone, String skills, String country1, String country2, String year, String month, String day, String pass, String conpass) throws IOException
	{	
		
		//ArrayList<String> data = ex.getData("RegisterData", "FormDetails");
		driver = initializeDriver();
		driver.get(prop.getProperty("url"));
		
		Random random = new Random();
		int randomInt = 0;
		for (int idx = 100; idx <= 1000; ++idx)
		{
			randomInt = random.nextInt(1000);
			//System.out.println("Generated : " + randomInt);
		}
		
		reg.firstname().sendKeys(first+randomInt);
		reg.lastname().sendKeys(last+randomInt);
		reg.address().sendKeys(addr+randomInt);
		reg.email().sendKeys(email);
		reg.tel().sendKeys(randomInt+phone); 
		
		JavascriptExecutor js = (JavascriptExecutor) driver;
		js.executeScript("window.scrollBy(0,500)", "");
		
		ArrayList<WebElement> gender = (ArrayList<WebElement>) reg.gender();
		
	    int index = random.nextInt(gender.size());
	    gender.get(index).click(); 

		
		ArrayList<WebElement> hobby = (ArrayList<WebElement>) reg.hobby();
		for ( WebElement chk : hobby ) {
		    if ( !chk.isSelected() ) {
		        chk.click();
		    }
		}
		 
		reg.skills().sendKeys(skills);
		reg.country().sendKeys(country1);
		//reg.sel_country().sendKeys(country2);
		reg.year().sendKeys(year);
		reg.month().sendKeys(month);
		reg.day().sendKeys(day);
		reg.pwd().sendKeys(pass);
		reg.conpwd().sendKeys(conpass);
		//reg.submit().click();  		
	}

	@DataProvider (name = "takleef")
	public String[][] FormData()
	{
		//public static Object[][] str = new Object[0][0];
		try {
			
			str = ex.getTableArray(prop.getProperty("filepath"), prop.getProperty("sheetname"));			
		}
		catch(Exception e) {
		System.out.println(e);
		}
		return (str);
	}
}

**Comment by juherr** [comment]
@Hari-Shetty 
The issue comes from your own code. `FormData` is returning null instead of an array.

At the same time, `@Guice` will inject `@Inject` class members and you have none in your classes.

**Comment by Hari-Shetty** [comment]
Thanks juherr for your reply.  Could u plz tell me how and where to achieve @inject in my code. 
 BTW if I run FormData file separately then it's successfully returning all data from excel sheet.

Thanks in advance. :)

**Comment by juherr** [comment]
Ping @krmahadevan
