### ISSUE TITLE
TestNG does not report/print/log throwables in data providers

### ISSUE THREAD

**Issue by mfulton26** [cbeust/testng#1107]
e.g. The `RuntimeException` is not printed to standard out and the test is ignored but no explanation on why.

```java
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class DemoTest {
    @DataProvider
    public Object[][] data() {
        throw new RuntimeException();
    }

    @Test(dataProvider = "data")
    public void test(Object input) {
    }
}
```

```
Test ignored.
Test ignored.
===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 1
===============================================
```

**Comment by juherr** [comment]
Yes, it is how the default console listener is working. If you want more details you can make your own listener with all you want.

But if you think you can propose something more verbose but not too much, you can try to pull-request it :)

**Comment by krmahadevan** [comment]
@juherr - I have tried fixing this. Can you please help take a look ?

**Comment by haithilak** [comment]
May I know the testng version this fix is in so that I can pull ? I am also facing the same issue

**Comment by krmahadevan** [comment]
@haithilak - How about trying with the latest released version of TestNG viz 6.12

**Comment by haithilak** [comment]
@krmahadevan Yes It worked in 6.12. Thanks a lot for fix and prompt response

**Comment by sankouski-dzmitry** [comment]
Still reproduces on 7.3.0, when dataprovider is used in Factory annotation

Consider example:

`import org.testng.annotations.DataProvider;
import org.testng.annotations.Factory;
import org.testng.annotations.Test;

class TestClass {
    @Factory(dataProvider = "dp")
    TestClass(String param) {
    }

    @Test
    public void test() {

    }

    @DataProvider
    public Object[][] dp() {
        System.out.println("Data provider invoked");
        throw new RuntimeException();
    }
}`

**Comment by krmahadevan** [comment]
@sankouski-dzmitry - Can you please help me understand what exactly are you expecting? 

This is what comes up when I run the shared sample in IntelliJ and this is correct because

1. Your `@DataProvider` is an instance method which means TestNG can get to it only after the instance has been created.
2. TestNG cannot create an instance because you tied the constructor via a `@Factory` and coupled it with the `@DataProvider`

So its like we are now going around in circles.

```
org.testng.TestNGException: 
Cannot instantiate class com.rationaleemotions.github.issue1107.TestClass
	at org.testng.internal.InstanceCreator.newInstance(InstanceCreator.java:36)
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:650)
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:551)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:772)
	at org.testng.internal.FactoryMethod.invoke(FactoryMethod.java:149)
	at org.testng.internal.TestNGClassFinder.processFactory(TestNGClassFinder.java:182)
	at org.testng.internal.TestNGClassFinder.processMethod(TestNGClassFinder.java:142)
	at org.testng.internal.TestNGClassFinder.processClass(TestNGClassFinder.java:133)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:71)
	at org.testng.TestRunner.initMethods(TestRunner.java:437)
	at org.testng.TestRunner.init(TestRunner.java:336)
	at org.testng.TestRunner.init(TestRunner.java:289)
	at org.testng.TestRunner.<init>(TestRunner.java:180)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:613)
	at org.testng.SuiteRunner.init(SuiteRunner.java:178)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:112)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1306)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1282)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1131)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.InstantiationException: com.rationaleemotions.github.issue1107.TestClass
	at java.lang.Class.newInstance(Class.java:427)
	at org.testng.internal.InstanceCreator.newInstance(InstanceCreator.java:30)
	... 22 more
Caused by: java.lang.NoSuchMethodException: com.rationaleemotions.github.issue1107.TestClass.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 23 more
```

Fix your data provider by making it static and run again.

You should see something like this:

```
Data provider invoked
java.lang.RuntimeException: java.lang.RuntimeException
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:145)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:797)
	at org.testng.internal.FactoryMethod.invoke(FactoryMethod.java:149)
	at org.testng.internal.TestNGClassFinder.processFactory(TestNGClassFinder.java:182)
	at org.testng.internal.TestNGClassFinder.processMethod(TestNGClassFinder.java:142)
	at org.testng.internal.TestNGClassFinder.processClass(TestNGClassFinder.java:133)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:71)
	at org.testng.TestRunner.initMethods(TestRunner.java:437)
	at org.testng.TestRunner.init(TestRunner.java:336)
	at org.testng.TestRunner.init(TestRunner.java:289)
	at org.testng.TestRunner.<init>(TestRunner.java:180)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:613)
	at org.testng.SuiteRunner.init(SuiteRunner.java:178)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:112)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1306)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1282)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1131)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.RuntimeException
	at com.rationaleemotions.github.issue1107.TestClass.dp(TestClass.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	... 21 more
```

**Comment by sankouski-dzmitry** [comment]
@krmahadevan , sorry, I made a mistake, when composing example in Java. Actually, we writing tests in Kotlin, and kotlin example is 

`import org.testng.annotations.DataProvider
import org.testng.annotations.Factory
import org.testng.annotations.Test

class Test1() {
    lateinit var param: String

    @Factory(dataProvider = "dp")
    constructor(param: String) : this() {
        this.param = param
    }

    @Test
    fun test1() {
        println("Run test1 with param: $param")
    }

    @Test
    fun test2() {
        println("Run test2 with param: $param")
    }

    @DataProvider
    fun dp() : Array<Array<String>> {
        throw RuntimeException()
        return arrayOf(arrayOf("param1"), arrayOf("param2"))
    }
}`
The error is just `No tests found for given includes: [Test1](--tests filter)` , and no exception stack trace.

The idea is to run several tests methods in one test class, with exact same testdata.  
Interesting, if exception is removed from dataprovider, test run fine, but I not sure how it works 🤔. Documentation to Factory annotation states, that factory method  must return Object[], but kotlin constructor should return just instance of test class.
Wasn't able to  figure out Java equivalent to this kotlin example yet.

**Comment by juherr** [comment]
> Wasn't able to  figure out Java equivalent to this kotlin example yet.

You can try to put the `fun dp` in a `companion object` which should generate the expected static method.

**Comment by sankouski-dzmitry** [comment]
@krmahadevan , @juherr , here is the correct Java example 

```
import org.testng.annotations.DataProvider;
import org.testng.annotations.Factory;
import org.testng.annotations.Test;

public class Test1 {
    private String param;

    public Test1() {

    }

    @Factory(dataProvider = "dp")
    public Test1(String param) {
        this.param = param;
    }

    @Test
    public void test1() {
        System.out.println(String.format("Run test1 with param: $%s", param));
    }

    @Test
    public void test2() {
        System.out.println(String.format("Run test2 with param: $%s", param));
    }

    @DataProvider
    public Object[][] dp() {
        throw new RuntimeException("Data provider fail");
//        return new Object[][]{{"param1"}, {"param2"}};
    }
}
```

So we have a data provider, which is used on "class level", thus eliminating need to invoke dataprovider multiple times for each test method.

Error in this example is `No tests found for given includes: [Test1](filter.includeTestsMatching)` , no stacktrace

**Comment by juherr** [comment]
@sankouski-dzmitry Put your data provider static and it will work. Use a companion object with Kotlin and it should work too (I didn't test)
