### ISSUE TITLE
XMLReporter crashes if a test parameter is exactly "]]>"

### ISSUE THREAD

**Issue by lqc** [cbeust/testng#1111]
Stack trace:

```
13:53:37    [testng] java.lang.ArrayIndexOutOfBoundsException: 0
13:53:37    [testng] 	at org.testng.reporters.XMLStringBuffer.addCDATA(XMLStringBuffer.java:308)
13:53:37    [testng] 	at org.testng.reporters.XMLSuiteResultWriter.addParameter(XMLSuiteResultWriter.java:266)
13:53:37    [testng] 	at org.testng.reporters.XMLSuiteResultWriter.addTestMethodParams(XMLSuiteResultWriter.java:250)
13:53:37    [testng] 	at org.testng.reporters.XMLSuiteResultWriter.addTestResult(XMLSuiteResultWriter.java:154)
13:53:37    [testng] 	at org.testng.reporters.XMLSuiteResultWriter.addTestResults(XMLSuiteResultWriter.java:130)
13:53:37    [testng] 	at org.testng.reporters.XMLSuiteResultWriter.writeAllToBuffer(XMLSuiteResultWriter.java:74)
13:53:37    [testng] 	at org.testng.reporters.XMLSuiteResultWriter.writeSuiteResult(XMLSuiteResultWriter.java:52)
13:53:37    [testng] 	at org.testng.reporters.XMLReporter.writeSuiteToBuffer(XMLReporter.java:120)
```

That's because `"]]>".split("]]>")` is an empty array

**Comment by juherr** [comment]
Thanks for the report.
