### ISSUE TITLE
[Bug] ConcurrentModificationException when generating JUnit report

### ISSUE THREAD

**Issue by gdemecki** [cbeust/testng#1212]
### TestNG Version

6.9.13.6 (latest available)

I've just upgraded from **6.8.8**  to **6.9.13.6**. But now, every time when all my tests pass, I'm getting  an exception and thus `junitreports/` is not generated. 
It is a regression bug. In previouss TestNG versions it has never happened, now it happens every time and is easily reproducible.

Versions tested: 
 * 6.8.8 - OK
 * 6.9.9 - OK
 * 6.9.10 - OK
 * 6.9.13.3 - FAILED
 * 6.9.13.6 - FAILED

So this bug has been introduced somewhere between 6.9.10 and 6.9.13.3 versions.

### Expected behavior

Generate JUnit reports without any `java.util.ConcurrentModificationException`.

### Actual behavior

I'm launching my tests via maven, without any concurrency. All is done **sequentially**. Anyway, when all tests pass, during generation of the JUnit reports, I'm getting:

```
07:55:19.603 INFO  | some logs ....
[TestNG] Reporter org.testng.reporters.JUnitReportReporter@27222045 failed
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at org.testng.reporters.JUnitReportReporter.getNextConfiguration(JUnitReportReporter.java:220)
	at org.testng.reporters.JUnitReportReporter.generateReport(JUnitReportReporter.java:105)
	at org.testng.TestNG.generateReports(TestNG.java:1175)
	at org.testng.TestNG.run(TestNG.java:1102)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Tests run: 82, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.182 sec - in TestSuite

Results :

Tests run: 82, Failures: 0, Errors: 0, Skipped: 0
```

### Is the issue reproductible on runner?

I'm using Maven 3.2.5, with Oracle JDK  1.7.0_75 and maven-surefire-plugin:2.18.1

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by gdemecki** [comment]
It seems to duplicate the  #1168 issue.
