### ISSUE TITLE
ITestResult injection is failing in BeforeMethod method

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1298]
From https://github.com/cbeust/testng-eclipse/issues/307

**Comment by juherr** [comment]
And exception from https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/internal/TestResult.java#L233 should have a message.

**Comment by missedone** [comment]
what I observed on my local with TestNG 6.0 is the stacktrack below:
```
java.lang.RuntimeException
	at org.testng.internal.TestResult.toString(TestResult.java:233)
	at org.testng.internal.TestResult.toString(TestResult.java:219)
	at org.testng.remote.strprotocol.TestResultMessage.toString(TestResultMessage.java:354)
	at org.testng.remote.strprotocol.TestResultMessage.<init>(TestResultMessage.java:130)
	at org.testng.remote.strprotocol.TestResultMessage.<init>(TestResultMessage.java:148)
	at org.testng.remote.strprotocol.RemoteTestListener1.onTestFailure(RemoteTestListener1.java:68)
	at org.testng.remote.strprotocol.RemoteTestListener1.onConfigurationFailure(RemoteTestListener1.java:98)
	at org.testng.internal.Invoker.runConfigurationListeners(Invoker.java:1686)
	at org.testng.internal.Invoker.handleConfigurationFailure(Invoker.java:305)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:241)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
```

this happens when runConfigurationListeners, at this phase, the ITestResult is still at initial state, its status is `-1`, so I still think the workaround/fix for this, is to print message rather than throw exception in a toString() method, and normally I think it make sense that make sure calling toString() is alway successfully, and throw exception at where do depends on the status.

**Comment by krmahadevan** [comment]
Maybe we can classify `-1` as `CREATED` (indicating that an `ITestResult` object has been created for a corresponding TestNG method, but it doesn't have any state yet, instead of classifying it as `UNKNOWN` ). Thoughts @missedone @juherr ?

**Comment by missedone** [comment]
👍 , `CREATED=-1` looks good to me.
