### ISSUE TITLE
TestNG 6.11 no longer works with java 7

### ISSUE THREAD

**Issue by rburgst** [cbeust/testng#1407]
### TestNG Version
> 6.11

### Expected behavior
testng should still work with java 7

### Actual behavior
due to the jcommander 1.64 dependency, it no longer works

### Is the issue reproductible on runner?

- [x] Shell
- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample

Jcommander > 1.59 requires java 8
https://github.com/cbeust/jcommander/issues/257#issuecomment-270311395

**Comment by rburgst** [comment]
FYI this is the exception stacktrace if you try to run with java 7:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/beust/jcommander/ParameterException : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

```

**Comment by missedone** [comment]
duplicates with #1377
