### ISSUE TITLE
Default Method @Test Inheritance and Mixin Pattern

### ISSUE THREAD

**Issue by tjni** [cbeust/testng#1502]
### TestNG Version
> 6.9.11+ (I believe)

### Expected behavior

Some libraries allow mixin behavior using default interface methods.

For example, in AssertJ:

```
@Test
public class MyTest implements WithAssertions {
  public void testSomething() {
    assertThat(true).isTrue();
  }
}
```

or in mockito-java8:

```
@Test
public class MyTest implements WithMockito {
  public void testSomething() {
    MyClass thing = mock(MyClass.class);
  }
}
```

The `assertThat` and `mock` methods are examples of default interface methods. The interface provides entry points to the library methods.

These interfaces also provide void methods, such as `fail(String)` on the `WithAssertions` interface and `verifyNoMoreInteractions(Object...)` on the `WithMockito` interface.

While I understand that there are use cases for which default methods should be run as tests, what I expect in this case is that somehow these methods, which are not intended to be tests, are ignored by a class-level `@Test` annotation.

### Actual behavior

See errors such as:

```
org.testng.TestNGException: 
Cannot inject @Test annotated Method [fail] with [class java.lang.String].
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:244)
	at org.testng.internal.Parameters.createParameters(Parameters.java:172)
	at org.testng.internal.Parameters.createParameters(Parameters.java:458)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:569)
```

**Comment by krmahadevan** [comment]
@tjni - But default methods exist only in JDK8. TestNG is still in JDK7. So not sure how we would be able to address this, till TestNG gets to JDK8 as well.

**Comment by juherr** [comment]
When you annotate a class with `@Test`, you assume all methods are tests.

We use the JDK7 and I don't if the API allows us to determine if a method is a default one or not.

But I don't know either what is supposed to be the default behavior of TestNG with default methods (ping @cbeust) 

As a workaround, excluding methods with a pattern in a suite file may work.

**Comment by tjni** [comment]
Thank you for engaging with me on this, @krmahadevan and @juherr! I myself haven't made up my mind yet on what the default behavior should be, so I'm looking forward to discussing this.

About workarounds, I do have one for my project that isn't too brittle. It uses an `IMethodInterceptor` to filter out methods declared in these known mixin interfaces. I think there must be a better solution than this, because both writing this interceptor and attaching it to TestNG through the build system requires some level of expertise. However, because of this workaround, I'm in no hurry, so let's take our time and get things right.

One observation is that, when there are legitimate cases in which some inherited public methods are tests and others are not, the author of that test or the class/interface containing it is best positioned to make that determination. This information would probably live best nearby.

Another consideration that I think is relevant, which actually seems quite obvious when written down, is that the author of a method not intended to be a test doesn't need to know about the existence of TestNG, while the author of a method that _is_ intended to be a test should be aware of TestNG.

**Comment by juherr** [comment]
In fact, the main issue is using `@Test` on a class because you have no easy way to customize the test detection. And that's why I recommend using the annotation on methods.

Don't expect a quick fix because the issue won't be easy to fix (but it could be fun!) :)

**Comment by slawekjaranowski** [comment]
From 7.0.0 version JDK 8 is required - maybe this issue should be refreshed

**Comment by krmahadevan** [comment]
@slawekjaranowski - Sure. Can you help share what would your expectations be from TestNG as part of getting this issue addressed? I am not sure if we still know what should be the outcome of this. Perhaps you could share some examples etc., that will make the requirement a bit more clearer.

**Comment by slawekjaranowski** [comment]
My expectations is to check again this issue, by author in the best way.

As I see from comments root cause was JDK 7 - and now TestNG use JDK 8 so maybe this can be closed.
