### ISSUE TITLE
TestNG exits with a zero when there are configuration failures

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#1517]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
When there's a configuration failure in a TestNG execution via its api, TestNG should be exiting with a non-zero status.

### Actual behavior
TestNG exits with a zero status.

### Is the issue reproductible on runner?

- [X] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

Here's a simple test class
```java
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class AppTest {

    @BeforeClass
    public void beforeClass() {
        throw new RuntimeException("Simulating a configuration failure");
    }
    @Test
    public void testMethod() {
        System.err.println("Hello world");
    }
}
```

Here's a runner class that runs the above mentioned test class
```java
import org.testng.TestNG;

public class TestRunner {
    public static void main(String[] args) {
        TestNG testNG = new TestNG();
        testNG.setTestClasses(new Class[]{AppTest.class});
        testNG.setVerbose(3);
        testNG.run();
        System.err.println("Return code : " + testNG.getStatus());
    }
}
```

Actual output:

```shell
===== Invoked methods
  AppTest.beforeClass()[pri:0, instance:com.rationaleemotions.AppTest@6a38e57f] 1782113663
=====
FAILED CONFIGURATION: @BeforeClass beforeClass
java.lang.RuntimeException: Simulating a configuration failure
	at com.rationaleemotions.AppTest.beforeClass(AppTest.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:165)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at com.rationaleemotions.TestRunner.main(TestRunner.java:12)

SKIPPED: testMethod
java.lang.RuntimeException: Simulating a configuration failure
	at com.rationaleemotions.AppTest.beforeClass(AppTest.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:165)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at com.rationaleemotions.TestRunner.main(TestRunner.java:12)


===============================================
    Command line test
    Tests run: 1, Failures: 0, Skips: 1
    Configuration Failures: 1, Skips: 0
===============================================


===============================================
Command line suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 0
===============================================

Return code : 0

Process finished with exit code 0
```

More Details available in this thread : https://groups.google.com/d/msg/testng-users/WlX5H5B8fwo/m_GR0svPAQAJ

**Comment by fangyishu** [comment]
I still get this problem for testng v6.14.3.

**Comment by krmahadevan** [comment]
@fangyishu - The latest released version for TestNG is `7.0.0-beta5` Please retry using that. If the issue still persists, please help share a simple standalone test project which can be used to reproduce the problem.

you may have to add a `<repository>` tag to your pom file to consume this beta release

```xml
 <repository>
                    <id>jcenter</id>
                    <name>jcenter</name>
                    <url>http://jcenter.bintray.com</url>
                </repository>
```

**Comment by fangyishu** [comment]
@krmahadevan do you have any doc on `7.0.0-beta5`, my testing code cannot be executed since @BeforeClass cannot be found as `org.testng.annotations.BeforeClass` any more.

**Comment by krmahadevan** [comment]
@fangyishu - That is not possible. `beta4` was a bad build, but `beta5` is a valid build. There is no fundamental change in terms of getting rid of annotations etc., So I don't have any doc.

**Comment by fangyishu** [comment]
@krmahadevan , sorry. I just started a clean project and find it works with `v6.14.3`. The problem might comes from the sbt plugin.
