### ISSUE TITLE
Can't run tests from IDEA

### ISSUE THREAD

**Issue by kateleiza** [cbeust/testng#1584]
### TestNG Version
latest, based on f39036f89c6b2807b1333e691662c09b3cc7d0ed commit

### Expected behavior
Can run test suite from IDEA 

### Actual behavior
```
org.testng.TestNGException:` java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\Katya\.IdeaIC2017.3\system\temp-testng-customsuite.xml
	at org.testng.TestNG.parseSuite(TestNG.java:316)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:331)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:45)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\Katya\.IdeaIC2017.3\system\temp-testng-customsuite.xml
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	at org.testng.xml.Parser.parse(Parser.java:151)
	at org.testng.TestNG.parseSuite(TestNG.java:293)
	... 3 more
```

**Comment by eyehwan** [comment]
Such excpetion is caused by `URI.create(m_fileName)` from `org.testng.xml.Parser.parse()`, because `URI.create(m_fileName)` would always check if the given string `m_fileName `is a legal URI. 
Apparantly `C:\Users\Katya\.IdeaIC2017.3\system\temp-testng-customsuite.xml` is a only file path. 

I can push for a review to fix it, because I also met such problem recently.
