### ISSUE TITLE
Parallel Execution causes Test methods to run before config methods run to completion

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#1660]
### TestNG Version
> Note: only the latest version is supported
6.13.1

As a user, I am trying to execute my suite xml with parallel mode set as "methods". I have a test class that contains 2 test methods and 1 before class method.

### Expected behavior
Test methods should only start running after all the configuration methods have run to completion.

### Actual behavior

Test methods are running even before the configuration methods have finished.

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

Suite xml file that is used 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite" verbose="2" parallel="methods">
    <test name="test" parallel="methods" verbose="2" thread-count="10">
        <classes>
            <class name="com.rationaleemotions.MultiThreadingSample"/>
        </classes>
    </test>
</suite>
```

```java
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.util.Random;
import java.util.concurrent.TimeUnit;

public class MultiThreadingSample {
    private String name;

    @BeforeClass
    public void setup() throws InterruptedException {
        TimeUnit.SECONDS.sleep(new Random().nextInt(30));
        name = "Krishnan";
        print("setup");
    }

    @Test
    public void test1() {
        print("test1");
        System.err.println(name + " has " + name.length() + " characters ");
    }

    @Test
    public void test2() {
        print("test2");
        System.err.println(name + " has " + name.length() + " characters ");
    }

    private void print(String prefix) {
        System.err.println("Running " + prefix + " on thread [" + Thread.currentThread().getId() + "]");
    }
}
```

Output

```
...
... TestNG 6.13.1 by Cédric Beust (cedric@beust.com)
...
Running test2 on thread [12]
Running setup on thread [11]

Running test1 on thread [11]
Krishnan has 8 characters 

java.lang.NullPointerException
	at com.rationaleemotions.MultiThreadingSample.test2(MultiThreadingSample.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

PASSED: test1
FAILED: test2
java.lang.NullPointerException
	at com.rationaleemotions.MultiThreadingSample.test2(MultiThreadingSample.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)


===============================================
    test
    Tests run: 2, Failures: 1, Skips: 0
===============================================

===============================================
Suite
Total tests run: 2, Failures: 1, Skips: 0
===============================================


Process finished with exit code 0

```

**Comment by PredatorVI** [comment]
I've verified this on my end.  I've attached a project that uses only Maven POM settings to reproduce.
[TestNGTest.zip](https://github.com/cbeust/testng/files/1602505/TestNGTest.zip)

The output:

```
--- maven-surefire-plugin:2.12.4:test (default-cli) @ TestNGTest ---
Surefire report directory: C:\Projects\Temp\TestNGTest\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running MultiThreadingExample
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@3a82f6ef
Running test2 on thread [14]
Running setup on thread [13]
Running test1 on thread [13]
Krishnan has 8 characters 
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 19.762 sec <<< FAILURE!
test2(MultiThreadingExample)  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.NullPointerException
	at MultiThreadingExample.test2(MultiThreadingExample.java:27)


Results :

Failed tests:   test2(MultiThreadingExample)

Tests run: 2, Failures: 1, Errors: 0, Skipped: 0

------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 23.101 s
Finished at: 2018-01-03T22:43:08-07:00
Final Memory: 16M/291M
------------------------------------------------------------------------

```

**Comment by juherr** [comment]
The issue could be somewhere in the graph.
Configuration methods are just dependencies of some methods, so like `dependsOnMethods`.
But, as I remember, it is expected to have parallel run for methods even if there is `dependsOnMethods` between them.
If it is right, we may change the behavior or treat configuration method differently.

**Comment by krmahadevan** [comment]
@PredatorVI - It looks like this issue has gotten fixed (perhaps as a side effect of some other bug fix. Which is it, I am yet to figure out) in TestNG `6.14-SNAPSHOT`. Can you please quickly check ?

Here's a console log

```bash
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
...
... TestNG 6.14-SNAPSHOT by Cédric Beust (cedric@beust.com)
...

Running setup on thread [12]
Running test1 on thread [12]
Running test2 on thread [13]
Krishnan has 8 characters 
Krishnan has 8 characters 
PASSED: test1
PASSED: test2

===============================================
    test
    Tests run: 2, Failures: 0, Skips: 0
===============================================

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 28.443 sec - in TestSuite

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by PredatorVI** [comment]
Sorry for the delay, I was on a cruise :-).  I forced a 30 sec sleep in setup to make sure tests waited and have verified that the the 6.14-SNAPSHOT does indeed work as expected.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running MultiThreadingExample
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@23ceabc1
Running setup on thread [13]
Running test1 on thread [13]
Krishnan has 8 characters 
Running test2 on thread [14]
Krishnan has 8 characters 
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 30.731 sec

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by krmahadevan** [comment]
Based on @PredatorVI  comments, I am closing this issue.
