### ISSUE TITLE
Guice injector failed to create when module contains internal inject of concrete type.

### ISSUE THREAD

**Issue by Kedanachi** [cbeust/testng#1698]
### TestNG Version
6.14.2

### Expected behavior
Injector should be created without any failure

### Actual behavior
```
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) A just-in-time binding to test.GuiceTest$ExampleSingleton was already configured on a parent injector.
  at test.GuiceTest$GuiceExampleModule.configure(GuiceTest.java:14)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
	at org.testng.GuiceHelper.getInjector(GuiceHelper.java:38)
	at org.testng.TestRunner.getInjector(TestRunner.java:1110)
	at org.testng.internal.ClassImpl.getInstanceFromGuice(ClassImpl.java:139)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:119)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:190)
	at org.testng.TestClass.getInstances(TestClass.java:95)
	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:81)
	at org.testng.TestClass.init(TestClass.java:73)
	at org.testng.TestClass.<init>(TestClass.java:38)
	at org.testng.TestRunner.initMethods(TestRunner.java:389)
	at org.testng.TestRunner.init(TestRunner.java:271)
	at org.testng.TestRunner.init(TestRunner.java:241)
	at org.testng.TestRunner.<init>(TestRunner.java:167)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:663)
	at org.testng.SuiteRunner.init(SuiteRunner.java:260)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1295)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1273)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

### Is the issue reproductible on runner?
- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
```java
import com.google.inject.*;
import org.testng.Assert;
import org.testng.annotations.Guice;
import org.testng.annotations.Test;

@Guice(modules = GuiceTest.GuiceExampleModule.class)
public class GuiceTest {
    public static class GuiceExampleModule implements Module {
        @Override
        public void configure(Binder binder) {
            binder.bind(ExampleSingleton.class).toInstance(new ExampleSingleton());
        }

        @Provides
        @Inject
        public AnotherSingleton provideAnotherSingleton(ExampleSingleton example) {
            return new AnotherSingleton();
        }
    }

    public static class ExampleSingleton {}
    public static class AnotherSingleton {}

    @Inject
    ExampleSingleton m_singleton;

    @Test
    public void singletonShouldWork() {
        Assert.assertNotNull(m_singleton);
    }
}
```

**Additional info**
Works fine when you remove @Inject from GuiceExampleModule.

**Comment by juherr** [comment]
Thank for the report.

It looks more like a bad usage of guice because I've never seen provider methods with `@Inject`  on it.
In fact, Guice is supposed to inject parameters of the provider methods with the configured object and you don't need to add `@Inject`.

I close the issue but feel free to reopen it if you think TestNG can do something.
