### ISSUE TITLE
assertEquals() for float[] array containing NaN 

### ISSUE THREAD

**Issue by archiecobbs** [cbeust/testng#1734]
Someone forgot that `Float.NaN != Float.NaN` even though `Float.NaN` = `Float.NaN`.

Same thing with `double[]`.

### TestNG Version
6.4.12

### Expected behavior

`Assert.assertEquals(new float[] { Float.NaN }, new float[] { Float.NaN })`

No exception

### Actual behavior

Exception

### Is the issue reproductible on runner?

- [x] Maven

### Test case sample

`Assert.assertEquals(new float[] { Float.NaN }, new float[] { Float.NaN })`

**Comment by archiecobbs** [comment]
Suggest comparing values [as is done in Arrays.equals()](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/util/Arrays.java#Arrays.equals%28float%5B%5D%2Cfloat%5B%5D%29) using `Float.floatToIntBits()`, etc.

**Comment by juherr** [comment]
Thanks for the report!
We already had a similar issue in the past https://github.com/cbeust/testng/pull/908 and we didn't take the time to check all NaN possible values.

**Comment by juherr** [comment]
You said Double.NaN doesn't work? Could you confirm?

**Comment by archiecobbs** [comment]
I didn't actually test `assertEquals(double[], double[])` but from code inspection it appeared to have the same problem.

**Comment by krmahadevan** [comment]
@juherr - I will take a go at this. But can you please help me understand what all needs to be covered as part of fixing this bug ?

**Comment by juherr** [comment]
@krmahadevan It is just adding some tests like in #908 and fix issues if any.
- Test Double.NaN, Float.NaN
- Test maybe some others constants too like POSITIVE_INFINITY or NEGATIVE_INFINITY (maybe some others if relevant)
- Test array of these values

Another subject but maybe a assertEqualsDeep(java.lang.Object[] actual, java.lang.Object[] expected)

**Comment by atulagrawal** [comment]
@krmahadevan - Can i take this up or you have already started the changes?

**Comment by krmahadevan** [comment]
I haven't started work on this. Please feel free to proceed further.

**Comment by atulagrawal** [comment]
I tried following two tests:
 @Test
  public void compareFloatArraysWithNaNValues() {
    Assert.assertEquals(new float[] { Float.NaN }, new float[] { Float.NaN });
  }

@Test
  public void compareDoubleArraysWithNaNValues() {
    Assert.assertEquals(new double[] { Double.NaN }, new double[] { Double.NaN });
  }
and i got following errors respectively:
float NaN
java.lang.AssertionError: arrays differ firstly at element [0]; expected value is <NaN> but was <NaN>. 

	at org.testng.Assert.fail(Assert.java:97)
	at org.testng.Assert.assertEquals(Assert.java:345)
	at org.testng.Assert.assertEquals(Assert.java:329)
	at org.testng.AssertTest.compareFloatArraysWithNaNValues(AssertTest.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:620)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:751)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1022)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:135)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:116)
	at org.testng.TestRunner.privateRun(TestRunner.java:653)
	at org.testng.TestRunner.run(TestRunner.java:509)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:365)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:359)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:55)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:90)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1135)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1065)
	at org.testng.TestNG.runSuites(TestNG.java:995)
	at org.testng.TestNG.run(TestNG.java:963)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)

double NaN:
java.lang.AssertionError: arrays differ firstly at element [0]; expected value is <NaN> but was <NaN>. 

	at org.testng.Assert.fail(Assert.java:97)
	at org.testng.Assert.assertEquals(Assert.java:375)
	at org.testng.Assert.assertEquals(Assert.java:359)
	at org.testng.AssertTest.compareDoubleArraysWithNaNValues(AssertTest.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:620)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:751)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1022)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:135)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:116)
	at org.testng.TestRunner.privateRun(TestRunner.java:653)
	at org.testng.TestRunner.run(TestRunner.java:509)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:365)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:359)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:55)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:90)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1135)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1065)
	at org.testng.TestNG.runSuites(TestNG.java:995)
	at org.testng.TestNG.run(TestNG.java:963)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)

I think this is working as expected in latest version but i will add unit tests for explicit validation.

**Comment by atulagrawal** [comment]
I have updated the unit tests in following PR - https://github.com/cbeust/testng/pull/1842
Please review and merge.

**Comment by atulagrawal** [comment]
@krmahadevan - Thanks. I will keep this in mind in future PRs.
