### ISSUE TITLE
TestNG documentation: unrunnable XML configurations

### ISSUE THREAD

**Issue by Warfront1** [cbeust/testng#1774]
### TestNG Version

6.14.3
### Expected behavior
The following documentation code to be runnable, or be modified to be runnable.
Obviously it is a snippet, so the full xml wouldn't be expected, but atleast the snippet itself should be complete.
One way to make this runnable is to wrap it in classes tags. IE.

```xml
        <classes>
            <class name= "TestWebServer" />
        </classes>
  ```

![Factory docs](https://i.gyazo.com/3706fbabf88d26de9fd54cbef0e388cd.png)

### Actual behavior
The XML in the IDE shows errors, as well as when you attempt to run you receive a NPE
```
org.testng.TestNGException: java.lang.NullPointerException
	at org.testng.TestNG.parseSuite(TestNG.java:327)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:348)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:45)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.NullPointerException
	at org.testng.xml.TestNGContentHandler.endElement(TestNGContentHandler.java:747)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.emptyElement(XMLDTDValidator.java:766)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:357)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2787)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at org.testng.xml.XMLParser.parse(XMLParser.java:38)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:16)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:9)
	at org.testng.xml.Parser.parse(Parser.java:152)
	at org.testng.xml.Parser.parse(Parser.java:233)
	at org.testng.TestNG.parseSuite(TestNG.java:295)
```

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
Implementation:
TestWebServer class

```java
import org.testng.annotations.Test;

public class TestWebServer {
    @Test(parameters = { "number-of-times" })
    public void accessPage(int numberOfTimes) {
        while (numberOfTimes-- > 0) {
            // access the web page
        }
    }
}
```

Testng xml

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Suite1" verbose="1" >
    <test name="T1">
        <parameter name="number-of-times" value="10"/>
        <class name= "TestWebServer" />
    </test>

    <test name="T2">
        <parameter name="number-of-times" value="20"/>
        <class name= "TestWebServer"/>
    </test>

    <test name="T3">
        <parameter name="number-of-times" value="30"/>
        <class name= "TestWebServer"/>
    </test>

</suite>
```

**Comment by Warfront1** [comment]
As a side note, I sort of like the way the `incorrect` xml reads.

**Comment by juherr** [comment]
@krmahadevan Do you think it is possible to avoid the NPE here?

**Comment by krmahadevan** [comment]
@juherr - Sure we can. But if we were to, then we should be avoiding it across the codebase for that class. Do you think its worth the effort, especially when the xml by itself is malformed ?
