### ISSUE TITLE
TestNGException when a @Factory method is initializing the class with a custom class object

### ISSUE THREAD

**Issue by virendrachaudhary06** [cbeust/testng#1797]
### TestNG Version
6.8

### Expected behavior
TestNGException when a @Factory method is initializing the class with a custom class object.
Factory annotated method is working fine if the test class is initialized with any built class

### Actual behavior
Getting the following exception

```
org.testng.TestNGException: 
The factory method class com.xyz.createPlatform.SampleTest.getData() threw an exception
	at org.testng.internal.FactoryMethod.invoke(FactoryMethod.java:93)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:140)
	at org.testng.TestRunner.initMethods(TestRunner.java:409)
	at org.testng.TestRunner.init(TestRunner.java:235)
	at org.testng.TestRunner.init(TestRunner.java:205)
	at org.testng.TestRunner.<init>(TestRunner.java:153)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:522)
	at org.testng.SuiteRunner.init(SuiteRunner.java:157)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:111)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1273)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1260)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1114)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.NullPointerException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.FactoryMethod.invoke(FactoryMethod.java:81)
	... 14 more

Process finished with exit code 0
Empty test suite.
```

### Is the issue reproducible on runner? Yes

I can reproduce this in maven and IntelliJ IDEA

### Test case sample
```java
public class SampleTest {

    private Person person;
    public SampleTest(Person person ){
        this.person = person;
    }

    @org.testng.annotations.Test
    public void sampeTest(){
        System.out.println(person);

    }
    @Factory
    public Object[] getData() throws IOException {
        return new Object[]{
                new SampleTest(new Person("me", 28)),
                new SampleTest(new Person("Sam", 30))
        };
    }

}

 class Person{
    private String name;
    private int age ;

    public Person(String name, int age){
        this.name = name;
        this.age = age;
    }
}
```

**Comment by juherr** [comment]
Could you try with `static` on `getData`?

**Comment by virendrachaudhary06** [comment]
Amazingly, it worked.
Thank you so much.

**Comment by krmahadevan** [comment]
Closing this issue.

**Comment by juherr** [comment]
@krmahadevan I think we can improve the user feedback with an advice instead of a stacktrace.

**Comment by krmahadevan** [comment]
@juherr 

@virendrachaudhary06 is using a very old version of TestNG. 

When I try the same using the latest released version of TestNG viz., `6.14.3`, here's what TestNG responds 

```java
org.testng.TestNGException: 
Can't invoke public java.lang.Object[] com.rationaleemotions.github.issue1797.SampleTest.getData(): either make it static or add a no-args constructor to your class
	at org.testng.internal.Utils.checkInstanceOrStatic(Utils.java:793)
	at org.testng.internal.FactoryMethod.<init>(FactoryMethod.java:90)
	at org.testng.internal.TestNGClassFinder.processFactory(TestNGClassFinder.java:209)
	at org.testng.internal.TestNGClassFinder.processMethod(TestNGClassFinder.java:179)
	at org.testng.internal.TestNGClassFinder.processClass(TestNGClassFinder.java:171)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:121)
	at org.testng.TestRunner.initMethods(TestRunner.java:370)
	at org.testng.TestRunner.init(TestRunner.java:271)
	at org.testng.TestRunner.init(TestRunner.java:241)
	at org.testng.TestRunner.<init>(TestRunner.java:167)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:663)
	at org.testng.SuiteRunner.init(SuiteRunner.java:260)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1295)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1273)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

```

So I think we are good here. WDYT ?

**Comment by juherr** [comment]
Yes, it's perfect!
