### ISSUE TITLE
Unable to understand testNg Exception

### ISSUE THREAD

**Issue by prvn83** [cbeust/testng#1839]
### TestNG Version
I am getting a testNg exception which I am unable to understand. I have googled for error cause but I have not got anything there. I am running Two classes in testNg classes in the same tag. It is giving me "No free nodes found in:[" error. Here are my two TestClasses. Here is first class Named loginPageTest
`public class loginPageTest extends TestBase {
	
	private static login login;
	

	@BeforeMethod
	public void setup() throws Exception {
		intialization();
		 login = new login();
	
	}
	
	@Test(priority=1,groups="login")
	public void titleVerification() {
		
		String validateTitleMethod = login.validateTitleMethod();
		Assert.assertEquals(validateTitleMethod, "OrangeHRM");
	}
	
	@Test(priority=2,groups="login")
	public void logoVerification() {
		 boolean validatePagelogo = login.validatePagelogo();
		 Assert.assertTrue(validatePagelogo);
	}
	
	@Test(priority=3,groups="login")
	public void loginTest() {
		login.loginMethod();
	}
	
	@AfterMethod
	public void teardown() {
		driver.quit();
	}

}`
Here are another testClass Named HomePageTest
`public class HomePageTest extends TestBase {

    private static login login;
     private static Home home;
    @BeforeMethod(alwaysRun=true)
    public void setup() throws Exception {
        intialization();
         login = new login();
         home = login.loginMethod();

    }

    @Test(priority=1,groups="Home")
    public void ValidateHomeUserTest() {
        home.HomePageUserValidate();
    }

    @Test(priority=2,groups="Home")
    public void ValidateMenuTest() throws InterruptedException {
        Assert.assertTrue(home.ValidateMenu("Admin"),"Menu is not present");

    }
    //dependsOnMethods= {"ValidateMenuTest"}
    @Test(dependsOnMethods= {"ValidateMenuTest"})
    public void clickOnAdminTest() {

        home.ClickOnAdmin();
    }

    @AfterMethod
    public void teardown() {
        driver.quit();
    }

}`

Testng XML:
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Orange CRM Tests" >
  <test name="Orange CRM Tests">
    <classes>

       <class name="com.crm.qa.testcases.loginPageTest" /> 
        <class name="com.crm.qa.testcases.HomePageTest" />

    </classes>
  </test> 
</suite> 
`
Error:
`[RemoteTestNG] detected TestNG version 6.14.3
org.testng.TestNGException: 
No free nodes found in:[DynamicGraph 
  Ready:[loginPageTest.loginTest()[pri:3, instance:com.crm.qa.testcases.loginPageTest@4883b407], loginPageTest.logoVerification()[pri:2, instance:com.crm.qa.testcases.loginPageTest@4883b407], loginPageTest.titleVerification()[pri:1, instance:com.crm.qa.testcases.loginPageTest@4883b407], HomePageTest.ValidateMenuTest()[pri:2, instance:com.crm.qa.testcases.HomePageTest@7d9d1a19], HomePageTest.clickOnAdminTest()[pri:0, instance:com.crm.qa.testcases.HomePageTest@7d9d1a19], HomePageTest.ValidateHomeUserTest()[pri:1, instance:com.crm.qa.testcases.HomePageTest@7d9d1a19]]
  Running:[]
  Finished:[]
  Edges:
     HomePageTest.clickOnAdminTest()[pri:0, instance:com.crm.qa.testcases.HomePageTest@7d9d1a19]
        HomePageTest.ValidateMenuTest()[pri:2, instance:com.crm.qa.testcases.HomePageTest@7d9d1a19]
        loginPageTest.logoVerification()[pri:2, instance:com.crm.qa.testcases.loginPageTest@4883b407]
        loginPageTest.loginTest()[pri:3, instance:com.crm.qa.testcases.loginPageTest@4883b407]
     HomePageTest.ValidateMenuTest()[pri:2, instance:com.crm.qa.testcases.HomePageTest@7d9d1a19]
        loginPageTest.titleVerification()[pri:1, instance:com.crm.qa.testcases.loginPageTest@4883b407]
        HomePageTest.ValidateHomeUserTest()[pri:1, instance:com.crm.qa.testcases.HomePageTest@7d9d1a19]
        loginPageTest.logoVerification()[pri:2, instance:com.crm.qa.testcases.loginPageTest@4883b407]
        loginPageTest.titleVerification()[pri:1, instance:com.crm.qa.testcases.loginPageTest@4883b407]
     HomePageTest.ValidateHomeUserTest()[pri:1, instance:com.crm.qa.testcases.HomePageTest@7d9d1a19]
        HomePageTest.clickOnAdminTest()[pri:0, instance:com.crm.qa.testcases.HomePageTest@7d9d1a19]
        loginPageTest.loginTest()[pri:3, instance:com.crm.qa.testcases.loginPageTest@4883b407]
        loginPageTest.titleVerification()[pri:1, instance:com.crm.qa.testcases.loginPageTest@4883b407]
     loginPageTest.logoVerification()[pri:2, instance:com.crm.qa.testcases.loginPageTest@4883b407]
        loginPageTest.titleVerification()[pri:1, instance:com.crm.qa.testcases.loginPageTest@4883b407]
        HomePageTest.ValidateHomeUserTest()[pri:1, instance:com.crm.qa.testcases.HomePageTest@7d9d1a19]
     loginPageTest.loginTest()[pri:3, instance:com.crm.qa.testcases.loginPageTest@4883b407]
        loginPageTest.logoVerification()[pri:2, instance:com.crm.qa.testcases.loginPageTest@4883b407]
        HomePageTest.ValidateMenuTest()[pri:2, instance:com.crm.qa.testcases.HomePageTest@7d9d1a19]
     loginPageTest.titleVerification()[pri:1, instance:com.crm.qa.testcases.loginPageTest@4883b407]
        HomePageTest.clickOnAdminTest()[pri:0, instance:com.crm.qa.testcases.HomePageTest@7d9d1a19]
]
    at org.testng.TestRunner.privateRun(TestRunner.java:642)
    at org.testng.TestRunner.run(TestRunner.java:505)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
    at org.testng.SuiteRunner.run(SuiteRunner.java:364)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
    at org.testng.TestNG.runSuites(TestNG.java:1049)
    at org.testng.TestNG.run(TestNG.java:1017)
    at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)`

I am getting an error when I am running both testclasses together in XML but here are two cases where it is working fine: 1. When I am running individual test ( one at a time) through XML, then it works fine. 2. When I am adding "priority=3" annotation in HomePageTest.clickOnAdminTest() , and running both tests together in XML then also it is working fine.

HomePageTest.clickOnAdminTest() is depend upon another method in HomaPageTest class, then why do I need to mention priority in HomePageTest.clickOnAdminTest() also? and if it is mandatory to mention priority then how does it is working without priority adding when I am running individual HomePageTest individually?

Please help to understand this.

### Expected behaviour
It should run properly.

### Actual behaviour
Throwing exception.

### Is the issue reproducible on the runner?

- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by prvn83** [comment]
If I mention two different Test classes in same test tag in testNg XML then how will priority and dependency mentioned for test methods work here?

**Comment by prvn83** [comment]
@krmahadevan  Thanks for the quick solution. It is working when I add priority 3. 
Another thing is that when I wrote each test in separate Test <tag> without adding priority 3 in clickOnAdminTest then  it is working fine. So If I mention two different tests in same Test <tag> then all test methods get connected somehow and due to which I an error?
