### ISSUE TITLE
Is there a way to immitate try, catch, finally for all testmethods using any testng feature?

### ISSUE THREAD

**Issue by formynet** [cbeust/testng#1916]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior

I have maven testng project used with extent reports and listeners to deal with on testsuccess and test failure that do the job of handling screenshots and other resources needed for my framework. Some times people do not use assertions and just use extent logs to fail some of the steps. So when some one does not use the assertions but there tests fail with extent log steps, testng sees the test as passed and extent sees the test as fail. I tried to Assert.fail in ontestsuccess and AfterMethod but it leaves a duplicate result for the method in testng results. This means I have the first instance of testmethod passing in testng and during the call to ontestsuccess or aftermethod, when I fail the method based on extent report status, I have one more instance of testng method logged with fail. I want to handle the testresult before testng goes to ontestsuccess. Is there a way to imitate below for all test methods in my framework using listeners or any other reasonable way:

```java
testmethod(){
try{

----steps

}catch{
}
finally{
if(ExtentTestStatus is fail)
    iTestResult.setStatus to fail
}
}
```

I tried to catchup with this question on other platforms but have not been lucky yet! Hope my question gets answered by some one here!

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by juherr** [comment]
It should work if you throw an exception:

```java
} finally {
  if(ExtentTestStatus is fail) {
    throw new MyException();
  }
}
```

**Comment by formynet** [comment]
I don't want to mandate automation tester to have a template for every
method. I was looking at a more cleaner implementation using listeners
where I could tap before ontestsuccess. That way I don't have to advocate
boiler plate usage for all methods.

**Comment by juherr** [comment]
Did you try IInvokedMethodListener?

**Comment by formynet** [comment]
do you mean me to try afterInvocation ? This gets executed after method starts execution but not before it completes execution. Is there any trick to listen to before a method completes execution?

**Comment by krmahadevan** [comment]
@formynet 

**Please ensure you are using TestNG 7.0.0-beta1 which is the latest released version as of today**

## Approach 1 - Using `IHookable` interface


The overall approach would be as below:

1. Create a base class which implements the `org.testng.IHookable` interface. 
2. Within its `run()` method, wrap the dispatching call to the test method within a `try..finally` call and include your logic for dealing with the `finally` clause. If you omit the `try..finally` block, then the logic will not get executed for `@Test` methods which fail.
3. Have all of your test classes extend the base class.

Here's a sample that shows how to use this:

**The base class**

```java
import org.testng.Assert;
import org.testng.IHookCallBack;
import org.testng.IHookable;
import org.testng.ITestResult;

public class SampleBaseTest implements IHookable {

  @Override
  public final void run(IHookCallBack callBack, ITestResult testResult) {
    try {
      callBack.runTestMethod(testResult);
    } finally {
      System.err.println("Finally block invoked for " + testResult.getMethod().getMethodName() + "()");

      if ("failme".equalsIgnoreCase(testResult.getMethod().getDescription())) {
        Assert.fail("Simulating a failure");
      }
    }
  }
}

```

**The child class**

```java
import org.testng.annotations.Test;

public class SampleTestcase extends SampleBaseTest {
  @Test
  public void testMethodWhichWillPass() {}

  @Test(description = "failme")
  public void testMethodWhichWillFail() {}
}

```

**Output**

```
Finally block invoked for testMethodWhichWillFail()

java.lang.AssertionError: Simulating a failure

	at org.testng.Assert.fail(Assert.java:97)
	at com.rationaleemotions.github.issue1916.SampleBaseTest.run(SampleBaseTest.java:18)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:249)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:654)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:589)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
	at org.testng.SuiteRunner.run(SuiteRunner.java:302)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

Finally block invoked for testMethodWhichWillPass()

===============================================
Default Suite
Total tests run: 2, Passes: 1, Failures: 1, Skips: 0
===============================================
```

## Approach 2 - Using TestNG listener

The other way in which it can be done is by leveraging the `org.testng.IInvokedMethodListener` listener.

Below is a sample that shows this in action.

```java
import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener;
import org.testng.ITestResult;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

@Listeners(TestStatusFudger.class)
public class AnotherSampleTestcase {
  @Test
  public void testMethodWhichWillPass() {}

  @Test(description = "failme")
  public void testMethodWhichWillFail() {}

  public static class TestStatusFudger implements IInvokedMethodListener {

    @Override
    public void afterInvocation(IInvokedMethod method, ITestResult testResult) {
      String description = method.getTestMethod().getDescription();
      if ("failme".equalsIgnoreCase(description)) {
        testResult.setStatus(ITestResult.FAILURE);
        testResult.setThrowable(new AssertionError("Simulating a failure"));
      }
    }
  }
}

```

**Output**
```
java.lang.AssertionError: Simulating a failure

	at com.rationaleemotions.github.issue1916.AnotherSampleTestcase$TestStatusFudger.afterInvocation(AnotherSampleTestcase.java:26)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:110)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:61)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:554)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:689)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:589)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
	at org.testng.SuiteRunner.run(SuiteRunner.java:302)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)


===============================================
Default Suite
Total tests run: 2, Passes: 1, Failures: 1, Skips: 0
===============================================
```

Closing this question with resolution as **Question answered**. Please comment if it doesn't help.
