### ISSUE TITLE
SAXParseException : how to handle special characters like '&' in testng?

### ISSUE THREAD

**Issue by saurabh-sp-tripathi** [cbeust/testng#1923]
### TestNG Version
6.14.3
### Expected behavior
Run a test on testng xml

### Actual behavior
throws below exceptions:
```
org.testng.TestNGException: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 166; The reference to entity "txtPromocode" must end with the ';' delimiter.
	at org.testng.TestNG.parseSuite(TestNG.java:327)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:348)
	at org.testng.TestNG.initializeEverything(TestNG.java:995)
	at org.testng.remote.support.RemoteTestNG6_12.initialize(RemoteTestNG6_12.java:22)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:97)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 166; The reference to entity "txtPromocode" must end with the ';' delimiter.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.scanAttributeValue(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanAttribute(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at org.testng.xml.XMLParser.parse(XMLParser.java:38)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:16)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:9)
	at org.testng.xml.Parser.parse(Parser.java:152)
	at org.testng.xml.Parser.parse(Parser.java:233)
	at org.testng.TestNG.parseSuite(TestNG.java:295)
	... 6 more
```

### Is the issue reproductible on runner?
Yes
- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ X] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="my-Test-Suite" parallel="tests" thread-count="1" verbose="10">
	<parameter name="testDataPath"  value="data/TestData.xlsx"/>
	<parameter name="URL"  value="https://mysite.com/en/private/hellword.jsp?fromLP=foo&txtBar=WW1221"/>
    <listeners>
        <listener class-name="com.foo.bar.MyClass"></listener>
    </listeners>
    <test name="DemoScript">
	    <groups>
			<run>
				<include name = "fail.*"/>
			</run>
		</groups>
        <classes>
            <class name="com.foo.bar.ko.TestClass"/>
        </classes>
    </test>     
</suite>

```

you don't have to write any class, just right clicking and running from eclipse will give this exception.
Basically SAXParser complains here about special character `&` ,  escaping it by replacing it to `&amp;` fixes the issue.

One solution could be, based on files with some kind of flag/mark, could be pre-processed by testNG to replace special character.

**UPDATE** : Same test works fine in yaml 
```
name: my-Test-Suite
verbose: 10
threadCount: 1
parallel: tests
parameters: { testDataPath: data/TestData.xlsx, URL: "https://mysite.com/en/private/hellword.jsp?fromLP=foo&txtBar=WW1221" }
listeners:
  - com.foo.bar.MyClass
tests:
  - name: DemoScript
    verbose: 10
    parallel: tests
    includedGroups: [ fail.* ]
    classes:
      - com.foo.bar.ko.TestClass
```
So may be yaml is better counter part. 

Also on second thought, it lesser of a bug and more of a limitation of testng xml. I would just keep it here as closed issue to help others (by appearing on search) to identify and fix when they encounter it.

**Comment by juherr** [comment]
You xml file is invalid because '&' is not a valid char.

Any XML editor will complain with files like that.

Your 2 workarounds are valid: 
* fixing your xml
* using another format
