### ISSUE TITLE
-usedefaultlisteners treated as file when supplied as command line argument to testNG

### ISSUE THREAD

**Issue by michapringle** [cbeust/testng#1928]
### TestNG Version 6.13.1, 7.0.0-beta1
> Note: only the latest version is supported

### Expected behavior
A command such as 
```
java -cp <bunch of classpath stuff> org.testng.TestNG -usedefaultlisteners false /Users/bob/development/miw/mcellblock/adbservice/test-results/3567/test_config/Test_Suite_testT13googleMaps.xml
```
should respect the documentation and turn off the default listeners. More info at 
https://stackoverflow.com/questions/5751416/turning-off-test-output-in-testng and http://testng.org/doc/documentation-main.html#testng-xml.
### Actual behavior
The arguments are treated as file paths, and the result is 
```
ProcessResults(exitCode=0, output=java.io.FileNotFoundException: /Users/bob/development/miw/mcellblock/adbservice/-usedefaultlisteners false testng.xml (No such file or directory)
    at java.base/java.io.FileInputStream.open0(Native Method)
    at java.base/java.io.FileInputStream.open(FileInputStream.java:196)
    at java.base/java.io.FileInputStream.<init>(FileInputStream.java:139)
    at org.testng.xml.Parser.parse(Parser.java:148)
    at org.testng.xml.Parser.parse(Parser.java:233)
    at org.testng.TestNG.parseSuite(TestNG.java:290)
    at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:334)
    at org.testng.TestNG.initializeEverything(TestNG.java:974)
    at org.testng.TestNG.run(TestNG.java:988)
    at org.testng.TestNG.privateMain(TestNG.java:1330)
    at org.testng.TestNG.main(TestNG.java:1299)
```

### Is the issue reproductible on runner?

- [ X ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
See the input and output above. Note that in my case, the problem occurs running a Java process, but I was also able to cut/paste the input and get the same error through a shell. This problem also occurs when suppling the arguments in a file, such as @file, in that case, the @file is loaded, and then the error above occurs.

**Comment by michapringle** [comment]
I confirmed with the simplest test case this works fine from the command line (as I suspected), so closing this.
