### ISSUE TITLE
[NPE] Reporter org.testng.reporters.jq.Main failed

### ISSUE THREAD

**Issue by shaburov** [cbeust/testng#1931]
### TestNG Version
7.0.0-beta1
Test class contains a single test method with executionCount = 0

### Expected behavior
NPE missing

### Actual behavior
```
Total tests >>>> 5
===============================================
DEFAULT TIGRA API suite
Total tests run: 4, Passes: 4, Failures: 0, Skips: 0
===============================================

[TestNG] Reporter org.testng.reporters.jq.Main@2892d68 failed
java.lang.NullPointerException
	at org.testng.reporters.jq.TimesPanel.maxTime(TimesPanel.java:124)
	at org.testng.reporters.jq.TimesPanel.getContent(TimesPanel.java:89)
	at org.testng.reporters.jq.BaseMultiSuitePanel.generate(BaseMultiSuitePanel.java:25)
	at org.testng.reporters.jq.Main.generateReport(Main.java:74)
	at org.testng.TestNG.generateReports(TestNG.java:1027)
	at org.testng.TestNG.run(TestNG.java:970)
	at org.touchbit.buggy.core.Buggy.run(Buggy.java:138)
	at org.touchbit.buggy.core.Buggy.main(Buggy.java:78)
	at com.ibclabs.aqa.latex.integration.ILatex.main(ILatex.java:9)

```
### Is the issue reproductible on runner?

- [x] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans
- [x] Jar

**Comment by krmahadevan** [comment]
@shaburov - Please help share a reproducible sample that can be used to recreate the problem. The stack trace doesn't hint at what is causing the NPE. So please share a sample.

**Comment by shaburov** [comment]
@kamilszymanski Your request is strange. Indeed, in stackTrace it is clearly indicated where the NPE originated.
`return m_totalTime.get(suite.getName());`
suite == null
**or**
suite.getName() == null
Other options cannot be.

Cut examples of suites:
![image](https://user-images.githubusercontent.com/15269131/46950423-56cc5d00-d08d-11e8-88b4-24c15f7e1bce.png)

![image](https://user-images.githubusercontent.com/15269131/46950522-998e3500-d08d-11e8-8ff1-34c8ddc851d1.png)

**Comment by krmahadevan** [comment]
> Your request is strange. Indeed, in stackTrace it is clearly indicated where the NPE originated.

@shaburov - Thats not the point. The stack trace is only pointing to the fact that `name` is null. What I am trying to understand is, how is `suite.getName()` is null ? The value is by default assigned with a value. So I would like to understand how is it being set to null. 

So I re-iterate what I asked for earlier. Please help provide a sample so that I can figure out under what circumstances is `suite.getName()` becoming `null`

**Comment by shaburov** [comment]
1. The problem with NPE in DefaultListeners (default report listeners) is not solved.
2. Nobody allowed himself to study the implementation of IReporter.generateReport () for default report listeners. Where the error actually occurs.
3. Error in the implementation of IReporter, however, the restriction was made in XmlSuite.java.
4. Not a single test has been added.

And the problem is that from Map m_totalTime.get (suite.getName ()) returns null when it is expected that the primitive long will return. Method signature: `private `**long**` maxTime(ISuite suite)`

@krmahadevan you need to get a little closer acquainted with java. For example, after reading several books.

Worse than this decision and come up with something difficult.

@juherr please reopen this issue.

**Comment by juherr** [comment]
But please, don't be so harsh. @krmahadevan always does a good job even here, you're right and a test should be added.
About the fix itself, the @krmahadevan 's fix looks to be a good start because `m_totalTime` is always supposed to have a value and the `maxTime` implementation will be ok once the fix will be applied.

**Comment by shaburov** [comment]
@juherr @krmahadevan Perhaps I expressed my thoughts in extremely dry form. I did not want to offend anyone. And in any case, I apologize.

Defect fixed. Test added.
The report for the suite without running tests is generated without errors.
![image](https://user-images.githubusercontent.com/15269131/47621326-24981200-db07-11e8-80ef-bb03639d344b.png)

**Comment by krmahadevan** [comment]
@shaburov 

> you need to get a little closer acquainted with java. For example, after reading several books.

Thanks for the advice. I will do so. I got into open source not because I was an expert in Java, but wanted to up my Java skills by writing more code and Open source IMO was the only place where I could do that and learn more. So yeah I am still on that task and haven't quite got there **YET**. Both @cbeust and @juherr have been kind enough to help me with my learning.. But as they say.. *I have miles to go*

But there are nicer way of pointing out at problems. It would be great if going forward you could point out problems than take a jab at the person who was trying to fixing the problems.

Couple of things 

1. The test that you have added in your PR basically just creates a suite object and tries to create a dummy suite and then tries to access the Model panel. That AFAIK is not a realistic way in which a user would use it. Because the root cause wasn't evident for me is why I was asking for a sample. 
2. It should **NOT** cause you to wait for a wrong fix in order to encourage you to raise a PR (like how you did now) when you know what the fix was. There are **NOT** many contributors here. So we would encourage you to raise a PR as well (if you do know the fix and how to reproduce it as in this case)

**Comment by Chathura1990** [comment]
Try to update your Testng version to 6.14.3. Hope it will help you.
