### ISSUE TITLE
when run test cmd ,Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException

### ISSUE THREAD

**Issue by Nyainqentanglha** [cbeust/testng#1932]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior

run test 
### Actual behavior
➜  test java org.testng.TestNG -Dversion
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.ParameterException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

### Is the issue reproductible on runner?

- [ ] Shell

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

### how run mvn project test case  with testng.jar cmd?

**Comment by juherr** [comment]
You must have the dependencies in the classpath.

**Comment by krmahadevan** [comment]
@Nyainqentanglha - If you are working with Maven, merely adding a dependency on TestNG should be enough.

If you are managing your class path manually, please make sure that you have the appropriate http://repo1.maven.org/maven2/com/beust/jcommander/ version also downloaded.

Closing this issue with resolution as *Question answered*
