### ISSUE TITLE
TestNG throws a misleading error when @Factory method returns empty array.

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#1953]
### TestNG Version
> Note: only the latest version is supported

`7.0.0-beta1`

### Expected behavior
TestNG should fail with a proper error message stating `No instances were produced by the Factory` (or) something on those lines

### Actual behavior
TestNG fails with a misleading error message which reads `An error occurred while instantiating class test.Main$MyTest. Check to make sure it can be instantiated`

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [X] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

```java
import org.testng.TestNG;
import org.testng.annotations.Factory;
import org.testng.annotations.Test;

public class Main {
    
    public static class MyTest {
        
        private final int i;

        public MyTest(int i) {
            this.i = i;
        }

        @Test
        public void testDownCall() {
            System.out.println("test: " + i);
        }   
    }

    @Factory
    public Object[] getTests() throws Throwable {
        return generateTests();
    }

    private Object[] generateTests() {
        return new Object[] {}; // erroneously returning empty array
    }

    public static void main(String[] args) throws Throwable {
        TestNG t = new TestNG();
        t.setTestClasses(new Class<?>[] { Main.class });
        t.run();
    }

}
```

Error message

```
Exception in thread "main" org.testng.TestNGException: 
An error occurred while instantiating class test.Main$MyTest. Check to make sure it can be instantiated
    at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:388)
    at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:336)
    at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:110)
    at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:188)
    at org.testng.TestClass.getInstances(TestClass.java:94)
    at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:79)
    at org.testng.TestClass.init(TestClass.java:71)
    at org.testng.TestClass.<init>(TestClass.java:36)
    at org.testng.TestRunner.initMethods(TestRunner.java:461)
    at org.testng.TestRunner.init(TestRunner.java:340)
    at org.testng.TestRunner.init(TestRunner.java:293)
    at org.testng.TestRunner.<init>(TestRunner.java:178)
    at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:603)
    at org.testng.SuiteRunner.init(SuiteRunner.java:194)
    at org.testng.SuiteRunner.<init>(SuiteRunner.java:125)
    at org.testng.TestNG.createSuiteRunner(TestNG.java:1230)
    at org.testng.TestNG.createSuiteRunners(TestNG.java:1209)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1058)
    at org.testng.TestNG.runSuites(TestNG.java:997)
    at org.testng.TestNG.run(TestNG.java:965)
    at test.Main.main(Main.java:32)
```

More details available in the TestNG forum https://groups.google.com/forum/#!topic/testng-users/yoKE5_suQcQ

**Comment by btiddle** [comment]
Using the sample code included in this issue, the error does not occur when using org.testng:testng:6.14.3. However, it does occur in subsequent versions.

```
Status  Version
Pass    org.testng:testng:6.14.3
Fail    org.testng:testng:7.0.0
Fail    org.testng:testng:7.1.0
Fail    org.testng:testng:7.3.0
```

**Comment by krmahadevan** [comment]
@btiddle - I am not sure as to what you are suggesting. The fix that was done here was ensure that the end user understands the reason behind the failure. The factory method is not returning any test class instances and so TestNG will not be able to run anything.
