### ISSUE TITLE
Parallel parameter doesn't work in YAML test suites

### ISSUE THREAD

**Issue by nietoc** [cbeust/testng#1965]
### TestNG Version
7.0.0-beta

### Expected behavior
`parallel` can be declared and used for test suite defined as YAML files

### Actual behavior
`Maven` test goal fails with the following error:
```
[ERROR] There was an error in the forked process
[ERROR] org.testng.internal.Yaml$TestNGConstructor.constructScalar(Lorg/yaml/snakeyaml/nodes/ScalarNode;)Ljava/lang/Object;
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] org.testng.internal.Yaml$TestNGConstructor.constructScalar(Lorg/yaml/snakeyaml/nodes/ScalarNode;)Ljava/lang/Object;
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:656)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
```

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
Test class
```
import org.testng.annotations.Test;

public class SampleTests {

    @Test
    public void firstTest() {
        System.out.println("First test");
    }

    @Test
    public void secondTest() {
        System.out.println("Second test");
    }
}
```

YAML test suite
```
name: YAML test
parallel: tests
tests:
- name: "First"
  classes:
  - name: SampleTests
    includedMethods:
    - firstTest

- name: "Second"
  classes:
  - name: SampleTests
    includedMethods:
    - secondTest
```

Maven pom file
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.nietoc</groupId>
    <artifactId>testng-yaml-test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <testng.version>7.0.0-beta1</testng.version>
        <maven.surefire.version>2.22.1</maven.surefire.version>
        <snakeyaml.version>1.23</snakeyaml.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.version}</version>
                <configuration>
                    <suiteXmlFiles>
                        <suiteXmlFile>testsuite.yaml</suiteXmlFile>
                    </suiteXmlFiles>
                    <properties>
                        <property>
                            <name>surefire.testng.verbose</name>
                            <value>2</value>
                        </property>
                    </properties>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>${testng.version}</version>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>${snakeyaml.version}</version>
        </dependency>
    </dependencies>

</project>
```

**Comment by nietoc** [comment]
You are correct, this issue is fixed on the current snapshot. Thank you.
