### ISSUE TITLE
TypeNotPresentExceptionProxy

### ISSUE THREAD

**Issue by Randgalt** [cbeust/testng#1976]
### TestNG Version

6.10

### Expected behavior

Tests complete as expected in Jenkins

### Actual behavior

Tests run fine locally, but with Jenkins after the tests are run a `TypeNotPresentExceptionProxy` is thrown for some reason.

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven on Jenkins
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

No test case. But here's a Jenkins run where it happens. https://builds.apache.org/job/Curator/63/console

Here's the stacktrace:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project curator-test-zk34: ExecutionException There was an error in the forked process
[ERROR] java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
[ERROR] at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
[ERROR] at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
[ERROR] at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
[ERROR] at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
[ERROR] at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
[ERROR] at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
[ERROR] at java.lang.reflect.Executable.declaredAnnotations(Executable.java:599)
[ERROR] at java.lang.reflect.Executable.declaredAnnotations(Executable.java:597)
[ERROR] at java.lang.reflect.Executable.getAnnotation(Executable.java:570)
[ERROR] at java.lang.reflect.Method.getAnnotation(Method.java:622)
[ERROR] at org.testng.internal.annotations.JDK15AnnotationFinder.findAnnotation(JDK15AnnotationFinder.java:111)
[ERROR] at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:77)
[ERROR] at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:40)
[ERROR] at org.testng.TestRunner.initMethods(TestRunner.java:403)
[ERROR] at org.testng.TestRunner.init(TestRunner.java:252)
[ERROR] at org.testng.TestRunner.init(TestRunner.java:222)
[ERROR] at org.testng.TestRunner.<init>(TestRunner.java:163)
[ERROR] at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:585)
[ERROR] at org.testng.SuiteRunner.init(SuiteRunner.java:189)
[ERROR] at org.testng.SuiteRunner.<init>(SuiteRunner.java:136)
[ERROR] at org.testng.TestNG.createSuiteRunner(TestNG.java:1375)
```

**Comment by Randgalt** [comment]
I posted this issue at Surefire (https://issues.apache.org/jira/browse/SUREFIRE-1612) and they insist the problem is in TestNg. I also just tried with the latest beta `7.0.0-beta1` and it fails in the same manner. So, I'm re-opening this. Here's is the full stacktrace from a run this morning:

```
[ERROR] ExecutionException There was an error in the forked process
[ERROR] sun.reflect.annotation.TypeNotPresentExceptionProxy
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException There was an error in the forked process
[ERROR] sun.reflect.annotation.TypeNotPresentExceptionProxy
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:494)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkPerTestSet(ForkStarter.java:441)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:293)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1194)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1022)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:868)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] sun.reflect.annotation.TypeNotPresentExceptionProxy
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:658)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:115)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:429)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:406)
[ERROR] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[ERROR] 	at java.lang.Thread.run(Thread.java:745)
[ERROR] 
```

**Comment by Tibor17** [comment]
@krmahadevan 
Can you have a look in the stack trace?
https://issues.apache.org/jira/browse/SUREFIRE-1612?focusedCommentId=16722617&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16722617

The stacktrace points to 
https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/internal/annotations/JDK15AnnotationFinder.java#L111

@Randgalt 
@krmahadevan 
I guess the stack pints to
https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/internal/annotations/JDK15AnnotationFinder.java#L132
or
https://github.com/cbeust/testng/blob/master/src/main/java/org/testng/internal/annotations/JDK15AnnotationFinder.java#L134

**Comment by Randgalt** [comment]
FWIW - I have a random guess as to what's going on. The module being compiled (https://github.com/apache/curator/tree/master/curator-test-zk34) uses a series of excludes to make sure old versions of Apache Curator JARs are used for testing purposes. Is it possible that a TestNG and/or Surefire Classloader from another module (or some other context?) is being used here and has references to the new versions of those JARs? This is really just a wild guess.

**Comment by Tibor17** [comment]
@Randgalt 
According to your stack trace you run tests in forked JVM and there is only System ClassLoader. You can see it. Run in debug mode `mvn -X test` and Surefire keeps Manifest-based JAR in `target/surefire/*.jar` on Linux. Windows placed the JAR in TEMP (see the logs).

**Comment by juherr** [comment]
The issue looks similar to https://stackoverflow.com/questions/14656543/typenotpresentexceptionproxy

**Comment by krmahadevan** [comment]
@Tibor17 - The error is stemming from the Java provided reflection APIs that TestNG is using to extract out various different information.
As @juherr also pointed out, this is usually due to a messed up class path.

@Randgalt - I ran the entire codebase (it did take a lot of time to run to completion) but I was able to simulate the problem on my local machine as well. So this is NOT a Jenkins specific problem for sure.

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:37 h
[INFO] Finished at: 2018-12-18T01:15:21+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project curator-test-zk34: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/krmahadevan/temp/curator/curator-test-zk34/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] ExecutionException There was an error in the forked process
[ERROR] sun.reflect.annotation.TypeNotPresentExceptionProxy
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException There was an error in the forked process
[ERROR] sun.reflect.annotation.TypeNotPresentExceptionProxy
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:494)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkPerTestSet(ForkStarter.java:441)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:293)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1194)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1022)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:868)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] sun.reflect.annotation.TypeNotPresentExceptionProxy
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:658)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:115)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:429)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:406)
[ERROR] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[ERROR] 	at java.lang.Thread.run(Thread.java:748)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :curator-test-zk34
✘-1 ~/temp/curator [master|✔]
```

To reproduce the problem, try cleaning up the relevant folders from your local `~/.m2/repository`. It should happen for you as well.

As you guessed as well, I am pretty sure that the `curator-test-zk34` is where you need to look for to understand where is this coming from (Since you perhaps have a better idea of the codebase than me).

I dont think TestNG has anything to do here in terms of fixing this issue.

I also don't think that surefire plugin maybe at fault here, because someone had faced this problem when using ant also. Please see [this](http://vshynkliar.blogspot.com/2014/09/sunreflectannotationtypenotpresentexcep.html) blog.

**Comment by Randgalt** [comment]
At long last I've found the problem. We had a test written ala:

```
@Test(expectedExceptions=KeeperException.NoWatcherException.class)
public void Foo
...
```

Under normal conditions this works fine. However, we also run the compiled code against an older version of ZooKeeper for compatibility reasons. The entire test class is annotated with `@Test(groups = Zk35MethodInterceptor.zk35Group)` which should exclude the class from being tested. However, I guess TestNG still parses all its annotations to set up some data. `KeeperException.NoWatcherException.class` does exist in old versions of ZooKeeper and this was causing the exception. It's frustrating that the error message gave no hint of what the missing type was. Could anything be improved in TestNG for this? If not, I'll close this issue.

**Comment by juherr** [comment]
`@Test` on methods usually can override values from the `@Test` on the class but I can remember the inheritance rule for `groups` and the documentation is not precise enough.
BTW, I'm not sure we can avoid the annotation introspection because of annotation inheritance.

@krmahadevan Do you confirm?

**Comment by Randgalt** [comment]
> Maybe we could try wrapping the exception within a try catch block wherein we at least print the information

That would help a lot. If I had seen a more informative error message it would have saved a lot of time.
