### ISSUE TITLE
ThreadPoolExecutor ConcurrentModificationException

### ISSUE THREAD

**Issue by shaburov** [cbeust/testng#2000]
### TestNG Version
7.0.0-beta1

### Actual behavior
Exception in thread "TestNG-test=default-1" java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1139)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:118)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)

### Is the issue reproductible on runner?
Jar

### Test case sample
no test case

**Comment by juherr** [comment]
How can we reproduce the issue?

**Comment by krmahadevan** [comment]
@shaburov - The codebase has gone through some changes after we released `beta1`. Can you please retry using `beta3` and post back the updated stack trace ?

**Comment by juherr** [comment]
@shaburov Any update?
