### ISSUE TITLE
org.testng.ITestNGListener: Provider io.qameta.allure.testng.AllureTestNg could not be instantiated

### ISSUE THREAD

**Issue by AjitSingh12** [cbeust/testng#2006]
### TestNG Version  6.7
PLEASE share with me any suggestions .

### Expected behavior
Test can be run 

### Actual behavior
org.testng.ITestNGListener: Provider io.qameta.allure.testng.AllureTestNg could not be instantiated
show me ERROR
### Is the issue reproductible on runner?

- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ

"C:\Program Files\Java\jdk1.8.0_77\bin\java.exe"
java.util.ServiceConfigurationError: org.testng.ITestNGListener: Provider io.qameta.allure.testng.AllureTestNg could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:967)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:906)
	at org.testng.TestNG.initializeEverything(TestNG.java:996)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/Versioned
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.qameta.allure.FileSystemResultsWriter.<init>(FileSystemResultsWriter.java:27)
	at io.qameta.allure.AllureLifecycle.getDefaultWriter(AllureLifecycle.java:281)
	at io.qameta.allure.AllureLifecycle.<init>(AllureLifecycle.java:47)
	at io.qameta.allure.Allure.getLifecycle(Allure.java:30)
	at io.qameta.allure.testng.AllureTestNg.<init>(AllureTestNg.java:119)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 8 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.Versioned
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more

Process finished with exit code -1

**Comment by krmahadevan** [comment]
This is not related to TestNG. You seem to have a messed up CLASSPATH and you are missing the class `Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/Versioned` which is what is causing the failure.

Please fix your CLASSPATH. If you are still having issues, I would suggest that you please post your query on the allure forums. TestNG doesn't own/maintain the allure framework.

**Comment by AjitSingh12** [comment]
i have tried multiple version of TestNG and also add dependencies "com.fasterxml.jackson "
then i got the "Cannot instantiate class CrmTestRunner"

**Comment by krmahadevan** [comment]
Like I mentioned before this is not a TestNG issue. The classes that you are mentioning aren't part of the TestNG codebase. Request you to please seek help from a relevant allure forum. Not much that can be done from TestNG to fix this issue.

**Comment by AjitSingh12** [comment]
thanks and i move to allure
