### ISSUE TITLE
skipped test depends on unsuccessful finished method, but that method success in second retry

### ISSUE THREAD

**Issue by charlieBat** [cbeust/testng#2050]
Basically there are two tests: test1 and test2. They both have retryAnalyzer that retry up to 3 times. 
test2 is depending on test1. 
test1 failed in the first run, but success in second retry.
test2 is marked skipped because first run of test1 failed.

https://groups.google.com/forum/#!topic/testng-users/_0hx5C8kawE

### TestNG Version
testng-7.0.0-beta3

### Expected behavior
both test case passed

### Actual behavior
first one passed, second one skipped

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [X] Ant
- [X] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

Test code:
```java
import org.testng.annotations.Test;

import com.inmotion.listeners.MyRetryAnalyzer;

public class DemoTestcases extends BaseWebTestNG {
	private int mark = 0;
	
	@Test(retryAnalyzer = MyRetryAnalyzer.class)
	public void test1() {
		if(mark == 0) {
			mark ++;
			fail();
		}
	}
	
	@Test(retryAnalyzer = MyRetryAnalyzer.class, dependsOnMethods = { "test1" })
	public void test2() {
		System.out.println("running test2");
	}
}
```

My MyRetryAnalyzer Class:

```java
public class MyRetryAnalyzer implements IRetryAnalyzer {
	private static int MAX_RETRY_COUNT = 3;

	AtomicInteger count = new AtomicInteger(MAX_RETRY_COUNT);

	public boolean isRetryAvailable() {
		return (count.intValue() > 0);
	}

	@Override
	public boolean retry(ITestResult result) {
		if (!result.isSuccess()) {
			if (isRetryAvailable()) {
				System.out.println("Going to retry test case: " + result.getMethod() + ", "
						+ (MAX_RETRY_COUNT - count.intValue() + 1) + " out of " + MAX_RETRY_COUNT);
				count.decrementAndGet();
				result.setStatus(ITestResult.FAILURE);
				return true;
			} else {
				result.setStatus(ITestResult.FAILURE);
			}
		} else {
			result.setStatus(ITestResult.SUCCESS);
		}

		return false;
	}
}
```

**Comment by krmahadevan** [comment]
@charlieBat - I think this may be related to the TestNG eclipse plugin. You might want to file an issue with the testng eclipse project here https://github.com/cbeust/testng-eclipse/issues

Here's a main method that when executed doesn't show the problem. The test code is the same as yours.

```java
  public static void main(String[] args) {
    TestNG testng = new TestNG();
    testng.setVerbose(2);
    testng.setTestClasses(new Class[] {DemoTestcases.class});
    SimpleReporter reporter = new SimpleReporter();
    testng.addListener(reporter);
    testng.run();
  }
}
```

The listener
```java
import java.util.List;
import java.util.Set;
import org.testng.IReporter;
import org.testng.ISuite;
import org.testng.ISuiteResult;
import org.testng.ITestResult;
import org.testng.xml.XmlSuite;

public class SimpleReporter implements IReporter {

  @Override
  public void generateReport(
      List<XmlSuite> xmlSuites, List<ISuite> suites, String outputDirectory) {
    for (ISuite suite : suites) {
      generateReport(suite);
    }
  }

  private void generateReport(ISuite suite) {
    for (ISuiteResult each : suite.getResults().values()) {
      generateReport(each);
    }
  }

  private void generateReport(ISuiteResult result) {
    generateReport("Failed Tests", result.getTestContext().getFailedTests().getAllResults());
    generateReport("Passed Tests", result.getTestContext().getPassedTests().getAllResults());
    generateReport("Skipped Tests", result.getTestContext().getSkippedTests().getAllResults());
  }

  private void generateReport(String msg, Set<ITestResult> results) {
    if (results.isEmpty()) {
      System.err.println("No  " + msg);
      return;
    }
    System.err.println("Printing " + msg);
    for (ITestResult result : results) {
      generateReport(result);
    }
  }

  private void generateReport(ITestResult result) {
    System.err.println("Method name " + result.getMethod().getMethodName());
    System.err.println("Invocation " + result.getMethod().getCurrentInvocationCount());
  }
}
```

Output
```
Going to retry test case: DemoTestcases.test1()[pri:0, instance:com.rationaleemotions.github.issue2050.DemoTestcases@59fa1d9b], 1 out of 3
running test2
PASSED: test1
PASSED: test2
RETRIED: test1
java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:97)
	at org.testng.Assert.fail(Assert.java:102)
	at com.rationaleemotions.github.issue2050.DemoTestcases.test1(DemoTestcases.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner.privateRun(TestRunner.java:763)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at com.rationaleemotions.github.issue2050.DemoTestcases.main(DemoTestcases.java:32)


===============================================
    Command line test
    Tests run: 3, Failures: 0, Skips: 0, Retries: 1
===============================================


===============================================
Command line suite
Total tests run: 3, Passes: 2, Failures: 0, Skips: 0, Retries: 1
===============================================

No  Failed Tests
Printing Passed Tests
Method name test1
Invocation 2
Method name test2
Invocation 1
Printing Skipped Tests
Method name test1
Invocation 2

Process finished with exit code 0
```
