### ISSUE TITLE
JUnit TestSuite not handled correctly in Reports

### ISSUE THREAD

**Issue by ewaryst1** [cbeust/testng#2069]
### TestNG Version
> Note: only the latest version is supported
Broken with 6.9.13.3 (6.9.10 is latest version where this works)

### Expected behavior
JUnit TestSuite classes should be run, and failed test methods should be reported as failures. Even if one uses JUnit 4+.

### Actual behavior
JUnit TestCase classes are run and results are reported correctly whereas JUnit TestSuite classes are run but failed test methods and successful methods are not reported.

(!) Note that this only happens with JUnit 4+ on the classpath, not with JUnit 3!

There are Exceptions in reporters:

1. jq Reporter
[TestNG] Reporter org.testng.reporters.jq.Main@1dd02175 failed
java.lang.NullPointerException
        at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:124)
        at org.testng.reporters.jq.Model.getTestResultName(Model.java:142)
        at org.testng.reporters.jq.ChronologicalPanel.getContent(ChronologicalPanel.java:68)
        at org.testng.reporters.jq.BaseMultiSuitePanel.generate(BaseMultiSuitePanel.java:24)
        at org.testng.reporters.jq.Main.generateReport(Main.java:63)
        at org.testng.TestNG.generateReports(TestNG.java:1175)
        at org.testng.TestNG.run(TestNG.java:1102)
        at org.testng.TestNG.privateMain(TestNG.java:1425)
        at org.testng.TestNG.main(TestNG.java:1394)

2. SuiteHTMLReporter
[TestNG] Reporter org.testng.reporters.SuiteHTMLReporter@4df828d7 failed
java.lang.NullPointerException
        at org.testng.reporters.SuiteHTMLReporter$1.compare(SuiteHTMLReporter.java:366)
        at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
        at java.base/java.util.TimSort.sort(TimSort.java:220)
        at java.base/java.util.Arrays.sort(Arrays.java:1515)
        at java.base/java.util.ArrayList.sort(ArrayList.java:1749)
        at java.base/java.util.Collections$SynchronizedList.sort(Collections.java:2468)
        at java.base/java.util.Collections.sort(Collections.java:177)
        at org.testng.reporters.SuiteHTMLReporter.generateMethodsChronologically(SuiteHTMLReporter.java:369)
        at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:73)
        at org.testng.TestNG.generateReports(TestNG.java:1175)
        at org.testng.TestNG.run(TestNG.java:1102)
        at org.testng.TestNG.privateMain(TestNG.java:1425)
        at org.testng.TestNG.main(TestNG.java:1394)

### Is the issue reproductible on runner?
I just tested with eclipse (testng plugin 6.14.3) and Testng.main "path/to/suite.xml"

- [x] Shell
- [ ] Maven
- [x] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

Instructions:
Extract zip and run with
>    gradlew rii

To see how a correct report should look like change the testng version in test/build.gradle to e.g. 6.9.10

Note that the test suite contains a test method that should fail and therefore we expect the task to fail if testng works correctly!

[minimal.zip](https://github.com/cbeust/testng/files/3136964/minimal.zip)

**Comment by juherr** [comment]
Thanks for the report. Could you try with the latest version? `7.0.0-beta4`

**Comment by ewaryst1** [comment]
The latest version seems to have changed w.r.t. org.testng.annotations.Test, this annotation is missing in the jar file!

I tried with repositories:
1. jcenter()
2. mavencentral()

Both contain an 7.0.0-beta4 artifact without the annotation! Was this annotation intentionally removed or are these artifacts broken? E.g. the jar at http://jcenter.bintray.com/org/testng/testng/7.0.0-beta4/

When using
maven {  url 'https://oss.sonatype.org/content/repositories/snapshots' }

with 7.0.0-SNAPSHOT (testng-7.0.0-20190501.063748-94.jar) I see the org.testng.annotations.Test annotation but the issue still occurs!

With 7.0.0-beta5 it also still occurs.

With 7.0.0-beta6 I'm getting a strange error:
`Error: Unable to initialize main class org.testng.TestNG
Caused by: java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException`

**Comment by krmahadevan** [comment]
@ewaryst1 - `beta4` was a bad build. I wasn't aware that `beta6` was released 😮 
So am not sure what is causing that issue.

@cbeust / @juherr  - When did we release `beta6` ?
