### ISSUE TITLE
SSL SunCertPathBuilderException exception when trying to download DTD from testng.org

### ISSUE THREAD

**Issue by ghenadied** [cbeust/testng#2081]
### TestNG Version
> Note: only the latest version is supported
6.13.1 but in this case not important
last java 8.

### Actual behavior
`
private static void testSSL() throws IOException {
        String url = "https://testng.org";

        URLConnection conn = new URL(url).openConnection();

        if (conn != null) {
            try (BufferedReader br = new BufferedReader(new InputStreamReader(conn.getInputStream()))) {
                String input;

                while ((input = br.readLine()) != null) {
                    System.out.println(input);
                }
            }
        }
    }
`

exception

`
avax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
`

### Is the issue reproductible on runner?

- [ ] Shell
- [x ] Maven
- [x ] Gradle
- [x] Ant
- [x ] Eclipse
- [x ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cbeust** [comment]
I just checked and the certificate seems to be valid:

![image](https://user-images.githubusercontent.com/92322/58404156-5d568600-8019-11e9-83d2-0c2263f7030a.png)

**Comment by ghenadied** [comment]
![image](https://user-images.githubusercontent.com/34937746/58404632-3aa28c80-806e-11e9-80cd-94f82f16902c.png)
It says it was issues on 26 May 2019. So anyone using an old trusted certification store won't recognize it until updated.

**Comment by cbeust** [comment]
I did renew it yesterday, yes.

Anything I need to do?
