### ISSUE TITLE
when using 'parallel="methods"' the "time-out" on suite level refers to the execution time of the whole suite, not to the execution time of individual tests

### ISSUE THREAD

**Issue by mischcon** [cbeust/testng#2092]
### TestNG Version
7.0.0-beta5

### Expected behavior
When a 'time-out' value at suite level has been set, then TestNG should interrupt each test that takes longer than the provided 'time-out' and mark it as 'failed'.
The suite continues until all tests are done.

### Actual behavior
When a 'time-out' value at suite level has been set, then TestNG stops the whole suite after the time-out value has been reached.

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
testng.xml:
```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >

<suite name="Parallel Timeout Suite" parallel="methods" thread-count="1" time-out="2000">
    <test name="Parallel Timeout Test">
        <packages>
            <package name="com.testing.bug.*"/>
        </packages>
    </test>
</suite>
```

TestClass:
```
package com.testing.bug;

import org.testng.annotations.Test;


public class TestBug {

    private void sleep() {
        try {
            Thread.sleep(1000);
        } catch(InterruptedException e) {
            System.out.println("FAIL");
            e.printStackTrace();
        }
        System.out.println("SUCCESS");
    }

    @Test
    public void test_1() {
        sleep();
    }

    @Test
    public void test_2() {
        sleep();
    }

    @Test
    public void test_3() {
        sleep();
    }

}
```

Expected Output:
```
SUCCESS
SUCCESS
SUCCESS

===============================================
Parallel Timeout Suite
Total tests run: 3, Passes: 3, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0
```

Actual Output:
```
SUCCESS
FAIL
===============================================
Parallel Timeout Suite
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
===============================================

SUCCESS

Test ignored.
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.testing.bug.TestBug.sleep(TestBug.java:10)
	at com.testing.bug.TestBug.test_2(TestBug.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:51)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:41)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:306)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:278)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:590)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Process finished with exit code 0
```

### Note
This occurs if you set the suite property 'parallel' to 'methods'. If 'parallel' is set to 'none' everything works as expected.

**Comment by krmahadevan** [comment]
@juherr - Any suggestions on how to get this sorted out?

**Comment by juherr** [comment]
@krmahadevan What is strange is `at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)` because it should be run in parallel.
But as `thread-count="1"` it could be an optimisation.

BTW, the behavior looks good to me.

@mischcon Could you try with a higher `thread-count`?

**Comment by krmahadevan** [comment]
@juherr 

> What is strange is at `org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)` because it should be run in parallel.

I didn't get the relevance of this part. What is the strange part in https://github.com/cbeust/testng/blob/1ff4e019b5ef4b7af8d691a19d96ef2b520c7ed1/src/main/java/org/testng/internal/MethodRunner.java#L44-L47

The section that is causing the problem in this case is this https://github.com/cbeust/testng/blob/1ff4e019b5ef4b7af8d691a19d96ef2b520c7ed1/src/main/java/org/testng/internal/MethodInvocationHelper.java#L304-L313

when the thread count is greater than 1, it works fine.. its just that when we are conceptually simulating parallel execution, but confining it to a sequential mode (by having a thread count as 1) is when this crops up.

**Comment by juherr** [comment]
@krmahadevan Are we agree that it is not an issue and the behavior is the good one because of `thread-count="1"`?

**Comment by krmahadevan** [comment]
@juherr - To be honest, I am in a dilemma on how to conclude on this. That was where I was hoping to get some insights from you :)

**Comment by juherr** [comment]
It is the expected behavior.

**Comment by mischcon** [comment]
@juherr tested again with 'thread-count' set to 2. 
Issue is still present.

testng.xml:
```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >

<suite name="Parallel Timeout Suite" parallel="methods" thread-count="2" time-out="2000">
    <test name="Parallel Timeout Test">
        <packages>
            <package name="com.testing.bug.*"/>
        </packages>
    </test>
</suite>
```

TestClass:
```
package com.testing.bug;

import org.testng.annotations.Test;


public class TestBug {

    private void sleep() {
        try {
            Thread.sleep(1000);
        } catch(InterruptedException e) {
            System.out.println("FAIL");
            e.printStackTrace();
        }
        System.out.println("SUCCESS");
    }

    @Test
    public void test_1() {
        sleep();
    }

    @Test
    public void test_2() {
        sleep();
    }

    @Test
    public void test_3() {
        sleep();
    }

    @Test
    public void test_4() {
        sleep();
    }

    @Test
    public void test_5() {
        sleep();
    }

    @Test
    public void test_6() {
        sleep();
    }

    @Test
    public void test_7() {
        sleep();
    }

}
```

Output:
```
SUCCESS
SUCCESS
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:278)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:265)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.testing.bug.TestBug.sleep(TestBug.java:10)
	at com.testing.bug.TestBug.test_4(TestBug.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)

Process finished with exit code 0
FAIL
FAIL
Test ignored.
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
SUCCESS

	at com.testing.bug.TestBug.sleep(TestBug.java:10)

===============================================
	at com.testing.bug.TestBug.test_3(TestBug.java:30)
Parallel Timeout Suite
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Total tests run: 2, Failures: 0, Skips: 0
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
===============================================

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
```

**Comment by mischcon** [comment]
@juherr @krmahadevan do you need some additional information to reopen the issue or did I miss something? 

As far as I understand your comments, this behavior is okay if you set the ```thread-count``` to ```1```, but that it is not okay if you set the ```thread-count``` to something larger than ```1``` (e.g. ```2```).

As you can see in my last comment, the behavior occurs if you set the ```thread-count``` to ```2```, which should not be okay imho and if I understood your comments correct.

**Comment by juherr** [comment]
@mischcon What if you set thread-count to 7 (the number of test methods)?

**Comment by mischcon** [comment]
@juherr If I set the thread-count to 7, then each tests passes - but I do not think that this information adds any value to the issue (please correct me if I am wrong about this).

Since each test only takes approximately 1000ms (the specified 'sleep'), the timeout cannot occur because the overall test execution duration is less than 2000ms (the specified timeout).

**Comment by juherr** [comment]
@mischcon Sure, but I confirm that TestNG is working as expected.
If you want to set a method timeout (and not a suite timeout), you'll find the option on `@Test`.
If you don't want to set it by hand on every annotation, you can use an `IAnnotationTransformer`.

**Comment by mischcon** [comment]
@juherr Great! This is exactly what I was searching for :)

Side note: Maybe you could add this information to the official documentation, since this behavior is not described there. (In fact, the possibility to add a ```time-out``` value at suite level is not mentioned there at all)

Thank you for your support!
