### ISSUE TITLE
TestNG exits with a zero code when test method was failed

### ISSUE THREAD

**Issue by corviv** [cbeust/testng#2115]
### TestNG Version
5.x.x, 6.x.x, 7.0.0-beta7

### Expected behavior
TestNG should be exiting with a non-zero status when test was failed.

### Actual behavior
TestNG return zero exit code in any case.

### Is the issue reproductible on runner?

- [x] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample

    @Test
    public void test1() {
        Assert.assertEquals(1, 1);
    }

    @Test
    public void test2()  {
        Assert.assertEquals(1, 0);
    }

Default Suite
Total tests run: 2, Failures: 1, Skips: 0
Process finished with exit code 0

**Comment by krmahadevan** [comment]
I don't think this is a problem with TestNG per se. The exit codes that you are sharing is from IntelliJ (so you may have to follow up with the IntelliJ with a bug to get this sorted out)

Here's a sample, that uses the same above example

```java
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import org.testng.TestNG;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlTest;

public class TestRunner {
  public static void main(String[] args) {
    TestNG testng = new TestNG();
    String file = TestNG.class.getProtectionDomain().getCodeSource().getLocation().getFile();
    String version = new File(file).getParentFile().getName();
    if (!"7.0.0-beta7".equalsIgnoreCase(version)) {
      throw new IllegalStateException("Not running on " + version);
    }
    testng.setXmlSuites(Collections.singletonList(newSuite(TestClass.class)));
    testng.setVerbose(2);
    testng.run();
    System.err.println("Return code " + testng.getStatus());
    if (testng.getStatus() == 0) {
      throw new IllegalStateException("Bad return code of " + testng.getStatus());
    }
  }

  private static XmlSuite newSuite(Class<?>... classes) {
    XmlSuite xmlSuite = new XmlSuite();
    xmlSuite.setName("Sample_Suite");
    XmlTest xmlTest = new XmlTest(xmlSuite);
    xmlTest.setName("Sample_test");
    List<XmlClass> xmlClasses = new ArrayList<>();
    for (Class<?> clazz : classes) {
      xmlClasses.add(new XmlClass(clazz));
    }
    xmlTest.setXmlClasses(xmlClasses);
    System.err.println(xmlSuite.toXml());
    return xmlSuite;
  }
}
```

Here's the output

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Sample_Suite">
  <test thread-count="5" name="Sample_test">
    <classes>
      <class name="com.rationaleemotions.github.issue2115.TestClass"/>
    </classes>
  </test> <!-- Sample_test -->
</suite> <!-- Sample_Suite -->

PASSED: test1
FAILED: test2
java.lang.AssertionError: expected [0] but found [1]
	at org.testng.Assert.fail(Assert.java:97)
	at org.testng.Assert.assertEqualsImpl(Assert.java:136)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:839)
	at org.testng.Assert.assertEquals(Assert.java:849)
	at com.rationaleemotions.github.issue2115.TestClass.test2(TestClass.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at com.rationaleemotions.github.issue2115.TestRunner.main(TestRunner.java:22)


===============================================
    Sample_test
    Tests run: 2, Failures: 1, Skips: 0
===============================================


===============================================
Sample_Suite
Total tests run: 2, Passes: 1, Failures: 1, Skips: 0
===============================================

Return code 1

Process finished with exit code 0
```

Also I dont think the exit code that IntelliJ shows has got anything to do with the return code of TestNG.

**Comment by corviv** [comment]
I saw my mistake. Thank you.
