### ISSUE TITLE
Altered Exceptions via TestNG listeners are not honored

### ISSUE THREAD

**Issue by krmahadevan** [cbeust/testng#2155]
### TestNG Version
> Note: only the latest version is supported

`7.0.0`

### Expected behavior

If there's a failure in configuration/test method and if a TestNG listener is used to alter the failure reason by changing the exception, the changed throwable object should be honored and not the original cause of failure.

### Actual behavior

The original exception information is cascaded.

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Test class**

```java
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

@Listeners(LocalExceptionChangingListener.class)
public class SampleTestClass {

  @BeforeClass
  public void beforeClass() {
    //This line can be uncommented to simulate the situation in configuration failures
    //throw new IllegalArgumentException("illegal argument");
  }

  @Test
  public void testMethod() {
    throw new IllegalArgumentException("illegal argument");
  }
}
```

**TestNG listener**

```java
import java.util.List;
import java.util.stream.Collectors;
import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener;
import org.testng.IReporter;
import org.testng.ISuite;
import org.testng.ISuiteResult;
import org.testng.ITestContext;
import org.testng.ITestResult;
import org.testng.xml.XmlSuite;

public class LocalExceptionChangingListener implements IInvokedMethodListener, IReporter {

  @Override
  public void afterInvocation(IInvokedMethod method, ITestResult methodResult) {
    if (methodResult.getStatus() == ITestResult.FAILURE) {
      Throwable t = new Throwable("info " + methodResult.getThrowable().getMessage());
      t.setStackTrace(methodResult.getThrowable().getStackTrace());
      methodResult.setThrowable(t);
    }
  }

  @Override
  public void generateReport(
      List<XmlSuite> xmlSuites, List<ISuite> suites, String outputDirectory) {
    suites.forEach(this::generateReport);
  }

  private void generateReport(ISuite suite) {
    List<ITestContext> testContexts =
        suite.getResults().values().stream()
            .map(ISuiteResult::getTestContext)
            .collect(Collectors.toList());
    List<ITestResult> failedResults =
        testContexts.stream()
            .flatMap(context -> context.getFailedConfigurations().getAllResults().stream())
            .collect(Collectors.toList());
    failedResults.addAll(testContexts.stream()
        .flatMap(context -> context.getFailedTests().getAllResults().stream())
        .collect(Collectors.toList())
    );
    failedResults.forEach(this::generateReport);
  }

  private void generateReport(ITestResult result) {
    System.err.println("Method " + result.getMethod().getMethodName());
    System.err.println("Type " + (result.getMethod().isTest() ? " test method " : "config method"));
    System.err.println("Failure cause " + result.getThrowable().getMessage());
    System.err.println("Exception object " + result.getThrowable().getClass().getName());
  }
}
```

More information available in this thread https://groups.google.com/forum/#!topic/testng-users/D4yB60vdbIE

Execution output
```
java.lang.Throwable: info illegal argument

	at com.rationaleemotions.googleforums.exceptions.SampleTestClass.testMethod(SampleTestClass.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)


===============================================
Default Suite
Total tests run: 1, Passes: 0, Failures: 1, Skips: 0
===============================================

Method testMethod
Type  test method 
Failure cause info illegal argument
Exception object java.lang.Throwable

Process finished with exit code 0

```

**Comment by krmahadevan** [comment]
Issue is not reproducible. 
The failure cause correctly comes up with the altered message.
