### ISSUE TITLE
Couldn't set attributes in testng result xml file

### ISSUE THREAD

**Issue by Yamuna-Rani** [cbeust/testng#2192]
I am also facing same issue........

@krmahadevan   I know issue is closed but i need help on this and I am working on XRAY and facing the same issue. I tried the above solution but nothing happens.no attributes generated .....................
..............................................................
my test.java file:
```java
package CalcTest;


import org.testng.annotations.Test;
import org.testng.annotations.BeforeMethod;
import org.testng.AssertJUnit;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;
import org.testng.annotations.BeforeMethod;
import org.testng.AssertJUnit;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.AssertJUnit;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;
import org.testng.annotations.BeforeMethod;
import org.testng.AssertJUnit;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;
import org.testng.annotations.BeforeMethod;
import org.testng.AssertJUnit;
import org.testng.Assert;
import org.testng.annotations.Test;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Listeners;
import org.testng.Reporter;
import org.testng.reporters.XMLReporter;
import org.testng.ITestResult;
import Xray_Automation.Demo.*;
import Xray_Automation.Demo_annotations.Xray;
import Xray_Automation.Demo_annotations.XrayListener;
 
@Test
//@Listeners({XrayListener.class})
public class TMTest2 {
 
    @BeforeMethod
	@BeforeSuite
    public void setUp() throws Exception {
 
    }
 
    
	@AfterMethod
	@AfterSuite
    public void tearDown() throws Exception {
    }
 
 
    @DataProvider
    public Object[][] ValidDataProvider() {
        return new Object[][]{
            {  1, 2, 3 },
            {  2, 3, 4 },  // error or the data itself :)
            { -1, 1, 0 }
        };
    }
 
 
    @Test(dataProvider = "ValidDataProvider")
    @Xray(requirement = "CALC-1234", test = "CALC-1")
    public void CanAddNumbersFromGivenData(final int a, final int b, final int c)
    {
        AssertJUnit.assertEquals(Calculator.Add(a, b), c);
       // System.out.println(requirement);
    }
 
 
    @Test
    @Xray(requirement = "CALC-1234", test = "CALC-2", labels = "core addition")
    public void CanAddNumbers()
    {
        AssertJUnit.assertEquals(Calculator.Add(1, 1),2);
        AssertJUnit.assertEquals(Calculator.Add(-1, 1),0);
    }
 
 
    @Test
    @Xray(requirement = "CALC-1235", labels = "core")
    public void CanSubtract()
    {
        AssertJUnit.assertEquals(Calculator.Subtract(1, 1), 0);
        AssertJUnit.assertEquals(Calculator.Subtract(-1, -1), 0);
        AssertJUnit.assertEquals(Calculator.Subtract(100, 5), 95);
    }
 
 
    @Test
    @Xray(requirement = "CALC-1236")
    public void CanMultiplyX()
    {
        AssertJUnit.assertEquals(Calculator.Multiply(1, 1), 1);
        AssertJUnit.assertEquals(Calculator.Multiply(-1, -1), 1);
        AssertJUnit.assertEquals(Calculator.Multiply(100, 5), 500);
    }
 
 
    @Test
    @Xray(requirement = "CALC-1237")
    public void CanDivide()
    {
        AssertJUnit.assertEquals(Calculator.Divide(1, 1), 1);
        AssertJUnit.assertEquals(Calculator.Divide(-1, -1), 1);
        AssertJUnit.assertEquals(Calculator.Divide(100, 5), 20);
    }
 
 
    @Test
    @Xray(requirement = "CALC-1237")
    public void CanDoStuff()
    {
        Assert.assertNotEquals(true, true);
    }
 
}
```

....................................................................................................................................
```java
package Xray_Automation.Demo_annotations;

import java.lang.reflect.Method;

import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener;
import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.ITestNGMethod;
import org.testng.ITestResult;

import Rest_Request.ImportTesngResults;

import static java.lang.System.out;

import java.io.IOException;

import static java.lang.System.err;
 
/**
 * The listener interface for receiving Xray events.
 * The Listener can be automatically invoked when TestNG tests are run by using ServiceLoader mechanism.
 * You can also add this listener to a TestNG Test class by adding
 * <code>@Listeners({com.xpand.java.XrayAnnotationListener.class})</code>
 * before the test class
 *
 * @see Xray
 */
public class XrayListener implements IInvokedMethodListener, ITestListener  {
	String requirement=null;
	String test =null;
	String labels=null;
     
    boolean testSuccess = true;
     
     
    /* (non-Javadoc)
     * @see org.testng.IInvokedMethodListener#beforeInvocation(org.testng.IInvokedMethod, org.testng.ITestResult)
     */
    public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
  
    	
    	
        if(method.isTestMethod() && annotationPresent(method, Xray.class) ) {
        	
        	testResult.setAttribute("requirement", method.getTestMethod().getConstructorOrMethod().getMethod().getAnnotation(Xray.class).requirement()); 
     testResult.setAttribute("test", method.getTestMethod().getConstructorOrMethod().getMethod().getAnnotation(Xray.class).test());
           testResult.setAttribute("labels", method.getTestMethod().getConstructorOrMethod().getMethod().getAnnotation(Xray.class).labels());
            
         
        }
    	
         
    }
 
     
    private boolean annotationPresent(IInvokedMethod method, Class clazz) {
        boolean retVal = method.getTestMethod().getConstructorOrMethod().getMethod().isAnnotationPresent(clazz) ? true : false;
        return retVal;
    }
 
     
    /* (non-Javadoc)
     * @see org.testng.IInvokedMethodListener#afterInvocation(org.testng.IInvokedMethod, org.testng.ITestResult)
     */
    public void afterInvocation(IInvokedMethod method, ITestResult testResult) {
    	 
        if(method.isTestMethod()) {
            if( !testSuccess ) {
                testResult.setStatus(ITestResult.FAILURE);
            }
        }
        
      
        
    }
 
    public void onTestStart(ITestResult result) {
        // TODO Auto-generated method stub
         
    }
 
    public void onTestSuccess(ITestResult result) {
        // TODO Auto-generated method stub
         
    }
 
    public void onTestFailure(ITestResult result) {
        // TODO Auto-generated method stub
         
    }
 
    public void onTestSkipped(ITestResult result) {
        // TODO Auto-generated method stub
         
    }
 
    public void onTestFailedButWithinSuccessPercentage(ITestResult result) {
        // TODO Auto-generated method stub
         
    }
 
    public void onStart(ITestContext context) {
    	
    	 for(ITestNGMethod m1 : context.getAllTestMethods()) {
             if(m1.getConstructorOrMethod().getMethod().isAnnotationPresent(Xray.class)) {
                 //capture metadata information.
            	 requirement=  m1.getConstructorOrMethod().getMethod().getAnnotation(Xray.class).requirement();
            	 test= m1.getConstructorOrMethod().getMethod().getAnnotation(Xray.class).test();
                 labels= m1.getConstructorOrMethod().getMethod().getAnnotation(Xray.class).labels();
             }
         }
         
         
    }
 
    public void onFinish(ITestContext context) {
        // TODO Auto-generated method stub
    	
    	  ImportTesngResults callrest= new ImportTesngResults();
          try {
  			callrest.createtestexec();
  		} catch (IOException e) {
  			// TODO Auto-generated catch block
  			e.printStackTrace();
  		}
         
    }
     
}
```
.........................................................................................................................................................................
pom.xml

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
 
   <groupId>Xray_Automation</groupId>
  <artifactId>Demo</artifactId>
  <version>0.0.1-SNAPSHOT</version>
 
 
    <properties>
         
        <!--XRay Properties -->
  
        <!--IN PROFILE ~.m2/settings.xml-->
        <!--<xray.jiraURL></xray.jiraURL>
        <xray.resultsFormat>JUNIT</xray.resultsFormat>
        <xray.username>syed</xray.username>
        <xray.password>123qwe</xray.password>-->
  
        <xray.projectKey>TM</xray.projectKey>
        <!--
        <xray.testExecKey></xray.testExecKey>
        <xray.testPlanKey></xray.testPlanKey>
        <xray.testEnvironments></xray.testEnvironments>
        <xray.revision></xray.revision>
        -->
  
        <xray.surefire.location>${basedir}/target/surefire-reports</xray.surefire.location>
        <!--End Xray Properties -->
  
    </properties>
 
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <debug>true</debug>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
             
            <plugin>
 
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M3</version>
 
                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>
                    <suiteXmlFiles>
                      <suiteXmlFile>testng.xml</suiteXmlFile>
                    </suiteXmlFiles>
                    <properties>
                        <property>
                            <name>reporter</name>
                             <value>org.testng.reporters.XMLReporter:generateTestResultAttributes=true,generateGroupsAttribute=true</value>
                        </property>
                    </properties>
 
                </configuration>
             </plugin>
 
 
 
 
        </plugins>
    </build>
 
    <dependencies>
        <dependency>
          <groupId>org.testng</groupId>
          <artifactId>testng</artifactId>
          <version>6.11</version>
          <scope>test</scope>
        </dependency>
       
        
 
       
        <!-- https://mvnrepository.com/artifact/com.googlecode.json-simple/json-simple -->
<dependency>
    <groupId>com.googlecode.json-simple</groupId>
    <artifactId>json-simple</artifactId>
    <version>1.1.1</version>
</dependency>

<!-- https://mvnrepository.com/artifact/com.mashape.unirest/unirest-java -->
<dependency>
    <groupId>com.mashape.unirest</groupId>
    <artifactId>unirest-java</artifactId>
    <version>1.4.9</version>
</dependency>

<!-- https://mvnrepository.com/artifact/org.apache.httpcomponents/httpasyncclient-osgi -->
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpasyncclient-osgi</artifactId>
    <version>4.1.4</version>
</dependency>
<!-- https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient -->
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>4.5.10</version>
</dependency>
<!-- https://mvnrepository.com/artifact/org.json/json -->
<dependency>
    <groupId>org.json</groupId>
    <artifactId>json</artifactId>
    <version>20190722</version>
</dependency>
<!-- https://mvnrepository.com/artifact/org.apache.httpcomponents/httpcore -->
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpcore</artifactId>
    <version>4.4.12</version>
</dependency>
<!-- https://mvnrepository.com/artifact/commons-io/commons-io -->
<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>2.6</version>
</dependency>




<!-- https://mvnrepository.com/artifact/org.apache.httpcomponents/httpmime -->
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpmime</artifactId>
    <version>4.5.10</version>
</dependency>
 
       <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-report-plugin -->
<dependency>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-report-plugin</artifactId>
    <version>3.0.0-M3</version>
</dependency>
       
    </dependencies>
 
    
 
 
    <reporting>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-report-plugin</artifactId>
                <version>3.0.0-M3</version>
            </plugin>
            <plugin>
                <groupId>CalcTest</groupId>
                <artifactId>xray-maven-plugin</artifactId>
                <version>1.0.0</version>
            </plugin>
        </plugins>
    </reporting>
  
 
</project>
```
..........................................................................
testng.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite">


  <test name="Test">
    <classes>
      <!--  class name="CalcTest.CalcTest"/-->
   
      <class name="CalcTest.TMTest2"/>
     
    </classes>
  </test> <!-- Test -->
</suite> <!-- Suite -->
```
..............................................................
output sample is coming like:::

```
<test-method name="CanAddNumbersFromGivenData" signature="CanAddNumbersFromGivenData(int, int, int)[pri:0, instance:CalcTest.TMTest2@56ac3a89]" status="PASS" duration-ms="2" urso="CALC-1" finished-at="2019-11-13T07:03:13Z" started-at="2019-11-13T07:03:13Z" data-provider="ValidDataProvider" requirement="xpto">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
```
No attribute is showing

_Originally posted by @ssoban in https://github.com/cbeust/testng/issues/1673#issuecomment-553291899_

**Comment by krmahadevan** [comment]
I am not able to reproduce the issue. Here's the `testing-results.xml` that got generated using the attached project.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="8" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="74" started-at="2019-11-17T21:13:34 IST" finished-at="2019-11-17T21:13:34 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="74" started-at="2019-11-17T21:13:34 IST" finished-at="2019-11-17T21:13:34 IST">
      <class name="com.rationaleemotions.TMTest2">
        <test-method status="PASS" signature="CanAddNumbers()[pri:0, instance:com.rationaleemotions.TMTest2@735b478]" name="CanAddNumbers" duration-ms="8" started-at="2019-11-17T21:13:34 IST" finished-at="2019-11-17T21:13:34 IST">
          <reporter-output>
          </reporter-output>
          <attributes>
            <attribute name="test">
              <![CDATA[CALC-2]]>
            </attribute> <!-- test -->
            <attribute name="requirement">
              <![CDATA[CALC-1234]]>
            </attribute> <!-- requirement -->
            <attribute name="labels">
              <![CDATA[core addition]]>
            </attribute> <!-- labels -->
          </attributes>
        </test-method> <!-- CanAddNumbers -->
        <test-method status="PASS" signature="CanAddNumbersFromGivenData(int, int, int)[pri:0, instance:com.rationaleemotions.TMTest2@735b478]" name="CanAddNumbersFromGivenData" duration-ms="0" started-at="2019-11-17T21:13:34 IST" data-provider="ValidDataProvider" finished-at="2019-11-17T21:13:34 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
          <attributes>
            <attribute name="test">
              <![CDATA[CALC-1]]>
            </attribute> <!-- test -->
            <attribute name="requirement">
              <![CDATA[CALC-1234]]>
            </attribute> <!-- requirement -->
            <attribute name="labels">
              <![CDATA[]]>
            </attribute> <!-- labels -->
          </attributes>
        </test-method> <!-- CanAddNumbersFromGivenData -->
        <test-method status="FAIL" signature="CanAddNumbersFromGivenData(int, int, int)[pri:0, instance:com.rationaleemotions.TMTest2@735b478]" name="CanAddNumbersFromGivenData" duration-ms="1" started-at="2019-11-17T21:13:34 IST" data-provider="ValidDataProvider" finished-at="2019-11-17T21:13:34 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[4]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<5> but was:<4>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<5> but was:<4>
at org.testng.AssertJUnit.fail(AssertJUnit.java:47)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:330)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:66)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:213)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:218)
at com.rationaleemotions.TMTest2.CanAddNumbersFromGivenData(TMTest2.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
          <attributes>
            <attribute name="test">
              <![CDATA[CALC-1]]>
            </attribute> <!-- test -->
            <attribute name="requirement">
              <![CDATA[CALC-1234]]>
            </attribute> <!-- requirement -->
            <attribute name="labels">
              <![CDATA[]]>
            </attribute> <!-- labels -->
          </attributes>
        </test-method> <!-- CanAddNumbersFromGivenData -->
        <test-method status="PASS" signature="CanAddNumbersFromGivenData(int, int, int)[pri:0, instance:com.rationaleemotions.TMTest2@735b478]" name="CanAddNumbersFromGivenData" duration-ms="1" started-at="2019-11-17T21:13:34 IST" data-provider="ValidDataProvider" finished-at="2019-11-17T21:13:34 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[-1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
          <attributes>
            <attribute name="test">
              <![CDATA[CALC-1]]>
            </attribute> <!-- test -->
            <attribute name="requirement">
              <![CDATA[CALC-1234]]>
            </attribute> <!-- requirement -->
            <attribute name="labels">
              <![CDATA[]]>
            </attribute> <!-- labels -->
          </attributes>
        </test-method> <!-- CanAddNumbersFromGivenData -->
        <test-method status="PASS" signature="CanDivide()[pri:0, instance:com.rationaleemotions.TMTest2@735b478]" name="CanDivide" duration-ms="0" started-at="2019-11-17T21:13:34 IST" finished-at="2019-11-17T21:13:34 IST">
          <reporter-output>
          </reporter-output>
          <attributes>
            <attribute name="test">
              <![CDATA[]]>
            </attribute> <!-- test -->
            <attribute name="requirement">
              <![CDATA[CALC-1237]]>
            </attribute> <!-- requirement -->
            <attribute name="labels">
              <![CDATA[]]>
            </attribute> <!-- labels -->
          </attributes>
        </test-method> <!-- CanDivide -->
        <test-method status="FAIL" signature="CanDoStuff()[pri:0, instance:com.rationaleemotions.TMTest2@735b478]" name="CanDoStuff" duration-ms="2" started-at="2019-11-17T21:13:34 IST" finished-at="2019-11-17T21:13:34 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertNotEquals(Assert.java:1401)
at org.testng.Assert.assertNotEquals(Assert.java:1406)
at com.rationaleemotions.TMTest2.CanDoStuff(TMTest2.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
          <attributes>
            <attribute name="test">
              <![CDATA[]]>
            </attribute> <!-- test -->
            <attribute name="requirement">
              <![CDATA[CALC-1237]]>
            </attribute> <!-- requirement -->
            <attribute name="labels">
              <![CDATA[]]>
            </attribute> <!-- labels -->
          </attributes>
        </test-method> <!-- CanDoStuff -->
        <test-method status="PASS" signature="CanMultiplyX()[pri:0, instance:com.rationaleemotions.TMTest2@735b478]" name="CanMultiplyX" duration-ms="0" started-at="2019-11-17T21:13:34 IST" finished-at="2019-11-17T21:13:34 IST">
          <reporter-output>
          </reporter-output>
          <attributes>
            <attribute name="test">
              <![CDATA[]]>
            </attribute> <!-- test -->
            <attribute name="requirement">
              <![CDATA[CALC-1236]]>
            </attribute> <!-- requirement -->
            <attribute name="labels">
              <![CDATA[]]>
            </attribute> <!-- labels -->
          </attributes>
        </test-method> <!-- CanMultiplyX -->
        <test-method status="PASS" signature="CanSubtract()[pri:0, instance:com.rationaleemotions.TMTest2@735b478]" name="CanSubtract" duration-ms="0" started-at="2019-11-17T21:13:34 IST" finished-at="2019-11-17T21:13:34 IST">
          <reporter-output>
          </reporter-output>
          <attributes>
            <attribute name="test">
              <![CDATA[]]>
            </attribute> <!-- test -->
            <attribute name="requirement">
              <![CDATA[CALC-1235]]>
            </attribute> <!-- requirement -->
            <attribute name="labels">
              <![CDATA[core]]>
            </attribute> <!-- labels -->
          </attributes>
        </test-method> <!-- CanSubtract -->
      </class> <!-- com.rationaleemotions.TMTest2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
```

[xray-demo.zip](https://github.com/cbeust/testng/files/3855755/xray-demo.zip)

**Comment by gkrananth** [comment]
what command you are using for run the test?

I have used verify -Dtest=com.rationaleemotions.TMTest2 not attribute is coming. Same reult like @Yamuna-Rani

**Comment by krmahadevan** [comment]
@gkrananth - It works fine for `mvn clean test`

For it to work for `mvn clean test -Dtest=com.rationaleemotions.TMTest2` you need to ensure that the listener that is adding the attributes (which is `com.rationaleemotions.XrayListener` in this case) is getting added maybe via a service loader (so that it gets invoked automatically all the time).

Refer to [my blog](https://rationaleemotions.com/testng_listeners/) to learn more on this.

**Comment by Mmallineni** [comment]
@krmahadevan I'm using the default listeners and still facing the issue. looks like its testng issue

**Comment by krmahadevan** [comment]
@Mmallineni - In that case, please help share a reproducible sample project which uses TestNG `7.7.0` (latest released version as of today)
