### ISSUE TITLE
NPE Using groups and @Before/@AfterMethod with alwaysRun and dependsOnMethods

### ISSUE THREAD

**Issue by iagotomas** [cbeust/testng#2195]
### TestNG Version
6.14.3 - 7.0.1-SNAPSHOT

### Expected behavior

Rise a friendly message instead of NPE

### Actual behavior

Using groups if a Before or After annotated method from a parent class is using alwaysRun and depends on a method which is not in the group nor annotated with alwaysRun an NPE is risen

```
Exception in thread "main" java.lang.NullPointerException
        at org.testng.internal.MethodHelper.findDependedUponMethods(MethodHelper.java:116)
        at org.testng.internal.MethodHelper.topologicalSort(MethodHelper.java:281)
        at org.testng.internal.MethodHelper.sortMethods(MethodHelper.java:381)
        at org.testng.internal.MethodHelper.collectAndOrderMethods(MethodHelper.java:71)
        at org.testng.internal.TestNGMethodFinder.findConfiguration(TestNGMethodFinder.java:200)
        at org.testng.internal.TestNGMethodFinder.getBeforeGroupsConfigurationMethods(TestNGMethodFinder.java:99)
        at org.testng.TestClass.initMethods(TestClass.java:159)
        at org.testng.TestClass.init(TestClass.java:75)
        at org.testng.TestClass.<init>(TestClass.java:39)
        at org.testng.TestRunner.initMethods(TestRunner.java:463)
        at org.testng.TestRunner.init(TestRunner.java:342)
        at org.testng.TestRunner.init(TestRunner.java:295)
        at org.testng.TestRunner.<init>(TestRunner.java:181)
        at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:618)
        at org.testng.SuiteRunner.init(SuiteRunner.java:196)
        at org.testng.SuiteRunner.<init>(SuiteRunner.java:127)
        at org.testng.TestNG.createSuiteRunner(TestNG.java:1265)
        at org.testng.TestNG.createSuiteRunners(TestNG.java:1244)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1093)
        at org.testng.TestNG.runSuites(TestNG.java:1032)
        at org.testng.TestNG.run(TestNG.java:1000)
        at org.testng.TestNG.privateMain(TestNG.java:1326)
        at org.testng.TestNG.main(TestNG.java:1294)

```

### Is the issue reproductible on runner?

- [X] Shell
- [X] Maven
- [X] Gradle
- [X] Ant
- [X] Eclipse
- [X] IntelliJ
- [X] NetBeans

### Test case sample

```java
@Test(groups={"testgroup"})
class Test1 extends BaseClass {

    public Test1() {
    }
}

class BaseClass {
    @BeforeMethod
    public void before(){}
    @BeforeMethod(alwaysRun = true, dependsOnMethods = "before")
    public void beforeAlways(){}

   @Test
   public void test()
   
    @AfterMethod
    public void after(){}
    @AfterMethod(alwaysRun = true, dependsOnMethods = "after")
    public void after(){}
}
```

Test suite xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite parallel="none" name="Custom suite">
    <test name="TestNPE" verbose="10">
        <groups>
            <run>
                <include name="testgroup"/>
            </run>
        </groups>
        <classes>
            <class name="TestClass"/>
        </classes>
    </test> <!-- TestNPE -->
</suite> <!-- Custom suite -->
````

**Comment by iagotomas** [comment]
I could come up with a patch which rises a nicer exception: 
```
org.testng.TestNGException: 
com.tomas.testngpoc.AbstractNPEClass.tearDownAlways() is depending on method public void com.tomas.testngpoc.AbstractNPEClass.tearDown(), which is not annotated with @Test or not included.
	at org.testng.internal.MethodHelper.findDependedUponMethods(MethodHelper.java:134)
	at org.testng.internal.MethodHelper.topologicalSort(MethodHelper.java:282)
	at org.testng.internal.MethodHelper.sortMethods(MethodHelper.java:382)
	at org.testng.internal.MethodHelper.collectAndOrderMethods(MethodHelper.java:71)
	at org.testng.internal.TestNGMethodFinder.findConfiguration(TestNGMethodFinder.java:200)
	at org.testng.internal.TestNGMethodFinder.getBeforeGroupsConfigurationMethods(TestNGMethodFinder.java:99)
	at org.testng.TestClass.initMethods(TestClass.java:159)
	at org.testng.TestClass.init(TestClass.java:75)
	at org.testng.TestClass.<init>(TestClass.java:39)
	at org.testng.TestRunner.initMethods(TestRunner.java:457)
	at org.testng.TestRunner.init(TestRunner.java:336)
	at org.testng.TestRunner.init(TestRunner.java:289)
	at org.testng.TestRunner.<init>(TestRunner.java:178)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:613)
	at org.testng.SuiteRunner.init(SuiteRunner.java:178)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:112)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1275)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1251)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1100)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

```
--- src/main/java/org/testng/internal/MethodHelper.java	
+++ src/main/java/org/testng/internal/MethodHelper.java
@@ -113,7 +113,8 @@
           int lastIndex = regexp.lastIndexOf('.');
           String newMethodName;
           if (lastIndex != -1) {
-            newMethodName = m.getTestClass().getRealClass().getName() + regexp.substring(lastIndex);
+            String clazzName = (m.getTestClass() != null ? m.getTestClass().getRealClass() : m.getRealClass()).getName();
+            newMethodName = clazzName + regexp.substring(lastIndex);
             results = matchMethod(methods, newMethodName);
             foundAtLeastAMethod = results.foundAtLeastAMethod;
             vResult.addAll(results.matchedMethods);
```

**Comment by krmahadevan** [comment]
@iagotomas - Can you please raise a Pull request for this, since you seem to have identified the root cause and also are aware of the solution ?

You could include your same sample as a unit test for this

**Comment by iagotomas** [comment]
Hi @krmahadevan created PR https://github.com/cbeust/testng/pull/2196 but found some issues with file encodings/endings and diff of org.testng.internal.MethodHelper class looks like if everything is modified. Tried several encodings and line endings but could not find the appropriate. 
If you could tell me the expected format will happily reformat appropriately.

**Comment by krmahadevan** [comment]
@iagotomas - We don't have a formal formatter per se for the TestNG project. Can you please try using https://github.com/google/google-java-format

Also try to see if you can refrain from either doing a format of the full class (or disable your IDE from applying auto format on file changes) and just apply the one line fix for `MethodHelper` and see if that solves the problem for you ?
