### ISSUE TITLE
Exception is not printed out if we use AbstractTestNGSpringContextTests and timeout annotation

### ISSUE THREAD

**Issue by yuandanxu** [cbeust/testng#2252]
### TestNG Version
> Note: only the latest version is supported
7.1.0

### Expected behavior
We extend AbstractTestNGSpringContextTests and use timeout annotation together, but if I thrown an exception in test method, the exception information will be not printed out. 

This is the very simple test class to reproduce this issue:

```java
public class TestException extends AbstractTestNGSpringContextTests {

    @Test(timeOut = 40000)
    public void test() throws Exception {
        throw new Exception("Test Exception");
    }
}
```

If I set this timeout annotation, after execution this case, I only know the test case fails, but there's no error message printed out in console. This is very inconvenient. If I want to set timeout, I can't get the exception information if there's any error happens. 

But If I remove timeout, the exception will be printed out like below.  

```
java.lang.Exception: Test Exception

	at com.dell.e2e.cases.TestException.test(TestException.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:240)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:181)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:252)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:593)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
```

### Actual behavior
Exception not printed out.

### Is the issue reproductible on runner?

- [ ] Shell
- [ x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ x] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

```java
public class TestException extends AbstractTestNGSpringContextTests {

    @Test(timeOut = 40000)
    public void test() throws Exception {
        throw new Exception("Test Exception");
    }
}
```

**Comment by krmahadevan** [comment]
@yuandanxu - You would need to tell us what version of TestNG is being used here. The latest released version is `7.1.0`. Is the problem persisting in this version ? 

If the problem persists, please help include details of all versions (It would be even better, if you can create a sample maven/gradle project that we can use to reproduce the problem along with the dependencies).

**Comment by krmahadevan** [comment]
@yuandanxu - Please see if your issue is related to https://github.com/cbeust/testng/issues/2251

I have raised a PR for fixing https://github.com/cbeust/testng/issues/2251

**Comment by yuandanxu** [comment]
@krmahadevan yes, my testng is 7.1.0. Yes, it persists. It is super easy to reproduce, here's the pom file and sample class.  If you remove timeout, the exception will be printed out. I didn't see explicitly NPE error though. 
1. Sample Class:
public class TestException extends AbstractTestNGSpringContextTests {

    @Test(timeOut = 40000)
    public void test() throws Exception {
        throw new Exception("Test Exception");
    }
}
2. pom.xml:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>TestNGPOC</artifactId>
  <version>1.0-SNAPSHOT</version>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.2.4.RELEASE</version>
    <relativePath/> 
  </parent>
<dependencies>
  <dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.1.0</version>
    <scope>test</scope>
  </dependency>
  <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
  </dependency>
  <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-test</artifactId>
    <scope>test</scope>
  </dependency>

</dependencies>
</project>

**Comment by krmahadevan** [comment]
Fixed as part of fixing https://github.com/cbeust/testng/issues/2251

**Comment by yuandanxu** [comment]
@krmahadevan thanks a lot for your quick fix. When we will get testng next release? Thanks.

**Comment by krmahadevan** [comment]
@yuandanxu - I don't have that information right now with me.
