### ISSUE TITLE
Eclipse, Exception in thread "main" org.testng.TestNGException, Cannot load class from file

### ISSUE THREAD

**Issue by tatery** [cbeust/testng#2283]
### TestNG Version
7.1.0

### Expected behavior
Tests can be run in eclipse.

### Actual behavior
When trying to run tests in Eclipse the following exception occurs:

`
[RemoteTestNG] detected TestNG version 7.0.1
Exception in thread "main" org.testng.TestNGException: 
Cannot load class from file: 
	at org.testng.internal.ClassHelper.fileToClass(ClassHelper.java:340)
	at org.testng.TestNG.configure(TestNG.java:1422)
	at org.testng.remote.AbstractRemoteTestNG.configure(AbstractRemoteTestNG.java:75)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:235)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
`

Eclipse version: 2020-03 (14.15.0)
TestNG	7.1.1.202003100345
TestNG P2 Feature	7.2.0.r202003151902

TestNG in POM: 7.1.0

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [X] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
Run any test in latest Eclipse with latest TestNG, for example:
```java
public class TestClass {
	@Test
	public void doNothingTest() {
		//do nothing
	}
}
```

**Comment by krmahadevan** [comment]
@tatery - Please log TestNG eclipse plugin issues in https://github.com/cbeust/testng-eclipse
