### ISSUE TITLE
[RemoteTestNG] detected TestNG version 7.0.1 Exception in thread "main" java.lang.NoClassDefFoundError: com/google/inject/Stage 	at org.testng.internal.Configuration.<init>(Configuration.java:33) 	at org.testng.TestNG.init(TestNG.java:216) 	at org.testng.TestNG.<init>(TestNG.java:200) 	at org.testng.remote.AbstractRemoteTestNG.<init>(AbstractRemoteTestNG.java:17) 	at org.testng.remote.support.RemoteTestNG6_12.<init>(RemoteTestNG6_12.java:18) 	at org.testng.remote.support.RemoteTestNGFactory6_12.createRemoteTestNG(RemoteTestNGFactory6_12.java:16) 	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:67) Caused by: java.lang.ClassNotFoundException: com.google.inject.Stage 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602) 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) 	... 7 more

### ISSUE THREAD

**Issue by Archana4686** [cbeust/testng#2297]
### TestNG Version
> Note: only the latest version is supported

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by missedone** [comment]
duplicates with #2223

**Comment by krmahadevan** [comment]
@Archana4686 - Please refer to the comments in #2223 to understand how to get past this problem. This needs TestNG `v7.2.0` to be released.
