### ISSUE TITLE
Test fails when running with <package> but passes with <className>in testng.xml

### ISSUE THREAD

**Issue by NareshJBhadrecha** [cbeust/testng#2299]
### TestNG Version
> Note: only the latest version is supported
7.1.0
### Expected behavior

Test should pass

### Actual behavior

Test fails when running with package but passes with className

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample

structure -- > **src/main/java**/restUtil

```java
public abstract class RestUtility {
	public void setEndPoint(String endPoint) {
		RestAssured.baseURI = endPoint;
		RestAssured.useRelaxedHTTPSValidation();
	}
        public void basicAuthentication(String userName, String password) {
		RestAssured.authentication = RestAssured.basic(userName, password);
	}
        public void doGET(String path) {
		try{
			response = given().when().get(path);
		} catch (Exception e) {
			throw new RuntimeException("Error Occurred: \n"+e.getMessage());
		}
	}
}
```

structure -- > **src/main/test**/restTest 

```java
public class AuthenticationTest extends RestUtility { 
        public static final String baseURL = "http://restapi.demoqa.com";
       @BeforeMethod(alwaysRun = true)
	public void setUp() {
                setEndPoint(baseURL);
		basicAuthentication("ToolsQA", "TestPassword");
        }

      @Test(groups = {"AuthenticationBasic", "Regression"})
	public void authenticationBasic() {
                  doGET("/authentication/CheckForAuthentication");
        }
}
```
______________________________________________________________________________________________

testng.xml

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="test" thread-count="1" parallel="tests">
    <test name="test">
        <groups>
            <run>
                <include name="AuthenticationBasic"/>
            </run>
        </groups>
<!--        <packages>-->
<!--            <package name="restTest"></package>-->
<!--        </packages>-->
        <classes>
            <class name="restTest.AuthenticationTest"></class>
        </classes>
    </test>
</suite>
```

**Comment by NareshJBhadrecha** [comment]
<packages>
            <package name="restTest*"></package>
        </packages>

**Comment by NareshJBhadrecha** [comment]
Connection timed out: connect

	at restAssuredUtility.RestUtility.doGET(RestUtility.java:52)
	at springBootTest.AuthenticationTest.authenticationBasic(AuthenticationTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)

**Comment by krmahadevan** [comment]
There is nothing wrong with TestNG. You are experiencing a connection time out in your test code which you would need to debug and fix.

Closing this issue with resolution as **Question answered**

Please feel free to comment with a simple standalone example (that does not use anything else outside of testng) to demonstrate the problem (if you are still experiencing it)

**Comment by NareshJBhadrecha** [comment]
> There is nothing wrong with TestNG. You are experiencing a connection time out in your test code which you would need to debug and fix.
> 
> Closing this issue with resolution as **Question answered**
> 
> Please feel free to comment with a simple standalone example (that does not use anything else outside of testng) to demonstrate the problem (if you are still experiencing it)

Why would the script pass with <class> and not <package>, all I see is that there is a loss of reference (RestAssured.baseURI = endPoint) to be used in the doGet method above, do investigate whenever you get time
