### ISSUE TITLE
Using softAssert and "hard" Asserts together, softAsserts are swallowed by the "hard" Asserts

### ISSUE THREAD

**Issue by wulfihm** [cbeust/testng#2314]
### TestNG Version
7.1.0, latest from the maven repo https://mvnrepository.com/artifact/org.testng/testng

### Issue

This issue is (probably) not one with testng per se but rather an architectural problem I have using testng and softAssertions. I found a solution and my question is if there is a better solution to this, am I missing something? Is there a reason why I should not use my solution to this problem?

Essentially what I am doing is this:
```
softAssert.fail("SoftAssert fail");
assert.fail("assert fail");
softAssert.assertAll();
```
What happens is that `assert.fail("assert fail");` obviously fails and the exception is shown as `java.lang.AssertionError: assert fail` but the softAssertion is never evaluated because of the Exception. The softAssertions will never be shown until the normal assert does not fail.

So what I ended up doing is this:
Simply extend SoftAssert so I can use the "doAssert" method, because it is protected in the original class.
```
public class MySoftAssert extends SoftAssert {
    public MySoftAssert() {
        super();
    }

    @Override
    protected void doAssert(IAssert<?> a) {
        super.doAssert(a);
    }
}
```
Then define a HardAssert class, which also passes all asserts to 'the' softAssert object used by the tests to do assertions, and when the hardAssert fails it automatically evaluates all the softAsserts.
```
public class MyHardAssert extends MySoftAssert {
    private final MySoftAssert softAssert;

    public MyHardAssert(MySoftAssert softAssert){
        this.softAssert = softAssert;
    }

    @Override
    public void onAssertFailure(IAssert<?> assertCommand, AssertionError ex) {
        super.onAssertFailure(assertCommand, ex);
        softAssert.assertAll();
    }

    @Override
    protected void doAssert(IAssert<?> a) {
        softAssert.doAssert(a);
        super.doAssert(a);
    }
}
```
Now I can do this:
```
softAssert.fail("softAssert fail");
hardAssert.fail("hardAssert fail");
```
and it will show both asserts as being failed.
```
java.lang.AssertionError: The following asserts failed:
	softAssert fail
	hardAssert fail
```

### Is the issue reproductible on runner?
- [X] IntelliJ

**Comment by krmahadevan** [comment]
@wulfihm - I am not able to understand why do you want to complicate this to this extent?
You want your Hard Asserts to not abort the evaluation of the Soft asserts. If that's the case, then why not just stick to using only Soft Asserts. Why bring in Hard asserts into the equation when you would like to ensure that the hard asserts are not hard asserts ?

Hard asserts by definition are meant to abandon execution right at the point where it fails.
Soft asserts by definition are meant to abandon execution at the end or at the place where `softAssert.assertAll()` is invoked.

If all you want is that you need to be able to do `softAssert.assertAll()` irrespective of whether or not there was a hard assertion failure, then you should be able to just use the `IHookable` approach, and work with it [ and have all your test classes extend from this base class ]

**Comment by wulfihm** [comment]
> Hard asserts by definition are meant to abandon execution right at the point where it fails.
> Soft asserts by definition are meant to abandon execution at the end or at the place where `softAssert.assertAll()` is invoked.
Exactly why I am using soft asserts and hard asserts. There are certain things I want to assert where I want it to stop the test simply because they would "break" the test. And then there are other things where it doesn't matter for the execution of the test if they are wrong, because they would not break the test and I just want to to know at the end if they were wrong.

> If all you want is that you need to be able to do softAssert.assertAll() irrespective of whether or not there was a hard assertion failure, then you should be able to just use the IHookable approach, and work with it [ and have all your test classes extend from this base class ]

Well that does not work. The IHookable approach is not executed when the test fails because of a hard assert that stops the execution. That is the whole point.

**Comment by krmahadevan** [comment]
> That is the whole point why I implemented the approach to evaluate all soft asserts if a hard assert fails.

You are diluting the concept of Hard assert, if you want all the test to continue to evaluate all the soft asserts even after a hard assert has failed.

If you build something like this, this would ensure that the soft assertion would get called if and only if all hard asserts pass. If the hard assert fails, even then the soft assert would get called.

```java
import org.testng.IHookCallBack;
import org.testng.IHookable;
import org.testng.ITestResult;
import org.testng.Reporter;
import org.testng.asserts.SoftAssert;

public class BaseTestCase implements IHookable {

  private static final String KEY = "softassert";

  @Override
  public void run(IHookCallBack callBack, ITestResult testResult) {
    SoftAssert softAssert = new SoftAssert();
    testResult.setAttribute(KEY, softAssert);
    callBack.runTestMethod(testResult);
    try {
      softAssert.assertAll();
    } catch (AssertionError e) {
      throw new AssertionError(e.getMessage(), testResult.getThrowable());
    }
  }

  protected final SoftAssert getSoftAssertForCurrentTest() {
    Object object = Reporter.getCurrentTestResult().getAttribute(KEY);
    if (object == null) {
      throw new RuntimeException("no soft assert object found");
    }
    if (!(object instanceof SoftAssert)) {
      throw new IllegalStateException("Not a soft assertion object");
    }
    return (SoftAssert) object;

  }
}
```

Test class looks like below

```java
import org.testng.Assert;
import org.testng.annotations.Test;

public class SimpleTestCase extends BaseTestCase {

  @Test
  public void testMethod() {
    getSoftAssertForCurrentTest().assertTrue(false, "Soft assert failed");
    Assert.assertFalse(true, "Hard assert failed");
    getSoftAssertForCurrentTest().assertTrue(true);
  }

}

```

**Comment by wulfihm** [comment]
> If you build something like this, this would ensure that the soft assertion would get called if and only if all hard asserts pass.

But that is how soft asserts currently work. If I use softasserts and normal asserts, the softasserts are only evaluated if the asserts pass. That is the whole issue I explained above in the first parapgraph.

Not sure what your code is supposed to show there. It does something completely different to what I did and what my issue exactly is.

**Comment by krmahadevan** [comment]
@wulfihm -

> If I use softasserts and normal asserts, the softasserts are only evaluated if the asserts pass.

This is *NOT* true. Please go back to my implementation and pay closer 

```java
    callBack.runTestMethod(testResult);
    try {
      softAssert.assertAll();
    } catch (AssertionError e) {
      throw new AssertionError(e.getMessage(), testResult.getThrowable());
    }
```
The above implementation would invoke `softAssert.assertAll()` irrespective of whether `Assert.xxx` causes a pass (or) a fail.

 Since we have reached a conclusion that what I proposed is not something that you want, but you want to mix both Soft and Hard asserts together in a manner that I fail to understand, I will step aside and let someone else chime in.

The fact that you are doing something like this

```java
protected void doAssert(IAssert<?> a) {
        softAssert.doAssert(a);
        super.doAssert(a);
    }
```

in your customised MyHardAssert is already caused the hard assert to lose its value. Because this is just soft assertion.

You can test it out by flipping the order

```
hardAssert.fail("hardAssert fail");
softAssert.fail("softAssert fail");
```

If your code still reaches `softAssert.fail()` then its just soft assertion that you are doing.

@juherr - Your thoughts ?

**Comment by wulfihm** [comment]
It does not reach the softAssert as I wrote above (in my edit you probably did not see while writing this post).

**Comment by wulfihm** [comment]
Sorry, some confusing there on my part.

> The above implementation would invoke softAssert.assertAll() irrespective of whether Assert.xxx causes a pass (or) a fail.

Yes that is correct. However, while doing so they swallow "normal" asserts.

I can run your test above and it shows this:
```java
java.lang.AssertionError: The following asserts failed:
	Soft assert failed expected [true] but found [false]
Expected :true
Actual   :false
<Click to see difference>


	at playground.BaseTestCase.run(BaseTestCase.java:21)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:252)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:593)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:240)
	at playground.BaseTestCase.run(BaseTestCase.java:17)
	... 23 more
Caused by: java.lang.AssertionError: Hard assert failed expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:97)
	at org.testng.Assert.failNotEquals(Assert.java:969)
	at org.testng.Assert.assertFalse(Assert.java:65)
	at playground.SimpleTestCase.testMethod(SimpleTestCase.java:11)
	... 30 more
```
It only shows the soft assert, not the hard assert, which actually causes the test to fail-
What happens is, that the hard assert fails, which causes the "run" method to be invoked. Before the ex exception from the hard assert is actually thrown the soft asserts are evaluated, which then causes the exceptions of the soft asserts to be thrown, before the hard assert exceptions can be thrown at all.

**Comment by juherr** [comment]
It looks like a corner case of assertion use cases and built-in assertions are just provided for common usages.
Usually, we recommend AssertJ for more complex use cases but I don't know if it will help here.

**Comment by kool79** [comment]
@wulfihm 

> Now I can do this:
>  softAssert = new MySoftAssert();
>  hardAssert = new MyHardAssert(softAssert);
>  softAssert.fail("softAssert fail");
>  hardAssert.fail("hardAssert fail");

hardAssert are good because we dont need to create any objects for them. They are pure static methods. But you propose to create +1 instance and add this line to EVERY method of every developer.. 

In any case this will NOT help you. After you'll get this in testng you'll find that ANY exception (in you code or in your libraries, like selenium ElementNotFoundException) will not collect your soft-asserts also )). Because hard assert in fact is just a kind of exception with formatted message. You'll not be able to refactor all exceptions around the world to accept softAssert like you did for `new MyHardAssert(softAssert);`

**Comment by wulfihm** [comment]
Of course I won't be able to refactor all exceptions. But at least this gives me the possibility to use softAsserts together with hardAsserts without impacting the functionality of the softasserts (i.e. discarding the softasserts results because I did a hard assert). In fact the code you quoted is not my proposition for the change, it just highlights what I am intending to do. An actual implementation could look way more smoother and lightweight, directly incorporated into the assert methods with a boolean (true=doHardAssert). What I did was with the code base provided without having to change too much of the underlying classes. I added 30 lines of code vs. changing about 600.
So far I am using the code I posted without any problems and it works very well for its intended purpose. So I am very pleased with the result. This is unrelated to if this change is considered as a feature requests for TestNG. If it will be I am glad that I could perhaps made someone's days a little easier by providing a functionaly to easily hardAssert with softAsserts.

**Comment by wulfihm** [comment]
If you are interested @kool79 
This is how I would imagine the feature would look like.
https://gist.github.com/wulfihm/47de0ddaaf2d397da9f2e6615cf8719e

This wouldn't even introduce breaking code.

**Comment by Proryanator** [comment]
@hwulfmeyer at my organisation we noticed/wanted something similar, we might have soft assertions for content checks (like missing periods) and have hard assertions that are primarily used to stop a test when it's obvious that it can't proceed. An example of this would be doing a hard assert for whether the page has loaded properly. Instead of getting a NoSuchElementException since the next element isn't there, we'd get the assertion error.

I can share our solution here if you're still looking to see what you can do, or even I could look to see if this could be a feature added to TestNG for this, but essentially it'd work like this:

-add an overloaded assertAll(Throwable) method to accept a throwable (which you'd pass in from the hard assert that failed)
-add a method to SoftAssert to tell you if any soft assertion failures were caught (hasSoftAssertErrors())
-implement 'IHookable' in your base test, and within the run() method catch when a hard assert is thrown
-if there are any soft assert failures, you then pass in the hard assert failure to the overloaded assertAll(Throwable) method,
and then attach the hard assert along with the other soft asserts.


This ensures that any soft assertion failures are still caught and are not suppressed by hard asserts. We found it to be a relatively robust solution.

You may not want to stop your test for content failures, but you may way to stop if when some API setup call fails for example mid-test. This allows just that :D

**Comment by hwulfmeyer** [comment]
I simply extended the softassert class with hardasserts. Its the easiest and cleanest way possible.
https://gist.github.com/hwulfmeyer/fba24d20a8b7b9b230c6147ace0df39e

That way I can e.g. call softAssert.assertEquals() for a soft assert and then softAssert.hardAssertEquals() if I need a hard assert.
My Base class contains an IHookAble which I simply call for the testResult and see if it successfully went through in case there was no failed hardAssert.

Example Code:
```
public abstract class BaseTest implements IHookable {
    public MySoftAssert softAssert;

    @Override
    public void run(IHookCallBack iHookCallBack, ITestResult iTestResult) {
        iHookCallBack.runTestMethod(iTestResult);
        if(iTestResult.getThrowable() == null){
            softAssert.assertAll("Test successful, evaluating Soft Asserts:");
        }
    }
}
```

**Comment by Proryanator** [comment]
> I simply extended the softassert class with hardasserts. Its the easiest and cleanest way possible, and foremost it works. :D
> https://gist.github.com/hwulfmeyer/fba24d20a8b7b9b230c6147ace0df39e
> I had to completely copy the softAssert class because It couldn't simply be extended. Forgot why. I think some functions were private and couldn't be overidden or something.
> 
> That way I can e.g. call softAssert.assertEquals() for a soft assert and then softAssert.hardAssertEquals() if I need a hard assert.
> My Base class contains an IHookAble which I simply call for the testResult and see if it successfully went through in case there was no failed hardAssert.
> 
> Example Code:
> 
> ```
> public abstract class BaseTest implements IHookable {
>     public MySoftAssert softAssert;
> 
>     @Override
>     public void run(IHookCallBack iHookCallBack, ITestResult iTestResult) {
>         iHookCallBack.runTestMethod(iTestResult);
>         if(iTestResult.getThrowable() == null){
>             softAssert.assertAll("Test successful, evaluating Soft Asserts:");
>         }
>     }
> }
> ```
> 
> The hardasserts are directly evaluated in the SoftAssert Class.
> 
> ```
>     private void doAssert(IAssert<?> a, boolean doHardAssert) {
>         this.onBeforeAssert(a);
> 
>         try {
>             a.doAssert();
>             this.onAssertSuccess(a);
>         } catch (AssertionError var6) {
>             this.onAssertFailure(a, var6);
>             this.m_errors.put(var6, a);
>             if(doHardAssert) this.assertAll("Hard Assert failed, also showing all soft asserts that failed before:");
>         } finally {
>             this.onAfterAssert(a);
>         }
>     }
> ```
> 
> So no magic code, just simple lines that do what they need to do.

Your solution is a bit simpler but since you're implementing hard assertions in your SoftAssert class, you'd have to create hard assert methods in SoftAssert for all the possible hard assert 'assertEquals' within your SoftAssert class which does add some overhead and code duplication (for booleans, doubles, floats, ints, etc).

Using our mentioned method all you need to account for is at the end, dealing with if you have any soft asserts after a hard assert is called.
