### ISSUE TITLE
expectedExceptions not working as expected after upgrading to testng 7.1.0

### ISSUE THREAD

**Issue by hnestorova** [cbeust/testng#2322]
### TestNG Version
7.1.0

### Expected behavior
Using testng Bundle-Version: 7.0.0.beta5 we have the test marked as PASSED and the exception logged as:

```
Exception java.lang.UnsatisfiedLinkError
Message: com.bravogroup.math.robust.Robeth.rpardf0([FIIIIFF[I[I[I)V

Stacktrace:

at com.bravogroup.math.robust.Robeth.rpardf0(Native Method)
at com.bravogroup.math.robust.Robeth.dfrpar(Robeth.java:122)
at com.bravogroup.math.robust.Robeth.dfrpar(Robeth.java:109)
at com.bravogroup.math.robust.Robeth.myhbhe(Robeth.java:73)
at com.bravogroup.math.robust.Robeth.myhbhe(Robeth.java:69)
at com.bravogroup.math.robust.Robeth.myhbhe(Robeth.java:64)
at com.bravogroup.cognity.calc.fa.TSFMUtils.calcRobust(TSFMUtils.java:136)
at com.bravogroup.cognity.calc.fa.TSFMUtils.calcCoefficients(TSFMUtils.java:125)
at com.bravogroup.cognity.calc.fa.TestTSFMUtils.testFailingCalcCoefficients(TestTSFMUtils.java:197)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:51)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:41)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:306)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:278)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:590)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
```

### Actual behavior
Using testng 7.1.0 downloaded from https://mvnrepository.com/artifact/org.testng/testng/7.1.0
we get the test marked as FAILED and the exception logged as:

```
Exception org.testng.TestException
Message: Expected exception of type class java.lang.UnsatisfiedLinkError but got org.testng.internal.InvokeMethodRunnable$TestNGRuntimeException: java.lang.UnsatisfiedLinkError: com.bravogroup.math.robust.Robeth.rpardf0([FIIIIFF[I[I[I)V

Stacktrace:


at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:731)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:629)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.testng.internal.InvokeMethodRunnable$TestNGRuntimeException: java.lang.UnsatisfiedLinkError: com.bravogroup.math.robust.Robeth.rpardf0([FIIIIFF[I[I[I)V
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:53)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:71)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:35)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:314)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:280)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:603)
... 9 more
Caused by: java.lang.UnsatisfiedLinkError: com.bravogroup.math.robust.Robeth.rpardf0([FIIIIFF[I[I[I)V
at com.bravogroup.math.robust.Robeth.rpardf0(Native Method)
at com.bravogroup.math.robust.Robeth.dfrpar(Robeth.java:122)
at com.bravogroup.math.robust.Robeth.dfrpar(Robeth.java:109)
at com.bravogroup.math.robust.Robeth.myhbhe(Robeth.java:73)
at com.bravogroup.math.robust.Robeth.myhbhe(Robeth.java:69)
at com.bravogroup.math.robust.Robeth.myhbhe(Robeth.java:64)
at com.bravogroup.cognity.calc.fa.TSFMUtils.calcRobust(TSFMUtils.java:136)
at com.bravogroup.cognity.calc.fa.TSFMUtils.calcCoefficients(TSFMUtils.java:125)
at com.bravogroup.cognity.calc.fa.TestTSFMUtils.testFailingCalcCoefficients(TestTSFMUtils.java:197)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
... 14 more
```

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by krmahadevan** [comment]
@hnestorova - Do you have a sample to share ?

**Comment by ramadevi04g** [comment]
```
try {
       responseContentLength = Integer.parseInt(responseHeaders.get(expectedHeaderKey));
} catch (NumberFormatException exception) {
softAssert.fail(String.format("Unable to parse the response header [%s] value [%s] into an Integer", expectedHeaderKey, responseHeaders.get(expectedHeaderKey)), exception);
continue;
 }
```
My Test
```
@Test(expectedExceptions = AssertionError.class, expectedExceptionsMessageRegExp = ".*Unable to parse the response header \\[Content-Length\\] value \\[foobar\\] into an Integer")
public void contentLengthValueNoResponseValueInvalid() {
        ...... some test code....
        *****.validate(softAssert, response);
        softAssert.assertAll();
}
```

> org.testng.TestException: 
> The exception was thrown with the wrong message: expected ".*Unable to parse the response header \[Content-Length\] value \[foobar\] into an Integer" but got "The following asserts failed:
> 	Unable to parse the response header [Content-Length] value [foobar] into an Integer For input string: "foobar""

I notice with the newer version, softAssert.fail() throwing a message that has message + realCause(exception message).

**Comment by ramadevi04g** [comment]
@krmahadevan  I have added a sample. Is this expected behavior?

**Comment by hnestorova** [comment]
Hi
Sorry for the late reply. I can see @ramadevi04g  has provided some example, not sure if it resembles our case
Unfortunately, I cannot provide the exact case due to security reasons but in the end we decided to skip the failing tests so i think i can close this one
