### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by AnandhaPriyaK** [cbeust/testng#2373]
Hi all,

I am using testng-version 7.1.0, getting concurrentModificationException in following line.
Please help me fix this issue.

My Code: ExtentManager.getTestStep().log(Status.INFO, m);

Error:
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
at java.util.ArrayList$Itr.next(ArrayList.java:859)
at com.aventstack.extentreports.ExtentObservable.collectRunInfo(ExtentObservable.java:465)
at com.aventstack.extentreports.ExtentObservable.addLog(ExtentObservable.java:309)
at com.aventstack.extentreports.ExtentTest.addLog(ExtentTest.java:359)
at com.aventstack.extentreports.ExtentTest.log(ExtentTest.java:308)
at com.aventstack.extentreports.ExtentTest.log(ExtentTest.java:333)
at com.aventstack.extentreports.ExtentTest.log(ExtentTest.java:352)

Note: i use DataProvider, Multithreading.

**Comment by krmahadevan** [comment]
@AnandhaPriyaK this issue is not because of TestNG. 

It's arising because of extent reports as explained in this comment https://github.com/cbeust/testng/issues/1168#issuecomment-701338422

There is nothing to be done from TestNG.
