### ISSUE TITLE
Regression: Using TestNG via Maven breaks when optional Guice dependency is unavailable

### ISSUE THREAD

**Issue by robbytx** [cbeust/testng#2405]
### TestNG Version
7.4.0-SNAPSHOT (built from bdf1c95501d9b6afb8a6e1a038dbdfbbf7acc378)

### Expected behavior
TestNG should be able to execute simple tests without requiring Guice to be present on the classpath.

### Actual behavior
TestNG fails to start when Guice is not present on the classpath, due to ee6cbabdbf3b5c3eec7685007e4d2d97136308d1.

### Is the issue reproductible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
`pom.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>testng-2403</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.4.0-SNAPSHOT</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19</version>
            </plugin>
        </plugins>
    </build>

</project>
```

`src/test/java/example/TestClass.java` (this doesn't really matter, but one test class must exist for TestNG to execute):
```java
package example;

import org.testng.annotations.Test;

public class TestClass {

    @Test
    public void test() {
        // this should pass
    }
}
```

Actual output:
```
$ mvn clean test
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< org.example:testng-2403 >-----------------------
[INFO] Building testng-2403 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ testng-2403 ---
[INFO] Deleting /Users/morgan/src/testng-2403/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ testng-2403 ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ testng-2403 ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ testng-2403 ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/morgan/src/testng-2403/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ testng-2403 ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 1 source file to /Users/morgan/src/testng-2403/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.19:test (default-test) @ testng-2403 ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running example.TestClass

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.105 s
[INFO] Finished at: 2020-11-04T13:19:12-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test (default-test) on project testng-2403: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test failed: There was an error in the forked process
[ERROR] java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/google/inject/Module
[ERROR] 	at org.testng.GuiceHelper.<clinit>(GuiceHelper.java:28)
[ERROR] 	at org.testng.TestRunner.<init>(TestRunner.java:87)
[ERROR] 	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:593)
[ERROR] 	at org.testng.SuiteRunner.init(SuiteRunner.java:173)
[ERROR] 	at org.testng.SuiteRunner.<init>(SuiteRunner.java:107)
[ERROR] 	at org.testng.TestNG.createSuiteRunner(TestNG.java:1300)
[ERROR] 	at org.testng.TestNG.createSuiteRunners(TestNG.java:1276)
[ERROR] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
[ERROR] 	at org.testng.TestNG.runSuites(TestNG.java:1063)
[ERROR] 	at org.testng.TestNG.run(TestNG.java:1031)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:134)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:118)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] Caused by: java.lang.NoClassDefFoundError: com/google/inject/Module
[ERROR] 	... 17 more
[ERROR] Caused by: java.lang.ClassNotFoundException: com.google.inject.Module
[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] 	... 17 more
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

### Previous Behavior

If you change `7.4.0-SNAPSHOT` to `7.3.0` (or an earlier version), and you add an exclusion for Guice (to eliminate it from the classpath), then it passes.

`pom.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>testng-2403</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.3.0</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.testng</groupId>
                    <artifactId>testng</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19</version>
            </plugin>
        </plugins>
    </build>

</project>
```

Output:
```
$ mvn clean test
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< org.example:testng-2403 >-----------------------
[INFO] Building testng-2403 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ testng-2403 ---
[INFO] Deleting /Users/morgan/src/testng-2403/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ testng-2403 ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ testng-2403 ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ testng-2403 ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/morgan/src/testng-2403/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ testng-2403 ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 1 source file to /Users/morgan/src/testng-2403/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.19:test (default-test) @ testng-2403 ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running example.TestClass
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.381 sec - in example.TestClass

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.587 s
[INFO] Finished at: 2020-11-04T13:23:39-06:00
[INFO] ------------------------------------------------------------------------
```

**Comment by robbytx** [comment]
It appears that #2357 modified the TestNG pom.xml such that `Guice` is now declared as `<optional>true</optional>`.  At least, this is the pom.xml that was produced when I built master:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- This module was also published with a richer model, Gradle metadata,  -->
  <!-- which should be used instead. Do not delete the following line which  -->
  <!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
  <!-- that they should prefer consuming it instead. -->
  <!-- do_not_remove: published-with-gradle-metadata -->
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.testng</groupId>
  <artifactId>testng</artifactId>
  <version>7.4.0-SNAPSHOT</version>
  <name>testng</name>
  <description>Testing framework for Java</description>
  <url>https://testng.org</url>
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>cbeust</id>
      <name>Cedric Beust</name>
      <email>cedric@beust.com</email>
    </developer>
    <developer>
      <id>juherr</id>
      <name>Julien Herr</name>
      <email>julien@herr.fr</email>
    </developer>
    <developer>
      <id>krmahadevan</id>
      <name>Krishnan Mahadevan</name>
      <email>krishnan.mahadevan1978@gmail.com</email>
    </developer>
  </developers>
  <scm>
    <connection>scm:git:git://github.com/cbeust/testng.git</connection>
    <url>https://github.com/cbeust/testng</url>
  </scm>
  <issueManagement>
    <system>Github</system>
    <url>https://github.com/cbeust/testng/issues</url>
  </issueManagement>
  <dependencies>
    <dependency>
      <groupId>com.beust</groupId>
      <artifactId>jcommander</artifactId>
      <version>1.78</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.ant</groupId>
      <artifactId>ant</artifactId>
      <version>1.10.9</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>com.google.inject</groupId>
      <artifactId>guice</artifactId>
      <version>4.2.2</version>
      <classifier>no_aop</classifier>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.yaml</groupId>
      <artifactId>snakeyaml</artifactId>
      <version>1.21</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
  </dependencies>
</project>
```

I believe this is the desired state of the pom.xml, since Guice like YAML are only necessary for optional features, and should only be required to exist on the classpath for tests that use those features.

Therefore, I think the solution is simply to restructure the TestNG code so that dependencies on Guice classes are isolated to the scenarios where Guice features are in use.
