### ISSUE TITLE
SkipException for multiple testclasses causes error in the forked process

### ISSUE THREAD

**Issue by dominikQAEngineer** [cbeust/testng#2415]
### TestNG Version
7.3.0
maven-surefire-plugin - 3.0.0-M5

### Expected behavior
I have testng.xml file that cantains a couple of test classes. I would like to skip the rest of test classes if one of the tests failed and get information about test results. It worked for a couple of years but recently stopped.

### Actual behavior
Since TestNG 7.0.0 there is an error when I try to skip the rest of test classes included in one testsuite.
There are also no information about test results, here is some log example:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
firstMethod prntln
secondMethod prntln
[ERROR] SkipException
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.765 s
[INFO] Finished at: 2020-11-12T18:48:24+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project TestNGSkipException: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\Users\NBDPLATOS\IdeaProjects\TestNGSkipException\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] SkipException
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] SkipException
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:733)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] 	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
POM file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>TestNGSkipException</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.3.0</version>
        </dependency>
    </dependencies>
    <build>
        <!--************************************************-->
        <!-- plugins -->
        <!--************************************************-->
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                    <suiteXmlFiles>
                        <suiteXmlFile>src/test/suites/testng.xml</suiteXmlFile>
                    </suiteXmlFiles>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

**SkipAfterPreviousTestClassFailureListener.java** file:

```java
import org.testng.*;

public class SkipAfterPreviousTestClassFailureListener implements IInvokedMethodListener {

    private boolean hasFailures = false;

    public void beforeInvocation(IInvokedMethod invokedMethod, ITestResult testResult) {
        if (hasFailures) {
            throw new SkipException("SkipException");
        }
    }

    public void afterInvocation(IInvokedMethod invokedMethod, ITestResult testResult) {
        if (! invokedMethod.isTestMethod()) {
            return;
        }
        if (! testResult.isSuccess()) {
                hasFailures = true;
        }
    }
}
```

**Test classes:**
```java
public class FirstTestClass {
    @Test(description = "First test step")
    public void firstMethod(){
        System.out.println("firstMethod prntln");
    }
    @Test(description = "Second test step", dependsOnMethods = "firstMethod")
    public void secondMethod(){
        System.out.println("secondMethod prntln");
        Assert.fail();
    }
    @Test(description = "Third test step", dependsOnMethods = "secondMethod")
    public void thirdMethod(){
        System.out.println("thirdMethod prntln");
    }
}
```
```java
public class SecondTestClass {
    @Test(description = "First test step")
    public void firstMethod(){
        System.out.println("firstMethod prntln");
    }
    @Test(description = "Second test step", dependsOnMethods = "firstMethod")
    public void secondMethod(){
        System.out.println("secondMethod prntln");
    }
    @Test(description = "Third test step", dependsOnMethods = "secondMethod")
    public void thirdMethod(){
        System.out.println("thirdMethod prntln");
    }
}
```

Testng.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="SkipException with multiple classes" verbose="1" parallel="false" thread-count="1" time-out="300000">
    <listeners>
        <listener class-name="SkipAfterPreviousTestClassFailureListener"/>
    </listeners>
    <test name="SkipException with multiple classes">
        <classes>
            <class name="FirstTestClass"/>
            <class name="SecondTestClass"/>
        </classes>
    </test>
</suite>
```

**Comment by bj-9527** [comment]
Hi,
I can reproduce your problem
Based on the message, could you please specify what have been changed recently in your project, and which version JDK are used in your project.
And also, could you please give the version which can successfully install.

**Comment by dominikQAEngineer** [comment]
Hi, this problem appear when I try to upgrade my TestNG version. TestNG 6.14.3 worked perfectly fine.
I use jdk 1.8.0_241.
What do You mean by "version which can successfully install?"

**Comment by krmahadevan** [comment]
@dominikQAEngineer - The latest released version of TestNG is `7.3.0`. Please try using that and let us know if its still a problem.

> "version which can successfully install?"

I guess @bj-9527 meant to ask, "Tell us what was the version wherein you saw this working".

**Comment by dominikQAEngineer** [comment]
I know about latest released version.
TestNG 7.3.0 - not working and that is why I created this issue
TestNG 6.14.3 - don't have this issue.

**Comment by krmahadevan** [comment]
@dominikQAEngineer  - Thanks for clarifying that.

**Comment by bj-9527** [comment]
Hi @dominikQAEngineer ,
I changed the testng version in pom file from 7.3.0 to 6.14.3, but it also failed during installation.
```
firstMethod prntln
secondMethod prntln
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 4, Time elapsed: 5.24 s <<< FAILURE! - in TestSuite
[ERROR] FirstTestClass.secondMethod  Time elapsed: 0.015 s  <<< FAILURE!
java.lang.AssertionError: null
	at FirstTestClass.secondMethod(FirstTestClass.java:13)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   FirstTestClass.secondMethod:13 null
[INFO] 
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 4

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.899 s
[INFO] Finished at: 2020-11-14T20:21:38+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project TestNGSkipException: There are test failures.
```
I'm not sure it's the right behavior. Have you changed 'maven-surefire-plugin' version recently?

**Comment by dominikQAEngineer** [comment]
Your log is example of expected behaviour. There is no "There was an error in the forked process" information and You can see test results:
Tests run: 6, Failures: 1, Errors: 0, Skipped: 4

When You upgrade to testng 7+ there is:
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process

and also no test results:
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

And that's my issue :)

**Comment by dominikQAEngineer** [comment]
Hi @bj-9527,
can You see my problem?
Best regards

**Comment by bj-9527** [comment]
Yes, of course. But I'm not sure what makes this happen for now.

**Comment by bj-9527** [comment]
Hi @dominikQAEngineer ,

I have found the problem and raised a PR, you can check it.

BR

**Comment by dominikQAEngineer** [comment]
Hi @bj-9527 
thank You for the solution. Do I have to do anything with that or just wait for another release?

**Comment by bj-9527** [comment]
I think maybe wait for the next release :)

**Comment by krmahadevan** [comment]
This is fixed via https://github.com/cbeust/testng/pull/2528
