### ISSUE TITLE
Rework MethodInheritance.fixMethodInheritance to "soft" dependencies

### ISSUE THREAD

**Issue by vlsi** [cbeust/testng#2432]
### TestNG Version

7.0.0, 7.3.0

### Expected behavior

I expect `@BeforeSuite(groups=...)` should add configuration methods to a "configuration group", and I expect multiple different classes should be able to "add a configuration method" to a group.

My use case is a database-related test: "prepare configuration", "upload configuration", "execute test". The upload step might take 1-2 minutes, so I batch the upload: I gather the bits from all the test classes in the suite, and I execute "upload configuration to db" just once.

The structure of the tests is as follows:

```java
import org.testng.annotations.BeforeSuite;

public class Base {
    @BeforeSuite(groups = "prepareConfig")
    public void prepareConfig() {
        // This method prepares the baseline configuration
        // Other classes might contribute to it via their own @BeforeSuite(groups = "prepareConfig")
        System.out.println("prepareConfig");
    }

    @BeforeSuite(groups = "uploadConfigToDatabase", dependsOnGroups = "prepareConfig")
    public void uploadConfigToDatabase() {
        // This method uploads the configuration to database. In most of the cases, it is the only method in uploadConfigToDatabase group
        System.out.println("uploadConfigToDatabase");
    }

    @BeforeSuite(groups = "verifyConfigurationAfterInstall", dependsOnGroups = "uploadConfigToDatabase")
    public void verifyConfigurationAfterInstall() {
        // Verify the database before tests start executing
        // Other classes can contribute their own checks via @BeforeSuite(groups = "verifyConfigurationAfterInstall")
        System.out.println("verifyConfigurationAfterInstall");
    }
}
```

```java
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

public class Test1 extends Base {
    @BeforeSuite(groups = "prepareConfig")
    public void prepareConfigForTest1() {
        System.out.println("prepareConfigForTest1");
    }

    @Test
    public void test1() {
    }
}
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<suite name="Groups test" parallel="false">
  <test name="Test groups">
    <classes>
      <class name="Test1">
        <methods><include name="test1"/></methods>
      </class>
    </classes>
  </test>
</suite>
```

I expect that `Test1#prepareConfigForTest1` participates in `prepareConfig` configuration group, so I expect the following execution order:

```
Base#prepareConfig
Test1#prepareConfigForTest1
Base#uploadConfigToDatabase
Base#verifyConfigurationAfterInstall

Test1#test1
```

In other words, I expect that the full set of dependencies is as follows:

```
Base#prepareConfig: no dependencies

Test1#prepareConfigForTest1
  "soft" depends on all BeforeSuite in Base (because Test1 inherits Base class):
      Base#prepareConfig, Base#uploadConfigToDatabase, Base#verifyConfigurationAfterInstall
  "hard" depends on: empty

Base#uploadConfigToDatabase
  "hard" depends on: all configuration methods in prepareConfig group: Base#prepareConfig, Test1#prepareConfigForTest1

Base#verifyConfigurationAfterInstall
  "hard" depends on: all configuration methods in uploadConfigToDatabase: Base#uploadConfigToDatabase
```

Then TestNG should make the topological sort taking all hard constraints into consideration, and it should fulfill soft constraints on the best effort basis.

### Actual behavior

TestNG adds "implicit" dependency (via `org.testng.internal.MethodInheritance#fixMethodInheritance`)  of "`Test1#prepareConfigForTest1` depends on `Base#verifyConfigurationAfterInstall`" which results in a configuration cycle, so the engine fails as follows

```
Caused by: org.testng.TestNGException: 
The following methods have cyclic dependencies:
Base.verifyConfigurationAfterInstall()[pri:0, instance:null]
Test1.prepareConfigForTest1()[pri:0, instance:null]
Base.uploadConfigToDatabase()[pri:0, instance:null]

	at org.testng.internal.Graph.topologicalSort(Graph.java:128)
	at org.testng.internal.MethodHelper.topologicalSort(MethodHelper.java:299)
	at org.testng.internal.MethodHelper.sortMethods(MethodHelper.java:382)
	at org.testng.internal.MethodHelper.collectAndOrderMethods(MethodHelper.java:71)
	at org.testng.internal.TestNGMethodFinder.findConfiguration(TestNGMethodFinder.java:200)
	at org.testng.internal.TestNGMethodFinder.getBeforeSuiteMethods(TestNGMethodFinder.java:79)
	at org.testng.TestClass.initMethods(TestClass.java:123)
	at org.testng.TestClass.init(TestClass.java:75)
	at org.testng.TestClass.<init>(TestClass.java:39)
	at org.testng.TestRunner.initMethods(TestRunner.java:457)
	at org.testng.TestRunner.init(TestRunner.java:336)
	at org.testng.TestRunner.init(TestRunner.java:289)
	at org.testng.TestRunner.<init>(TestRunner.java:180)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:613)
	at org.testng.SuiteRunner.init(SuiteRunner.java:178)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:112)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1306)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1282)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1131)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
```

### Is the issue reproductible on runner?

The above exception is from Gradle 6.6, however, I'm quite sure it is reproducible from Shell runner as well.

**Comment by vlsi** [comment]
@juherr , it looks #2437 does not fully resolve the case.

Here's an updated sample:

```java
import org.testng.annotations.BeforeSuite;

public class Base {
    public final static String PREPARE_CONFIG = "prepareConfig";
    public final static String UPLOAD_CONFIG = "uploadConfigToDatabase";
    public final static String CHECK_AFTER_INSTALL = "verifyConfigurationAfterInstall";

    @BeforeSuite(groups = PREPARE_CONFIG)
    public void prepareConfig() {
        // This method prepares the baseline configuration
        // Other classes might contribute to it via their own @BeforeSuite(groups = "prepareConfig")
        System.out.println("dependency-only: PREPARE_CONFIG");
    }

    @BeforeSuite(groups = UPLOAD_CONFIG, dependsOnGroups = PREPARE_CONFIG)
    public void uploadConfigToDatabase() {
        // This method uploads the configuration to database. In most of the cases, it is the only method in uploadConfigToDatabase group
        System.out.println("dependency-only: UPLOAD_CONFIG");
    }

    @BeforeSuite(groups = CHECK_AFTER_INSTALL, dependsOnGroups = UPLOAD_CONFIG)
    public void verifyConfigurationAfterInstall() {
        // Verify the database before tests start executing
        // Other classes can contribute their own checks via @BeforeSuite(groups = "verifyConfigurationAfterInstall")
        System.out.println("dependency-only: CHECK_AFTER_INSTALL");
    }

    @BeforeSuite(groups = PREPARE_CONFIG)
    public void genericPrepare() {
        System.out.println("default: PREPARE_CONFIG");
    }

    @BeforeSuite(groups = UPLOAD_CONFIG)
    public void uploadConfig() {
        System.out.println("default: UPLOAD_CONFIG");
    }

    @BeforeSuite(groups = CHECK_AFTER_INSTALL)
    public void checkAfterInstall() {
        System.out.println("default: CHECK_AFTER_INSTALL");
    }
}
```

```java
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

public class Test1 extends Base {
    @BeforeSuite(groups = PREPARE_CONFIG)
    public void prepareConfigForTest1() {
        System.out.println("test1: PREPARE_CONFIG");
    }

    @BeforeSuite(groups = CHECK_AFTER_INSTALL)
    public void checkInstallForTest1() {
        System.out.println("test1: CHECK_AFTER_INSTALL");
    }

    @Test
    public void test1() {
    }
}
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<suite name="Groups test" parallel="false">
    <test name="Test groups">
        <classes>
            <class name="Test1">
                <methods><include name="test1"/></methods>
            </class>
        </classes>
    </test>
</suite>
```

Actual result:

```
Groups test STANDARD_OUT
    Run configuration Test1.genericPrepare
    default: PREPARE_CONFIG
        OK   17ms
    Run configuration Test1.prepareConfig
    dependency-only: PREPARE_CONFIG
        OK   0ms
    Run configuration Test1.uploadConfig
    default: UPLOAD_CONFIG
        OK   0ms
    Run configuration Test1.prepareConfigForTest1
    test1: PREPARE_CONFIG
        OK   0ms
    Run configuration Test1.uploadConfigToDatabase
    dependency-only: UPLOAD_CONFIG
        OK   1ms
    Run configuration Test1.verifyConfigurationAfterInstall
    dependency-only: CHECK_AFTER_INSTALL
        OK   1ms
    Run configuration Test1.checkAfterInstall
    default: CHECK_AFTER_INSTALL
        OK   0ms
    Run configuration Test1.checkInstallForTest1
    test1: CHECK_AFTER_INSTALL
        OK   1ms

Groups test > Test groups > Test1 STANDARD_OUT
    Run test Test1.test1
```

My expectation is "all methods in PREPARE_CONFIG group" should be executed before methods in UPLOAD_CONFIG group.

However, `prepareConfigForTest1` is scheduled after `uploadConfig` :-(
