### ISSUE TITLE
NPE in FailedReporter.java With Tests Created in Factory

### ISSUE THREAD

**Issue by egglestonbd** [cbeust/testng#2445]
### TestNG Version
7.3.0
(Note, this did not occur with 6.9.11, and began with the upgrade to the latest).
### Expected behavior
No NPE upon failure when using A Factory Class (with @Factory annotation) to define our xml Suite.

Sample testng.xml:
```
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
<suite name="IntegrationTestSuite" verbose="1" parallel="methods" thread-count="15" configfailurepolicy="continue">

  <!--***** Set Parameters to be passed to methods *****-->
  <parameter name="baseUrl" value="http://localhost:8080/"/>


  <!--***** Define test Configuration below  *****-->
  <test name="service-at-local">
    <classes>
      <class name="org.acceptance.MyFactory"/>
    </classes>
  </test>
</suite>
```
MyFactory.java contains:
```
  @Factory
  public Object[] create() {
    List<Object> vResult = new ArrayList<>();

    vResult.add(new TestX());
    vResult.add(new TestY());

    return vResult.toArray();
  }
```

### Actual behavior

When the TestX() class has failures, the following NPE is produced.

```
[TestNG] Reporter [FailedReporter passed=0 failed=0 skipped=0] failed
java.lang.NullPointerException
	at java.util.HashMap.putMapEntries(HashMap.java:501)
	at java.util.HashMap.putAll(HashMap.java:785)
	at org.testng.xml.XmlClass.setParameters(XmlClass.java:233)
	at org.testng.reporters.FailedReporter.createXmlClasses(FailedReporter.java:199)
	at org.testng.reporters.FailedReporter.createXmlTest(FailedReporter.java:150)
	at org.testng.reporters.FailedReporter.generateXmlTest(FailedReporter.java:124)
	at org.testng.reporters.FailedReporter.generateFailureSuite(FailedReporter.java:64)
	at org.testng.reporters.FailedReporter.generateReport(FailedReporter.java:49)
	at org.testng.TestNG.generateReports(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1042)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

At this [line][0], xmlClass.getName() returns the individual TestX() and classParameters contains only the key of the MyFactory Class. Therefore classParameters.get(xmlClass.getName()) results in a null.

[0]: https://github.com/cbeust/testng/blob/7.3.0/src/main/java/org/testng/reporters/FailedReporter.java#L199

### Is the issue reproducible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [X] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by arham-jain** [comment]
Have added a fallback to the older behaviour i.e., aggregating all of the parameters when setting XML class parameters when a specific classes' parameters are not found, to fix this
