### ISSUE TITLE
Removal of org.testng.xml.XmlSuite.setParallel(java.lang.String) breaks surefire maven plugin

### ISSUE THREAD

**Issue by josephlbarnett** [cbeust/testng#2485]
### TestNG Version
7.4.0

### Expected behavior
Tests run with parallel flags set

### Actual behavior
All surefire-testng breaks when trying to setParallel:
```
java.lang.NoSuchMethodError: 'void org.testng.xml.XmlSuite.setParallel(java.lang.String)'
        at org.apache.maven.surefire.testng.conf.TestNGMapConfigurator.configure(TestNGMapConfigurator.java:71)
        at org.apache.maven.surefire.testng.conf.TestNG510Configurator.configure(TestNG510Configurator.java:40)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:111)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```
Also filed this w/ surefire as https://issues.apache.org/jira/browse/SUREFIRE-1890, but unsure if testng wants to restore the method until surefire support exists?

### Is the issue reproductible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
Surefire is configured as:
```
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${version.maven.surefire}</version>
                    <configuration>
                        <skip>${skip.tests}</skip>
                        <argLine>
                            ${jacocoArgLineUnit}
                        </argLine>
                        <parallel>methods</parallel>
                        <threadCount>10</threadCount>
                        <trimStackTrace>false</trimStackTrace>
                    </configuration>
                </plugin>
```

**Comment by krmahadevan** [comment]
@Tibor17 - Can you please have this taken care of in surefire plugin ?

**Comment by josephlbarnett** [comment]
opened up https://github.com/apache/maven-surefire/pull/339 in surefire, fwiw

**Comment by Tibor17** [comment]
@krmahadevan 
Thx, we will continue in Surefire.
T

**Comment by krmahadevan** [comment]
@josephlbarnett - Since this will be fixed in Surefire plugin, can we close this issue here ?

**Comment by josephlbarnett** [comment]
@krmahadevan up to you, I'm ok with taht

**Comment by krmahadevan** [comment]
Closing this issue since it would be fixed from surefire
