### ISSUE TITLE
TestNG 7.4.0 throws an exception "sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection" when xml file contain "ENTITY  SYSTEM" grammer

### ISSUE THREAD

**Issue by xirs** [cbeust/testng#2501]
### TestNG Version
> Note: only the latest version is supported
7.4.0
### Expected behavior
works as 7.1.0 

### Actual behavior
TestNG 7.4.0 throws an exception "sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection" when case xml file contain raw XML mechanism grammer like below:

```
<!ENTITY raw_listeners SYSTEM "testng/_listener/raw_listeners.xml">
        ]>
```

see java stack:

```
Connected to the target VM, address: '127.0.0.1:62526', transport: 'socket'
[TestNGContentHandler] [WARN] Failed to read [/E:/A_Project/A_Code/ose-test/jss_test/testng/_listener/raw_listeners.xml] from CLASSPATH. Attempting to read from [file:///E:/A_Project/A_Code/ose-test/jss_test/testng/_listener/raw_listeners.xml].
org.testng.TestNGException: java.lang.ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
	at org.testng.TestNG.parseSuite(TestNG.java:356)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:376)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:39)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
	at org.testng.xml.TestNGContentHandler.lambda$new$0(TestNGContentHandler.java:70)
	at org.testng.xml.TestNGContentHandler.resolveEntity(TestNGContentHandler.java:138)
	at com.sun.org.apache.xerces.internal.util.EntityResolverWrapper.resolveEntity(EntityResolverWrapper.java:110)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntityAsPerStax(XMLEntityManager.java:997)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1212)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEntityReference(XMLDocumentFragmentScannerImpl.java:1908)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3061)

```

### Is the issue reproductible on runner?

- [X ] Shell
- [X ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
1. write a testng xml case file like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" [
        <!ENTITY raw_listeners SYSTEM "testng/_listener/raw_listeners.xml">
        ]>
<suite name="ECBench Suite">
  <groups>
    <run>
      <exclude name = "known_bug"/>
      <exclude name = "disabled"/>
    </run>
  </groups>
  <test name="ecbench test">
    <classes>
      <class name="com.cloud.test.ecbench.ecmaster.Node.AddNodeTest" />
    </classes>
  </test> 
  &raw_listeners;
</suite>
```

and write another file which will be imported by using XML ENTITY grammer
```
<?xml version="1.0" encoding="UTF-8"?>

<listeners>
    <listener class-name="com.cloud.report.listener.TestNgReportListener"/>
</listeners>
```

2.  execute this case, and testng 7.4.0 will throw an exception "sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection"

but testng versions before 7.1.0 can recognize ENTITY in xml case files,

**Comment by krmahadevan** [comment]
@xirs - How are you running your test?

I tried running this from within IntelliJ and I dont see any exception. I also dont see the listener being invoked as well (which is a separate problem)

**Comment by krmahadevan** [comment]
ping @xirs

**Comment by gdflorea** [comment]
Hi, I'm pretty sure that I have the same problem, asked a question about this on StackOverflow, you can find more details here - https://stackoverflow.com/questions/66118355/java-lang-classcastexception-when-trying-to-import-document-entities-in-a-testng .  Also tested with 7.4.0, it's the same. Let me know what more info do you need, I'll be happy to assist. Running from Maven project using Eclipse 2020.03, TestNG plugin 7.4.0, openjdk 14. I could also try running it from IntelliJ if it's any help.

**Comment by krmahadevan** [comment]
@gdflorea - Can you please try downgrading your JDK to JDK8 and let us know what you see ? I think this could be related to JDK

**Comment by gdflorea** [comment]
Same problem with JDK8, TestNG 6.9.11 is ok, 7.4.0 fails

**Comment by krmahadevan** [comment]
@gdflorea - It would be really good if you could please help debug more to find out if you can help get us any additional context on how we can reproduce this error.

Maybe the JDK flavour and JDK version also will help. Can you please create a sample project that we can use to reproduce this via a runner (Maven/Gradle) or maybe using a public static void main method ?

**Comment by xirs** [comment]
@krmahadevan I created a IDEA project, it will help to reproduce this issue.

[Testng.zip](https://github.com/cbeust/testng/files/7725942/Testng.zip)

I use JDK 1.8, see the configutation when I run the testngxml
![image](https://user-images.githubusercontent.com/7657918/146343633-c13539c0-b4e0-4f14-abe4-94aa066d464e.png)

**Comment by gdflorea** [comment]
@krmahadevan See attached archive. Tried to do everything as simple as possible, so I went for the public static void main method and classpath in cmd.
[TestProject.zip](https://github.com/cbeust/testng/files/7736651/TestProject.zip)

Running with TestNG 6.9.11 everything is ok
`d:\TestProject\bin>java -cp ./;../lib/testng-6.9.11.jar;../lib/jcommander-1.78.jar Main`
produces the output(among other things)
`Total tests run: 1, Failures: 0, Skips: 0`

But running with TestNG 7.4.0 it crashes:
`d:\TestProject\bin>java -cp ./;../lib/testng-7.4.0.jar;../lib/jcommander-1.78.jar Main`
results in 
```
[TestNGContentHandler] [WARN] Failed to read [/d:/TestProject/bin/params.xml] from CLASSPATH. Attempting to read from [file:///d:/TestProject/bin/params.xml].
Exception in thread "main" org.testng.TestNGException: java.lang.ClassCastException: class sun.net.www.protocol.file.FileURLConnection cannot be cast to class java.net.HttpURLConnection (sun.net.www.protocol.file.FileURLConnection and java.net.HttpURLConnection are in module java.base of loader 'bootstrap')
        at org.testng.TestNG.parseSuite(TestNG.java:356)
        at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:376)
        at org.testng.TestNG.initializeEverything(TestNG.java:1011)
        at org.testng.TestNG.run(TestNG.java:1023)
        at Main.main(Main.java:10)
Caused by: java.lang.ClassCastException: class sun.net.www.protocol.file.FileURLConnection cannot be cast to class java.net.HttpURLConnection (sun.net.www.protocol.file.FileURLConnection and java.net.HttpURLConnection are in module java.base of loader 'bootstrap')
```
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OS: Windows 10
I'm pretty sure that the jdk version is not relevant, I also tested with 8, but not with the attached files.

**Comment by krmahadevan** [comment]
@gdflorea - Thanks for the persistence on bringing out this issue. The problem was because of embedding file entities in the suite xmls which was the root cause. I have fixed it and raised a PR. So this problem should go away after `7.5.0` (upcoming version) gets released.
