### ISSUE TITLE
Help： NullPointerException throws when using MethodSelector to customize rerun xmlSuite with testcase which is annotated with @Test(alwaysRun = true)

### ISSUE THREAD

**Issue by tyingrong** [cbeust/testng#253]
HI, there

I'm working for Taobao.Inc as a Software Developer Engineer in Test. I met an issue that blocks my work a lot. Details infomation as below：

I'm working  on a rerun mechanism on test failure using testng. And this issue blocks a lot to move on to fix this issue. Pls help！！！！！ 

Defect Description: 
 NullPointerException when using MethodSelector to customize rerun xmlSuite with testcase which is annotated with @Test(alwaysRun = true).

Pay Attention:
 This defect only repro-ed with customization of rerun xmlSuite with implemented IMethodSelector. I used XmlInclude method to create customized rerun XmlSuite works just fine.!!

Error Stack Trace:
java.lang.NullPointerException
    at org.testng.DependencyMap.getMethodDependingOn(DependencyMap.java:38)
    at org.testng.TestRunner.createDynamicGraph(TestRunner.java:1070)
    at org.testng.TestRunner.privateRun(TestRunner.java:734)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
    at org.testng.TestNG.run(TestNG.java:1022)
    at com.etao.adtest.iselenium.common.TestFailureRerunListener.onTestFailure(TestFailureRerunListener.java:77)
    at org.testng.internal.Invoker.runTestListeners(Invoker.java:1883)
    at org.testng.internal.Invoker.runTestListeners(Invoker.java:1867)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1280)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:768)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
    at org.testng.TestNG.run(TestNG.java:1022)
    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)

Best Regards!!

YOURS,
Jane Lee

**Comment by krmahadevan** [comment]
@cbeust - Was this resolved by you ? If not, it would be great if you could please help share the sample project that was mailed to you.

**Comment by cbeust** [comment]
Not sure, that was five years ago. Closing.
