### ISSUE TITLE
Exception thrown when method is disabled programatically and there is another dependant method

### ISSUE THREAD

**Issue by jgomer2001** [cbeust/testng#2546]
I make use of `IAnnotationTransformer#transform` to disable some tests programmatically. I use `ITestAnnotation#setEnabled(false)` depending on certain custom logic.

If the disabled test is say, `search`, and in the same class there is another method `delete` so that:

```
@Test(dependsOnMethods = "search", alwaysRun = true)
public void delete(){
        blah...
}
```

An exception is thrown. 

### TestNG Version
7.4.0, 6.14.3

### Expected behavior

No exception. Method should not be deleted from graph, just bypassed on traversal.

### Actual behavior

```
[ERROR] 
[ERROR] Method "Test.delete()[pri:0, instance:co.acme.Test@2d9caaeb]" depends on nonexistent method "co.acme.Test.search"
[ERROR] 	at org.testng.DependencyMap.getMethodDependingOn(DependencyMap.java:80)
[ERROR] 	at org.testng.internal.DynamicGraphHelper.lambda$null$0(DynamicGraphHelper.java:54)
[ERROR] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[ERROR] 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[ERROR] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[ERROR] 	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
[ERROR] 	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
[ERROR] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[ERROR] 	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
[ERROR] 	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
[ERROR] 	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
[ERROR] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
[ERROR] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[ERROR] 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
[ERROR] 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:650)
[ERROR] 	at org.testng.internal.DynamicGraphHelper.lambda$createDynamicGraph$3(DynamicGraphHelper.java:53)
[ERROR] 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[ERROR] 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
[ERROR] 	at org.testng.internal.DynamicGraphHelper.createDynamicGraph(DynamicGraphHelper.java:39)
[ERROR] 	at org.testng.TestRunner.lambda$privateRun$1(TestRunner.java:735)
[ERROR] 	at org.testng.util.TimeUtils.computeAndShowTime(TimeUtils.java:50)
[ERROR] 	at org.testng.TestRunner.privateRun(TestRunner.java:732)
[ERROR] 	at org.testng.TestRunner.run(TestRunner.java:596)
[ERROR] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
[ERROR] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
[ERROR] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
[ERROR] 	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
[ERROR] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[ERROR] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[ERROR] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
[ERROR] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
[ERROR] 	at org.testng.TestNG.runSuites(TestNG.java:1063)
[ERROR] 	at org.testng.TestNG.run(TestNG.java:1031)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

### Is the issue reproductible on runner?

- [ ] Shell
- [x ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by jgomer2001** [comment]
btw, the same goes when just doing `@Test(enabled=false)` manually. I think `disabling` should not entail removal but sort of ignoring/deactivating.

**Comment by krmahadevan** [comment]
@jgomer2001 - You can control TestNG's behaviour (should it fail when there is an upstream failure or should it continue as is) from within the annotation transformer as seen below:


```java
import org.testng.annotations.Test;

public class TestClassSample {

  @Test
  public void upstreamMethod() {}

  @Test(dependsOnMethods = "upstreamMethod")
  public void downstreamMethod() {}
}
```

```java
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.Arrays;
import org.testng.IAnnotationTransformer;
import org.testng.annotations.ITestAnnotation;

public class LocalTransformer implements IAnnotationTransformer {

  @Override
  public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor,
      Method testMethod) {
    if ("upstreamMethod".equals(testMethod.getName())) {
      annotation.setEnabled(false);
    }
    if (Arrays.asList(annotation.getDependsOnMethods()).contains("upstreamMethod")) {
      annotation.setIgnoreMissingDependencies(true);
    }
  }
}
```

Now when you run the tests with the above annotation transformer, the test method runs fine.

I think this should do what you are looking for.

**Comment by jgomer2001** [comment]
Thanks for enlightment
