### ISSUE TITLE
Flaky test: ThreadAffinityTest#testThreadAffinity

### ISSUE THREAD

**Issue by vlsi** [cbeust/testng#2557]
### TestNG Version

The latest

### Expected behavior

The test should not fail.

### Actual behavior

https://travis-ci.org/github/cbeust/testng/jobs/772083005#L1270-L1274

```
FAILURE   0.1sec, test.thread.parallelization.ThreadAffinityTest > testThreadAffinity[1]([Ljava.lang.Class;@8402514)
    java.lang.AssertionError: 
    Expected size:<2> but was:<1> in:
    <["5904", "5903"]>
        at test.thread.parallelization.ThreadAffinityTest.testThreadAffinity(ThreadAffinityTest.java:39)
```

@krmahadevan , is there a possibility you remember something regarding the test? ;)

I did try increasing the number of invocations for the test to 10000. Then I configured `LogGatheringListener` to use `Collections.synchronizedSet(Sets.newHashSet())` instead of the regular `Sets.newHashSet()`.

It caused quite a surprising result (one or two among 10000 invocations, Java 15)):

```
Expected size:<2> but was:<3> in:
<["42896", "9448", "42897"]>
java.lang.AssertionError: 
Expected size:<2> but was:<3> in:
<["42896", "9448", "42897"]>
	at test.thread.parallelization.ThreadAffinityTest.testThreadAffinity(ThreadAffinityTest.java:39)
	at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:593)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:175)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:49)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:826)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:147)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:129)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:415)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:376)
	at org.testng.SuiteRunner.run(SuiteRunner.java:320)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1142)
	at org.testng.TestNG.runSuites(TestNG.java:1071)
	at org.testng.TestNG.run(TestNG.java:1039)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

### Test case sample

`test.thread.parallelization.ThreadAffinityTest#testThreadAffinity`

**Comment by vlsi** [comment]
Ok, my understanding is that `test.thread.parallelization.ThreadAffinityTest#testThreadAffinity` wants to check if each test class is executed in a single thread only.

Would it be better to track thread ID in the test itself rather than in the listener?
I guess the class is in much better position to assert the current thread. Then `Reporter.log` in classes like `PriorityTestSample1` should be replaced with storing the current thread (no need to rely on thread id) in a test field and verifying that all test methods are executed by the same thread.

WDYT?

**Comment by juherr** [comment]
We often have random failing tests with the parallel feature.
Any help is welcome ;)

**Comment by krmahadevan** [comment]
@vlsi - Your understanding in terms of the thread affinity is correct. 

> Would it be better to track thread ID in the test itself rather than in the listener?

`afterInvocation()` is guaranteed to run on the same thread as the test. So it shouldnt be the cause. Moreover, we are trying to run two or more test classes together to check for the thread affinity which is what is failing.

What confuses me is this output in the test results

```
java.lang.AssertionError: 
Expected size:<4> but was:<5> in:
<[6019, 6020, 6021, 6022]>
```

How is the output saying the same was 5, when there are just 4 elements in the set ? Or am I reading this incorrectly ?

**Comment by vlsi** [comment]
> How is the output saying the same was 5, when there are just 4 elements in the set ? 

Please double-check the description.

1. "Obvious":

```java
public class LogGatheringListener implements IInvokedMethodListener {

    Set<String> log = Sets.newHashSet(); // <-- this is UNSAFE for concurrent access, and the listener is shared between threads
```

2. Less obvious: AFAIK thread pool is free to schedule test class on whatever thread it prefers. Of course, the affinity feature should make all the methods to be executed in the same thread, however, each time the test could start on **any** thread in the thread pool. The test configures the thread pool executor with 6 threads, so it is unclear why the test expects that only 2 of 6 threads will be used in the executor.

**Comment by krmahadevan** [comment]
@vlsi 

> Less obvious: AFAIK thread pool is free to schedule test class on whatever thread it prefers. Of course, the affinity feature should make all the methods to be executed in the same thread, however, each time the test could start on any thread in the thread pool. The test configures the thread pool executor with 6 threads, so it is unclear why the test expects that only 2 of 6 threads will be used in the executor.

This is not applicable, because the whole point of supporting thread affinity is to ensure that threads are confined to the affinity behavior as requested by the user. So the number of concurrent threads should always be either equal to the size of the thread pool (when the number of independent threads is more) or equal to the number of independent test methods (when the independent test method count is less than the thread pool size). Right now the implementation does look for the thread id that was provided at the beginning, for the dependent thread to re-use that. If it doesn't get that same thread id, it would wait.

**Comment by vlsi** [comment]
>thread id that was provided at the beginning, for the dependent thread to re-use that. If it doesn't get that same thread id, it would wait

Would you please use that in the assertion? Why merging all the ids into a single set when you could detect the case when a test method switches to a new thread id?

If you merge ids to a set you could miss the case when two tests "exchange" threads: the number of active threads would still be two, however, the affinity would not be there

**Comment by krmahadevan** [comment]
@vlsi 

> Would you please use that in the assertion? Why merging all the ids into a single set when you could detect the case when a test method switches to a new thread id?

And how do you propose that we propagate the upstream test method thread id to its downstream dependent?

> Why merging all the ids into a single set when you could detect the case when a test method switches to a new thread id?

The single set is for all the thread ids for an execution and not for an individual test class.

> If you merge ids to a set you could miss the case when two tests "exchange" threads: 

I didnt quite understand. Care to elaborate ?

**Comment by vlsi** [comment]
> I didnt quite understand. Care to elaborate ?
For instance, let us consider

```java
  @Test(dataProvider = "dp2")
  public void testThreadAffinityAcrossTests(XmlSuite.ParallelMode mode, int size) {
    XmlSuite xmlsuite = createXmlSuite("test_suite");
    xmlsuite.setParallel(XmlSuite.ParallelMode.TESTS);
    xmlsuite.setThreadCount(6);
    createXmlTest(xmlsuite, "Test_1", PriorityTestSample1.class, PriorityTestSample2.class).setParallel(mode);
    createXmlTest(xmlsuite, "Test_2", PriorityTestSample1.class,PriorityTestSample2.class).setParallel(mode);
    TestNG testng = create(xmlsuite);
    LogGatheringListener listener = new LogGatheringListener();
    testng.addListener(listener);
    testng.run();
    assertThat(listener.getLog()).hasSize(size);
  }

  @DataProvider(name = "dp2")
  public Object[][] createTestData() {
    return new Object[][] {
            {XmlSuite.ParallelMode.NONE, 2},
```

Suppose thread ids are 1, 2, 3, 4, 5, 6

Suppose PriorityTestSample1 methods are scheduled as follows:
`PriorityTestSample1#FirstTest` in thread1,
`PriorityTestSample1#SecondTest` in thread2,
`PriorityTestSample1#ThridTest` in thread1,

and PriorityTestSample2 schedules as follows:

`PriorityTestSample2#FirstTest` in thread2,
`PriorityTestSample2#SecondTest` in thread1,
`PriorityTestSample2#ThridTest` in thread2,

The overall set of `thread ids` would be `[1, 2]`, so the test would pass even though the affinity is violated.

If the above scheduling is allowable, then I do not understand what do you mean by "affinity".

**Comment by vlsi** [comment]
In any case, please care to add **message** to the assertion so it clarifies **why** 2 or 4 is expected. The test is non-trivial, and it is hard to tell what has failed and what was the intention behind the test.

**Comment by krmahadevan** [comment]
@vlsi 

That's now how it would work.

```
PriorityTestSample1
    FirstTest (p1)
    SecondTest (p2)
    ThridTest (p3)
```

```
PriorityTestSample2
    FirstTest (p1)
    SecondTest (p2)
    ThridTest (p3)
```

When TestNG schedules the test, first 
`PriorityTestSample1.FirstTest` and `PriorityTestSample2.FirstTest` get scheduled in T1 and T2 threads.
Since TestNG is internally using a DAG, the rest of the tests will not be executed until the above mentioned P1 tests are run to completion.

After this, the thread affinity feature ensures that remaining threads are executed. So the usecase/example that you have called out cannot happen, because if that happens, it basically means that priority in TestNG is itself broken!

Now coming to the assertion part, I can probably think of leveraging a Map which adds more clarity in terms of the thread affinity feature.

**Comment by vlsi** [comment]
@krmahadevan , what you describe is the implementation detail, while assertion should better test **expected behavior** rather than rely on the implementation details.

If you expect that all the methods in a single class must be executed within the same thread, then please assert exactly that. For instance, monitor `Thread.currentThread()` inside test methods and assert the thread does not vary from method to method.

If you have other expectations on the overall behavior, then you could add more assertions with explanations.

---

How about the following?

`PriorityTestSample1#FirstTest` in thread1 concurrently with `PriorityTestSample2#FirstTest` in thread2
`PriorityTestSample1#SecondTest` in thread2 concurrently with `PriorityTestSample2#SecondTest` in thread1,
`PriorityTestSample1#ThridTest` in thread1 concurrently with `PriorityTestSample2#ThridTest` in thread2

All priorities are met, and affinity is broken.

**Comment by krmahadevan** [comment]
@vlsi - Like I said earlier, I can try to refactor the assertions such that what it asserts is more clear. 

> If you expect that all the methods in a single class must be executed within the same thread, then please assert exactly that. For instance, monitor Thread.currentThread() inside test methods and assert the thread does not vary from method to method.

This cannot be done in the test class which is what I am trying to explain. the actual test uses the TestNG API to run TestNG programmatically and then run assertions. So the actual assertions in terms of thread affinity need to be done outside of the sample test class and NOT within the test class.

> How about the following?
> 
> PriorityTestSample1#FirstTest in thread1 concurrently with PriorityTestSample2#FirstTest in thread2
> PriorityTestSample1#SecondTest in thread2 concurrently with PriorityTestSample2#SecondTest in thread1,
> PriorityTestSample1#ThridTest in thread1 concurrently with PriorityTestSample2#ThridTest in thread2
> 
> All priorities are met, and affinity is broken.

Like I said before, Not letting this happen is the intent of the thread affinity. I will think of adding some assertions that can better vet this out.

**Comment by vlsi** [comment]
>  NOT within the test class.

Why not?

**Comment by krmahadevan** [comment]
> > NOT within the test class.
> 
> Why not?

Because assertions on functionalities are supposed to happen in tests that run the TestNG APIs and NOT in the sample classes that the TestNG APIs work with. Thats the convention the codebase follows.

**Comment by vlsi** [comment]
Ok, then you could collect per-classs sets
