### ISSUE TITLE
DataProvider cannot be used with null values anymore

### ISSUE THREAD

**Issue by ickzon** [cbeust/testng#2559]
### TestNG Version
7.4.0 (still worked with 7.3.0)

### Expected behavior
A @DataProvider can be used to provided null values for any of the test method's arguments.

### Actual behavior
If the data contains any null value and log level is > 1, TestNG fails *after* successfully running the current test, aborting the whole suite:

```
java.lang.NullPointerException
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at org.testng.internal.Utils.extractParameterTypes(Utils.java:612)
	at org.testng.reporters.TextReporter.logResult(TextReporter.java:140)
	at org.testng.reporters.TextReporter.logResults(TextReporter.java:74)
	at org.testng.reporters.TextReporter.onFinish(TextReporter.java:34)
	at org.testng.TestRunner.fireEvent(TestRunner.java:923)
	at org.testng.TestRunner.afterRun(TestRunner.java:887)
	at org.testng.TestRunner.run(TestRunner.java:599)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
```

### Is the issue reproductible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample

```java
   @DataProvider( name = "name" )
   public Object[][] dp() {
      return new Object[][] { new Object[] { null } };
   }

   @Test( dataProvider = "name" )
   public void test( String arg ) {
   }
```

![Unbenannt](https://user-images.githubusercontent.com/39127621/119570362-4c7baf00-bdb0-11eb-8eef-77e882695682.jpg)

**Comment by bj-9527** [comment]
I ran your sample test, and I found it could work for now.

![image](https://user-images.githubusercontent.com/73265830/120170109-34ce7b80-c233-11eb-8f90-46b976d7b83d.png)

And I noticed that you are using JDK11, have you tried JDK8

**Comment by ickzon** [comment]
Strange! I tried with Java 8 and still get that NPE...
![image](https://user-images.githubusercontent.com/39127621/120172421-50ba2900-c203-11eb-97a7-91371f70231c.png)

**Comment by juherr** [comment]
Maybe a different behavior between IntelliJ and Eclipse.
Or a difference between running the test in TestNG project and outside.

@bj-9527 Could you try to reproduce the issue with Eclipse?

**Comment by bj-9527** [comment]
Hi, 
I tried again use Eclipse and outside TestNG project, and still got pass.
![image](https://user-images.githubusercontent.com/73265830/120193619-35750b00-c24f-11eb-9a1a-abbe036bbac6.png)
the eclipse version is 2020-06

**Comment by ickzon** [comment]
Strange! I originally got this error running tests via Ant (on different machines, different Ant versions, Linux/Windows) and was easily able to reproduce it in Eclipse so I assumed it to be a general problem, not related to the environment... Anyway, I'm glad you found a way to reproduce the issue!

**Comment by krmahadevan** [comment]
@ickzon - This issue is confirmed and I am able to reproduce this issue.

@bj-9527 Can you please try creating a TestNG suite xml file, set the verbose level to `2` and run again ? If you are running from within the IDE, make sure that you have turned on the default listeners of testng.

Suite file to reproduce
```
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
<suite name="ExcerciseSuiteA" verbose="2" preserve-order="false"
	configfailurepolicy="continue">
	<test name="TestA" verbose="2">
		<classes>
			<class
				name="com.rationaleemotions.github.issue2559.SampleTestClass" />
		</classes>
	</test>
</suite>
```

Here's how the run configuration should look like in IntelliJ

![image](https://user-images.githubusercontent.com/909773/120213796-458dea00-c251-11eb-9f9f-f221ec3ef898.png)

**Comment by krmahadevan** [comment]
@ickzon - It looks like this is no longer a problem in TestNG `7.5.0` (next upcoming release).

Please try using `7.5.0-SNAPSHOT` 

https://oss.sonatype.org/content/repositories/snapshots/org/testng/testng/7.5.0-SNAPSHOT/

Refere [here](https://stackoverflow.com/a/7717234) for info on how to consume a snapshot dependency.

**Comment by ickzon** [comment]
With testng-7.5.0-20210528.084226-28.jar I do no longer get this error. Thanks a lot!
