### ISSUE TITLE
Dataprovider only supporting a raw type for Iterator return type

### ISSUE THREAD

**Issue by GauthamM-official** [cbeust/testng#2565]
### TestNG Version
7.4.0
### Expected behavior
Return type like `Iterator<X<Y>>` should be supported for a data provider

### Actual behavior
Assume the below code:
```java
@DataProvider
public Iterator<Supplier<String>> data() {
    List<Supplier<String>> obj = new ArrayList<>();
    obj.add(() -> "hai");
    obj.add(() -> "bye");
    return obj.iterator();
}    
```
This produces the following exception:
```
java.lang.ClassCastException: class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to class java.lang.Class (sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl and java.lang.Class are in module java.base of loader 'bootstrap')
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:159)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:798)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	...............................
```
The below is causing issue when the actual type argument is also a parameterized type.
```java
//MethodInvocationHelper.invokeDataProvider
Class<?> type = (Class<?>) contentType.getActualTypeArguments()[0];
```
If I use raw `Iterator<Supplier>` instead of `Iterator<Supplier<String>>` then it would work without issues.

### Is the issue reproductible on runner?
- [x] Eclipse

### Test case sample
```java
@Test(dataProvider = "data")
public void testCase(Supplier<String> s) {
    System.out.println(s.get());
}

@DataProvider
public Iterator<Supplier<String>> data() {
    List<Supplier<String>> obj = new ArrayList<>();
    obj.add(() -> "hai");
    obj.add(() -> "bye");
    return obj.iterator();
}    
```

**Comment by bj-9527** [comment]
Hi, 

I copied your test sample, but I met issue below:
![image](https://user-images.githubusercontent.com/73265830/120167008-cf2cc000-c22f-11eb-9fed-0809a30624e0.png)
It seems that the return type is not same with declared.
![image](https://user-images.githubusercontent.com/73265830/120167136-f5526000-c22f-11eb-94be-284b8ef895a0.png)

**Comment by juherr** [comment]
@bj-9527 The return type should not be an issue but IntelliJ declares it as bad practice because it doesn't know that `Object[][]`, `Object[]` and `Object` are valid return types for a data provider method.
