### ISSUE TITLE
java.lang.IllegalArgumentException: wrong number of arguments

### ISSUE THREAD

**Issue by rajukthomas** [cbeust/testng#2604]
### TestNG Version
> Note: only the latest version is supported

### Expected behavior

Retry Test with RetryAnalyzer without errors. TESTNG version 
[RemoteTestNG] detected TestNG version 7.4.0
eg
@Test(retryAnalyzer = com.retry.FailureRetryAnalyzer.class, groups = { "P1" })
	public void isTopNavigationFailureWithCustomExceptionInTheBegin(Method m) throws Exception {

### Actual behavior
First Run of test completes the test with Fail. Retry fails with below error

java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Is the issue reproducible on a runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
![TESTNG](https://user-images.githubusercontent.com/31891966/122588271-8002cf80-d024-11eb-9477-8139bd782b77.png)

**Comment by bj-9527** [comment]
Could you please share the whole test case which could copy and paste.

**Comment by krmahadevan** [comment]
@rajukthomas - Please share a sample code for us to be able to reproduce the problem. If we dont hear back on this, we may have to close out this issue (we have to do this so that we exactly know which are the issues that need to be fixed).

**Comment by krmahadevan** [comment]
No response from user. Closing this issue. Please feel free to add a comment with a sample if the problem persists.
