### ISSUE TITLE
Unable to run the file in Test ng.

### ISSUE THREAD

**Issue by Anilprusty56** [cbeust/testng#2628]
### TestNG Version 7.4.0
> Note: only the latest version is supported

### Actual Code

```java
package org.cgg.api.base;

import org.testng.annotations.Test;

import files.payload;
import io.restassured.path.json.JsonPath;

public class SumValidation {
	//Verify if Sum of all Course prices matches with Purchase Amount
	@Test
	public void sumofCourses()
	{
		JsonPath js = new JsonPath(payload.courseprice());
		int coursecount = js.getInt("courses.size");
		for(int i=0;i<coursecount;i++)
		{
			int courseprice= js.get("courses["+i+"].price");
			int coursecopies= js.getInt("courses["+i+"].copies");
			int Sumofcourseprice = courseprice * coursecopies ;
			System.out.println(Sumofcourseprice);
		}
	
		
	}

}
```

### Issue Details

```
[RemoteTestNG] failed to get TestNG version from class: java.lang.IllegalArgumentException: invalid version "[WORKING]": non-numeric "[WORKING]"
[RemoteTestNG] now trying to parse the version from pom.properties
[RemoteTestNG] now trying to parse the version from MANIFEST.MF
[RemoteTestNG] parsing TestNG version at jar:file:///C:/Users/anil.p/Desktop/Anil/Eclipse/testng-7.4.0.jar!/META-INF/MANIFEST.MF
[RemoteTestNG] detected TestNG version 7.4.0
org.testng.TestNGException: 
Cannot instantiate class org.cgg.api.base.SumValidation
	at org.testng@7.4.0/org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:30)
	at org.testng@7.4.0/org.testng.internal.InstanceCreator.instantiateUsingDefaultConstructor(InstanceCreator.java:193)
	at org.testng@7.4.0/org.testng.internal.InstanceCreator.createInstanceUsingObjectFactory(InstanceCreator.java:113)
	at org.testng@7.4.0/org.testng.internal.InstanceCreator.createInstance(InstanceCreator.java:79)
	at org.testng@7.4.0/org.testng.internal.objects.SimpleObjectDispenser.dispense(SimpleObjectDispenser.java:25)
	at org.testng@7.4.0/org.testng.internal.objects.GuiceBasedObjectDispenser.dispense(GuiceBasedObjectDispenser.java:30)
	at org.testng@7.4.0/org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:112)
	at org.testng@7.4.0/org.testng.internal.ClassImpl.getInstances(ClassImpl.java:165)
	at org.testng@7.4.0/org.testng.TestClass.getInstances(TestClass.java:122)
	at org.testng@7.4.0/org.testng.TestClass.initTestClassesAndInstances(TestClass.java:102)
	at org.testng@7.4.0/org.testng.TestClass.init(TestClass.java:94)
	at org.testng@7.4.0/org.testng.TestClass.<init>(TestClass.java:59)
	at org.testng@7.4.0/org.testng.TestRunner.initMethods(TestRunner.java:463)
	at org.testng@7.4.0/org.testng.TestRunner.init(TestRunner.java:339)
	at org.testng@7.4.0/org.testng.TestRunner.init(TestRunner.java:292)
	at org.testng@7.4.0/org.testng.TestRunner.<init>(TestRunner.java:223)
	at org.testng.remote.support.RemoteTestNG6_12$1.newTestRunner(RemoteTestNG6_12.java:33)
	at org.testng.remote.support.RemoteTestNG6_12$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_12.java:66)
	at org.testng@7.4.0/org.testng.ITestRunnerFactory.newTestRunner(ITestRunnerFactory.java:55)
	at org.testng@7.4.0/org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:659)
	at org.testng@7.4.0/org.testng.SuiteRunner.init(SuiteRunner.java:173)
	at org.testng@7.4.0/org.testng.SuiteRunner.<init>(SuiteRunner.java:107)
	at org.testng@7.4.0/org.testng.TestNG.createSuiteRunner(TestNG.java:1300)
	at org.testng@7.4.0/org.testng.TestNG.createSuiteRunners(TestNG.java:1276)
	at org.testng@7.4.0/org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng@7.4.0/org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng@7.4.0/org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public org.cgg.api.base.SumValidation() accessible: module DemoProject does not "exports org.cgg.api.base" to module org.testng
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
	at org.testng@7.4.0/org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:22)
	... 29 more
```

### Is the issue reproductible on runner?
yes

- [ ] Maven

- [ ] Eclipse

### Test case sample
> Printing the Sumofcourseprice in the console

**Comment by krmahadevan** [comment]
@Anilprusty56 

> Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public org.cgg.api.base.SumValidation() accessible: module DemoProject does not "exports org.cgg.api.base" to module org.testng
	
This sounds like a problem in your test project and not related to TestNG. Am guessing that your project is using Java 11 and there are some [Java modules](http://tutorials.jenkov.com/java/modules.html) that perhaps is interfering? This is just a guess.

Not much that can be done from TestNG.
