### ISSUE TITLE
testResult.getThrowable() is null in IConfigurable.run when a test fails and if BeforeMethod is present

### ISSUE THREAD

**Issue by askfor** [cbeust/testng#2657]
### TestNG Version
7.4.0

### Expected behavior
testResult.getThrowable() should not be null when test fails. 

### Actual behavior
When a test has a BeforeMethod and the test fails, testResult.getThrowable() is null in IConfigurable.run 

### Is the issue reproducible on runner?

Maven

### Test case sample

```

import static org.testng.Assert.fail;

import org.testng.IConfigurable;
import org.testng.IConfigureCallBack;
import org.testng.ITestResult;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class ConfigurableTest implements IConfigurable {

    @Override
    public void run(IConfigureCallBack callBack, ITestResult testResult) {
        try {
            callBack.runConfigurationMethod(testResult);
            System.out.println(testResult.getThrowable() == null);
            System.out.println("finish");
        }catch (Exception e) {
            System.out.println("exception");
        }
    }

    @BeforeMethod
    public void setup() {

    }

    @Test
    public void test() {
        fail();
    }
}

```

The output is:

```
true
finish





java.lang.AssertionError: null

	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.fail(Assert.java:106)
	at ConfigurableTest.test(ConfigurableTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)


===============================================
Default Suite
Total tests run: 1, Passes: 0, Failures: 1, Skips: 0
===============================================


Process finished with exit code 0
```

**Comment by krmahadevan** [comment]
@askfor - I think that the sample test is incorrect. The configuration method in your sample does not throw any exceptions. So its `ITestResult` object would be null.

**Comment by krmahadevan** [comment]
Closing this issue since the sample is not correct and there has been no updates from @askfor regarding this.
