### ISSUE TITLE
TestNG detected TestNG version 7.4.0 error

### ISSUE THREAD

**Issue by mironb13** [cbeust/testng#2702]
I have this TestNG part 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite">
<listeners>
<listener class-name="ShufersalMiron.Sprod.Listeners"/>
</listeners>
<test name="Test1">
<classes>
<class name="ShufersalMiron.Sprod.PA_Coupons"/>
</classes>
</test> <!-- Test -->
<test  name="Test2">
<classes>
<class name="ShufersalMiron.Sprod.PA_SupermeCoins"/>
</classes>
</test> <!-- Test -->
</suite> <!-- Suite -->
```
When I am trying to run it as a suite I get this error :

```
[RemoteTestNG] detected TestNG version 7.4.0
java.lang.NoClassDefFoundError: io/reactivex/rxjava3/core/Observer
	at resources.ExtentReporterNG.getReportObject(ExtentReporterNG.java:14)
	at ShufersalMiron.Sprod.Listeners.<init>(Listeners.java:22)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350)
	at java.base/java.lang.Class.newInstance(Class.java:645)
	at org.testng.internal.InstanceCreator.newInstance(InstanceCreator.java:30)
	at org.testng.TestNG.addListeners(TestNG.java:964)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:924)
	at org.testng.TestNG.initializeEverything(TestNG.java:1012)
	at org.testng.remote.support.RemoteTestNG6_12.initialize(RemoteTestNG6_12.java:22)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:98)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ClassNotFoundException: io.reactivex.rxjava3.core.Observer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

Can someone please tell me what could be wrong and how to solve it please ?

Thanks.

**Comment by krmahadevan** [comment]
The line

> java.lang.NoClassDefFoundError: io/reactivex/rxjava3/core/Observer
>	at resources.ExtentReporterNG.getReportObject(ExtentReporterNG.java:14)

is suggesting that you are dealing with a messed up classpath and TestNG does not have anything to do with this.

You may have to add an appropriate version dependency from here https://mvnrepository.com/artifact/io.reactivex.rxjava2/rxjava

**Comment by krmahadevan** [comment]
Please feel free to use the TestNG user forums for questions https://groups.google.com/g/testng-users

We would like to keep github issues restricted to actual defects/feature requests.
