### ISSUE TITLE
Skipped tests showing incorrect testnames

### ISSUE THREAD

**Issue by skhandekar1** [cbeust/testng#2707]
### TestNG Version
7.4.0

### Expected behavior
The testnames should be properly displayed for skipped tests in onTestSkipped() in listener

### Actual behavior
The testnames for all skipped tests showing up as same as failed dependent test that caused the skips

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
The beforeMethod in my baseClass is where I set the testname. The beforeMethod(alwaysRun=true) is not running for skipped test. So testname never gets updated for skipped tests. As a workaround I added the result.getName() inside onTestSkipped() in listener. But that is also fetching the failed test name. PLease help. How do I get the correct testname for the skipped test?

Before Method code from baseClass:

```
@BeforeMethod(alwaysRun=true)
	public void setUpTest(Method method, Object[] testData, ITestContext ctx) {	
		log.info("BeforeMethod from NaluTestSection");
		try {
			Map<String,String> map = new HashMap<String,String>();
			
			 //Updates names of testcases that use DataProviders
			if (testData.length > 0) {
				 //Code used for dataproviders from excel sheets that contain TestID
				String[] entries = testData[0].toString().split(",");
				if(entries.length>1) {
					for(String entry:entries) {
						map.put(entry.split("=")[0].trim(), entry.split("=")[1].trim());
					}
					
					testName.set(method.getName() + "_" + map.get("TestID"));
					ctx.setAttribute("testName", method.getName() + "_" + map.get("TestID"));
				}
				else {
					//Code used for dataproviders that have single entry and no TestID's, viz create_patient
					testName.set(method.getName() + "_" + testData[0].toString());
				    ctx.setAttribute("testName", method.getName() + "_" + testData[0].toString());
				}
			 } else {
				 testName.set(method.getName());
				 ctx.setAttribute("testName", method.getName());
			 }
```

Listener code:

```
	public void onTestSkipped(ITestResult result) {	
		log.debug("Test skipped");
		resultWriter.appendTestCaseResultToCSV(TP397_Constants.testCaseResult_FAIL);		
		
		String message="";
		Class<?> errorCause = null;
	
		//Figure out the cause/location for test skip and log it
		log.info("***Result throwable: " + result.getThrowable());
		for(ITestResult r:result.getTestContext().getSkippedConfigurations().getAllResults()) {
			if(result.getThrowable().getClass()!=null) {
				errorCause = result.getThrowable().getClass();
				
			}
			if(r.getSkipCausedBy().get(0).isBeforeClassConfiguration()) {
				message = "skipped due to failure in 'BeforeClass' configuration - " + errorCause.toString();
			}else if(r.getSkipCausedBy().get(0).isBeforeMethodConfiguration()) {
				message = "skipped due to failure in 'BeforeMethod' configuration - " + errorCause.toString();
			}else if(r.getSkipCausedBy().get(0).isBeforeSuiteConfiguration()) {
				message = "skipped due to failure in 'BeforeSuite' configuration - " + errorCause.toString();
			}else if(r.getSkipCausedBy().get(0).isBeforeTestConfiguration()) {
				message = "skipped due to failure in 'BeforeTest' configuration - " + errorCause.toString();
			}else{
				message = "skipped due to failure  - " + errorCause.toString();
			}
			
		}
		
		if(message!="") {
			log.error("\n***********************************************************************************************************************************\n"
				+ "Test Name - {} {} \n {}\n***********************************************************************************************************************************\n", result.getName(), message, result.getThrowable().getMessage());
		}else
			log.error("\n***********************************************************************************************************************************\n"
					+ "Test Name - {} skipped \n{} \n***********************************************************************************************************************************\n", result.getName(), result.getThrowable());
		System.out.println();
		result.getThrowable().printStackTrace();
	}

```

Also another question is, how do I pass the threadLocal testName created in baseClass to the listeners?

**Comment by krmahadevan** [comment]
@skhandekar1 - For TestNG questions, request you to please use the [TestNG forums](https://groups.google.com/g/testng-users) and not the github issues. We would like to confine the issues page to actual problems (which from your issue doesn't seem to be the case)

> Also another question is, how do I pass the threadLocal testName created in baseClass to the listeners?
You can't because they are NOT guaranteed to run on the same thread. You should perhaps try to leverage the `setAttribute()` on the `ITestResult` object to be able to safely share data across different aspects of your testng project.

**Note:** The latest released version of TestNG is `7.5`


Here's a sample that shows how to fudge the test name.

```java
import java.util.List;
import java.util.stream.Stream;
import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener;
import org.testng.IReporter;
import org.testng.ISuite;
import org.testng.ISuiteResult;
import org.testng.ITestResult;
import org.testng.xml.XmlSuite;

public class NameChanger implements IInvokedMethodListener, IReporter {

  @Override
  public void afterInvocation(IInvokedMethod method, ITestResult testResult) {
    if (testResult.getStatus() == ITestResult.SKIP) {
      testResult.setTestName(testResult.getName() + "_SKIPPED");
    }
  }

  @Override
  public void generateReport(List<XmlSuite> xmlSuites, List<ISuite> suites,
      String outputDirectory) {
    suites.stream()
        .flatMap(each -> each.getResults().values().stream())
        .map(ISuiteResult::getTestContext)
        .flatMap(each -> Stream.concat(each.getFailedTests().getAllResults().stream(),
            each.getSkippedTests().getAllResults().stream()))
        .forEach(each -> System.err.println("Test Name = " + each.getName()));
  }
}
```

Here's the test class

```java
import org.testng.Assert;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

@Listeners(NameChanger.class)
public class TestClassSample {

  @Test
  public void primaryMethod() {
    System.err.println("Primary Method is about to fail");
    Assert.fail();
  }

  @Test(dependsOnMethods = "primaryMethod")
  public void secondaryMethod() {
    System.err.println("Secondary Method");
  }
}
```
 
Here's the output

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Primary Method is about to fail

java.lang.AssertionError: null

	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.fail(Assert.java:115)
	at com.rationaleemotions.issue2707.TestClassSample.primaryMethod(TestClassSample.java:13)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)


Test ignored.

===============================================
Default Suite
Total tests run: 2, Passes: 0, Failures: 1, Skips: 1
===============================================

Test Name = primaryMethod
Test Name = secondaryMethod_SKIPPED

Process finished with exit code 0

```
