### ISSUE TITLE
Is my logic to get the skip reason correct

### ISSUE THREAD

**Issue by skhandekar1** [cbeust/testng#2708]
### TestNG Version
7.4.0

### Expected behavior
Skip test should show reason for failure even if failure is in a configuration method

### Actual behavior
Not sure if my logic to obtain skip reason is correct

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
My skipped test logic in listener is as below. Can someone help me know if the logic i am using is correct or am I overcomplicating the code?

```
	public void onTestSkipped(ITestResult result) {	
		log.debug("Test skipped");
		resultWriter.appendTestCaseResultToCSV(TP397_Constants.testCaseResult_FAIL);		
		
		String message="";
		Class<?> errorCause = null;
	
		//Figure out the cause/location for test skip and log it
		log.info("***Result throwable: " + result.getThrowable());
		for(ITestResult r:result.getTestContext().getSkippedConfigurations().getAllResults()) {
			if(result.getThrowable().getClass()!=null) {
				errorCause = result.getThrowable().getClass();
				
			}
			if(r.getSkipCausedBy().get(0).isBeforeClassConfiguration()) {
				message = "skipped due to failure in 'BeforeClass' configuration - " + errorCause.toString();
			}else if(r.getSkipCausedBy().get(0).isBeforeMethodConfiguration()) {
				message = "skipped due to failure in 'BeforeMethod' configuration - " + errorCause.toString();
			}else if(r.getSkipCausedBy().get(0).isBeforeSuiteConfiguration()) {
				message = "skipped due to failure in 'BeforeSuite' configuration - " + errorCause.toString();
			}else if(r.getSkipCausedBy().get(0).isBeforeTestConfiguration()) {
				message = "skipped due to failure in 'BeforeTest' configuration - " + errorCause.toString();
			}else{
				message = "skipped due to failure  - " + errorCause.toString();
			}
			
		}
		
		if(message!="") {
			log.error("\n***********************************************************************************************************************************\n"
				+ "Test Name - {} {} \n {}\n***********************************************************************************************************************************\n", result.getName(), message, result.getThrowable().getMessage());
		}else
			log.error("\n***********************************************************************************************************************************\n"
					+ "Test Name - {} skipped \n{} \n***********************************************************************************************************************************\n", result.getName(), result.getThrowable());
		System.out.println();
		result.getThrowable().printStackTrace();
	}
```

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
The below sample should show how to get this done using TestNG `7.5` (which is the latest released version).

```java
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

@Listeners(NameChanger.class)
public class TestClassSample {
  @BeforeClass
  public void beforeClass() {
    Assert.fail("Simulating a failure");
  }

  @Test
  public void primaryMethod() {
    System.err.println("Primary Method is about to fail");
    Assert.fail();
  }

  @Test(dependsOnMethods = "primaryMethod")
  public void secondaryMethod() {
    System.err.println("Secondary Method");
  }
}
```

Here's the listener

```java
import java.util.List;
import org.testng.IInvokedMethod;
import org.testng.IInvokedMethodListener;
import org.testng.ITestListener;
import org.testng.ITestNGMethod;
import org.testng.ITestResult;

public class NameChanger implements IInvokedMethodListener, ITestListener {

  @Override
  public void afterInvocation(IInvokedMethod method, ITestResult testResult) {
    if (testResult.getStatus() == ITestResult.SKIP) {
      testResult.setTestName(testResult.getName() + "_SKIPPED");
    }
  }

  @Override
  public void onTestSkipped(ITestResult result) {
    System.err.println("Skipped Test Name = " + result.getName() + " and was skipped due to "
        + causedBy(result.getSkipCausedBy()));
  }

  private static String causedBy(List<ITestNGMethod> methods) {
    StringBuilder builder = new StringBuilder();
    methods.forEach(each -> {
      builder.append("[").append(each.getQualifiedName()).append("]")
          .append(" which is a ");
      if (each.isTest()) {
        builder.append(" test");
      } else {
        builder.append(" configuration");
      }
      builder.append(" Method.").append("\n");
    });
    return builder.toString();
  }
}
```

Here's the output

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

java.lang.AssertionError: Simulating a failure

	at org.testng.Assert.fail(Assert.java:110)
	at com.rationaleemotions.issue2707.TestClassSample.beforeClass(TestClassSample.java:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)


Test ignored.
Skipped Test Name = primaryMethod_SKIPPED and was skipped due to [com.rationaleemotions.issue2707.TestClassSample.beforeClass] which is a  configuration Method.

Skipped Test Name = secondaryMethod_SKIPPED and was skipped due to [com.rationaleemotions.issue2707.TestClassSample.beforeClass] which is a  configuration Method.


Test ignored.

===============================================
Default Suite
Total tests run: 2, Passes: 0, Failures: 0, Skips: 2
Configuration Failures: 1, Skips: 0
===============================================

Test Name = secondaryMethod_SKIPPED
It was skipped due to [com.rationaleemotions.issue2707.TestClassSample.beforeClass] which is a  configuration Method.

Test Name = primaryMethod_SKIPPED
It was skipped due to [com.rationaleemotions.issue2707.TestClassSample.beforeClass] which is a  configuration Method.


Process finished with exit code 0
```
