### ISSUE TITLE
TestNGException Error

### ISSUE THREAD

**Issue by oshodiab** [cbeust/testng#2740]
### TestNG Version
> Note: only the latest version is supported

```
<groupId>org.testng</groupId>
<artifactId>testng</artifactId>
<version>6.14.3</version>
```

### Expected behavior

Expect the test to run by getting values from an excel file to login 

### Actual behavior

```
1647380062109	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\habib\\AppData\\Local\\Temp\\rust_mozprofile.SGkDbAExlndb"
1647380094285	Marionette	INFO	Marionette enabled

org.openqa.selenium.WebDriverException: connection refused
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'HABIB-PC', ip: '192.168.0.47', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_40'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.W3CHandshakeResponse$$Lambda$219/16175550.apply(Unknown Source)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.HandshakeResponse$$Lambda$214/17818746.apply(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake$$Lambda$215/13348802.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at com.Interbanking.testCases.BasePage.setup(BasePage.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

[Utils] [ERROR] [Error] org.testng.TestNGException: 
Some DataProvider java.lang.Object[][] com.Interbanking.testCases.TC_LoginTestDDT_02.getData(java.lang.String) throws java.io.IOException parameters unresolved:  at 0 type class java.lang.String

	at org.testng.internal.MethodInvocationHelper.getParameters(MethodInvocationHelper.java:197)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:130)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)


org.testng.TestNGException: 
Some DataProvider java.lang.Object[][] com.Interbanking.testCases.TC_LoginTestDDT_02.getData(java.lang.String) throws java.io.IOException parameters unresolved:  at 0 type class java.lang.String



===============================================
Default Suite
Total tests run: 1, Failures: 1, Skips: 0
Configuration Failures: 1, Skips: 1
===============================================


Process finished with exit code 0

```

### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

```
package com.Interbanking.testCases;

import java.io.IOException;
import com.Interbanking.pageObjects.LoginPage;
import com.Interbanking.utilities.XLUtils;
import org.openqa.selenium.NoAlertPresentException;
import org.testng.Assert;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;



public class TC_LoginTestDDT_02 extends BasePage {


    @Test(dataProvider="Logindata")
    public void LoginDDT(String user,String pwd) throws InterruptedException

    {
        LoginPage lp=new LoginPage(driver);
        lp.setUserName(user);
        logger.info("user name provided ");
        lp.setPassword(pwd);
        logger.info("password provided ");
        lp.clickSubmit();

        Thread.sleep(3000);


        if(isAlertPresent()==true)
        {
           driver.switchTo().alert().accept();
           driver.switchTo().defaultContent();
            Assert.assertTrue(false);
            logger.warn("Login failed ");
        }

        //Thread.sleep(3000);

        else {

            Assert.assertTrue(true);
            logger.info("Login passed ");
            lp.clickLog0ut();
            Thread.sleep(3000);
            driver.switchTo().alert().accept();
            driver.switchTo().defaultContent();

        }
    }


    public boolean isAlertPresent()//user defined method to check alert

    {
       try {
           driver.switchTo().alert();
           return true;
       }
       catch (NoAlertPresentException e)
       {
           return false;
       }
    }


    @DataProvider(name = "Logindata")
    Object[][] getData(String path) throws IOException
    {
        path = System.getProperty("user.dir") + "/src/test/java/com/Interbanking/testData/Logindata.xlsx";

        int rownum = XLUtils.getRowCount(path, "sheet1");
        int colcount = XLUtils.getCellCount(path, "sheet1", 1);

        String LoginData[][] = new String[rownum][colcount];


        for (int i = 1; i <= rownum; i++) {
            for (int j = 0; j <= colcount; j++) {
                LoginData[i - 1][j] = XLUtils.getCellData(path, "Sheet1", i, j);
            }
        }

     return LoginData;
    }


}
```

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment]
There is nothing in this issue that suggests that this is a TestNG issue. 

Please check your data provider and ensure that it returns two values for every iteration ( which i believe is what the error is suggesting as well )

Also please ensure that you use testng 7.5 ( latest released version as of today )
