### ISSUE TITLE
Critical: Parallel run by methods and exception in @AfterMethod results in some next tests not being executed at all

### ISSUE THREAD

**Issue by mstrahinski** [cbeust/testng#2782]
### TestNG Version
Latest TestNG up to today - 7.6.1
Latest maven-surefire-plugin up to today - 3.0.0-M7

### Expected behavior

Even though in @AfterMethod an exception has been thrown that should not be a reason for some of the next tests that are supposed to be run to be ignored, only the @BeforeMethod and @AfterMethod is run again, however the test itself is being ignored and not run.

### Actual behavior

When you run in parallel(lets say 4 threads) by methods and you have a RuntimeException thrown in @AfterMethod for whatever reason, some of the tests are NOT being run at all, however their @BeforeMethod and @AfterMethod is run, but the test itself is NOT, and this happens randomly also for any next tests before which in the @AfterMethod in the previous test an exception was thrown for whatever reason.

In other words the classes have 20 tests that are absolutely the same and they print the name of the test that is being run, however in the output you will see only 16 of them being printed, the other 4 were not run at all because of the parallel execution and due to the fact that an exception is thrown in @AfterMethod for whatever reason.

EDIT(Quick Update): Just checked it even with a single thread if an exception is thrown in the @AfterMethod it ignores to System.out.println() most of the next tests, i.e. the body of the methods not being executed, but their @BeforeMethod and @AfterMethod are being called.

### Is the issue reproducible on runner?

- [ ] Shell
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [x] IntelliJ
- [ ] NetBeans

### Test case sample
I have prepared a really small project that shows the issue, in order to check it just follow the steps:

0) Precondition: You should have Maven on your computer and the PATH configured to it.
1) Clone in IntelliJ that repo - https://github.com/mstrahinski/testng-parallel-aftermethod-issue 
2) Click on the "Terminal" tab at the bottom of your IntelliJ 
3) Type in the directory of your project in the command line: 
      mvn clean test -Dgroups="issue" -Dparallel="methods" -DthreadCount=4

and you will observe the behavior that after it runs the first 4 tests(i.e. uses all 4 threads) in parallel, the first test that is supposed to be run as 5th one has the @BeforeMethod and @AfterMethod executed however the test itself is NOT, i.e. the System.out.println() you are supposed to see is NOT seen at all, i.e. the test is not executed at all(only its @BeforeMethod and @AfterMethod) and all this is caused by the fact that some exception is being thrown in @AfterMethod of the previous test for whatever reason.

You will see also the same behavior happen for some of the subsequent tests also, some tests are being run, some are not being run and only their @BeforeMethod and @AfterMethod is always run.

An example output of the run with the command above looks like as shown below, where every tests is supposed to print "Test TEST_NAME", however you will see for example the text "Test test5" is not shown anywhere, but the @BeforeMethod and @AfterMethod that says STARTING TEST and ENDING TEST is being executed:

``` [INFO] -------------------------------------------------------
[INFO]  T E S T S                                             
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation   
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert1Test.test1
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert1Test.test4
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert1Test.test3
-----------------------------------------------------------------
Test test4
Test test3
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert1Test.test2
-----------------------------------------------------------------
Test test2
Test test1
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert1Test.test4
-----------------------------------------------------------------
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert1Test.test3
-----------------------------------------------------------------
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert2Test.test11
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert1Test.test5
-----------------------------------------------------------------
Test test11
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert1Test.test5
-----------------------------------------------------------------
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert1Test.test1
-----------------------------------------------------------------
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert1Test.test2
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert2Test.test22
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert2Test.test33
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert2Test.test44
-----------------------------------------------------------------
Test test44
Test test22
Test test33
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert2Test.test11
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert2Test.test55
-----------------------------------------------------------------
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert2Test.test55
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert3Test.test111
-----------------------------------------------------------------
Test test111
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert2Test.test33
-----------------------------------------------------------------
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert2Test.test22
-----------------------------------------------------------------
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert2Test.test44
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert3Test.test444
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert3Test.test333
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert3Test.test222
-----------------------------------------------------------------
Test test222
Test test444
Test test333
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert3Test.test111
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert3Test.test555
-----------------------------------------------------------------
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert3Test.test555
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert4Test.test1111
-----------------------------------------------------------------
Test test1111
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert3Test.test444
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert4Test.test2222
-----------------------------------------------------------------
Test test2222
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert3Test.test222
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert4Test.test3333
-----------------------------------------------------------------
Test test3333
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert3Test.test333
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert4Test.test4444
-----------------------------------------------------------------
Test test4444
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert4Test.test1111
-----------------------------------------------------------------
-----------------------------------------------------------------
STARTING TEST --> TestingSoftAssert4Test.test5555
-----------------------------------------------------------------
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert4Test.test5555
-----------------------------------------------------------------
-----------------------------------------------------------------
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert4Test.test2222
ENDING TEST --> TestingSoftAssert4Test.test3333
-----------------------------------------------------------------
-----------------------------------------------------------------
-----------------------------------------------------------------
ENDING TEST --> TestingSoftAssert4Test.test4444
----------------------------------------------------------------- ```

**Comment by krmahadevan** [comment]
@mstrahinski - TestNG is working as designed here. You should be setting the attribute `configfailurepolicy="continue"` at the `<suite>` level.

Here's a sample

<details>
<summary>Base class</summary>

```java
import java.lang.reflect.Method;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CopyOnWriteArrayList;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;

public abstract class BaseWebTest {

    public static class Key {
        String clazz;
        int hashCode;

        public Key(String clazz, int hashCode) {
            this.clazz = clazz;
            this.hashCode = hashCode;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) {
                return true;
            }
            if (o == null || getClass() != o.getClass()) {
                return false;
            }
            Key key = (Key) o;
            return hashCode == key.hashCode && Objects.equals(clazz, key.clazz);
        }

        @Override
        public int hashCode() {
            return Objects.hash(clazz, hashCode);
        }

        @Override
        public String toString() {
            return "{" +
                "clazz='" + clazz + '\'' +
                ", hashCode=" + hashCode +
                '}';
        }
    }

  public static final Map<Key, List<String>> logs = new ConcurrentHashMap<>();

  public BaseWebTest() {
    logs.computeIfAbsent(getKey(), k -> new CopyOnWriteArrayList<>());
  }

  protected Key getKey() {
      return new Key(getClass().getSimpleName(), hashCode());
  }

  @BeforeMethod(alwaysRun = true)
  public void beforeEachTest(Method method) {
    logs.get(getKey()).add("beforeMethod_" + method.getName());
  }

  @AfterMethod(alwaysRun = true)
  public void afterEachTest(Method method) {
    logs.get(getKey()).add("afterMethod_" + method.getName());
    throw new RuntimeException("For whatever reason.");
  }
}
```
</details>

<details>
<summary>One of the test class looks like below</summary>

```java
package samples;

import org.testng.annotations.Test;

public class TestingSoftAssert1Test extends BaseWebTest {

    @Test(groups = "issue")
    public void test1() throws InterruptedException {
        logs.get(getKey()).add("test1");
        Thread.sleep(5000);
    }

    @Test(groups = "issue")
    public void test2() throws InterruptedException {
        logs.get(getKey()).add("test2");
        Thread.sleep(5000);
    }

    @Test(groups = "issue")
    public void test3() throws InterruptedException {
        logs.get(getKey()).add("test3");
        Thread.sleep(5000);
    }

    @Test(groups = "issue")
    public void test4() throws InterruptedException {
        logs.get(getKey()).add("test4");
        Thread.sleep(5000);
    }

    @Test(groups = "issue")
    public void test5() throws InterruptedException {
        logs.get(getKey()).add("test5");
        Thread.sleep(5000);
    }
}
```
</details>

<details>
<summary>Test Runner class</summary>

```java
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import org.testng.Assert;
import org.testng.TestNG;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlGroups;
import org.testng.xml.XmlRun;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlSuite.FailurePolicy;
import org.testng.xml.XmlTest;
import samples.BaseWebTest;
import samples.TestingSoftAssert1Test;
import samples.TestingSoftAssert2Test;
import samples.TestingSoftAssert3Test;
import samples.TestingSoftAssert4Test;

public class TestRunner {

  public static void main(String[] args) {
    runTestWithConfigFailurePolicyEnabled();
    runTestWithConfigFailurePolicyDisabled();
  }
  

  private static void runTestWithConfigFailurePolicyEnabled() {
    runTest(true);
  }

  private static void runTestWithConfigFailurePolicyDisabled() {
    runTest(false);
  }

  private static void runTest(boolean useConfigFailurePolicy) {
    TestNG testng = new TestNG();
    XmlSuite xmlsuite = create(useConfigFailurePolicy);
    testng.setXmlSuites(Collections.singletonList(xmlsuite));
    testng.run();
    long size = BaseWebTest.logs.values().stream()
        .mapToLong(Collection::size).sum();
    Assert.assertEquals(size, 60, xmlsuite.getName());
    BaseWebTest.logs.clear();
  }

  private static XmlSuite create(boolean useConfigFailurePolicy) {
    XmlSuite xmlSuite = new XmlSuite();
    if (useConfigFailurePolicy) {
      xmlSuite.setConfigFailurePolicy(FailurePolicy.CONTINUE);
    }
    xmlSuite.setThreadCount(2);
    xmlSuite.setName("Suite_With_Config_Failure_Policy_" + useConfigFailurePolicy);
    XmlTest xmlTest = new XmlTest(xmlSuite);
    xmlTest.setName("Test_With_Config_Failure_Policy_" + useConfigFailurePolicy);
    XmlGroups xmlGroups = new XmlGroups();
    XmlRun xmlRun = new XmlRun();
    xmlRun.onInclude("issue");
    xmlGroups.setRun(xmlRun);
    xmlTest.setGroups(xmlGroups);
    xmlTest.setXmlClasses(
        Arrays.asList(
            new XmlClass(TestingSoftAssert1Test.class),
            new XmlClass(TestingSoftAssert2Test.class),
            new XmlClass(TestingSoftAssert3Test.class),
            new XmlClass(TestingSoftAssert4Test.class)
        )
    );
    System.err.println("Running Suite: " + xmlSuite.getName());
    System.err.println(xmlSuite.toXml());
    return xmlSuite;
  }
}
```
</details>

<details>
<summary>console output</summary>

```bash
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Running Suite: Suite_With_Config_Failure_Policy_true
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite configfailurepolicy="continue" thread-count="2" name="Suite_With_Config_Failure_Policy_true">
  <test thread-count="2" name="Test_With_Config_Failure_Policy_true">
    <groups>
      <run>
        <include name="issue"/>
      </run>
    </groups>
    <classes>
      <class name="samples.TestingSoftAssert1Test"/>
      <class name="samples.TestingSoftAssert2Test"/>
      <class name="samples.TestingSoftAssert3Test"/>
      <class name="samples.TestingSoftAssert4Test"/>
    </classes>
  </test> <!-- Test_With_Config_Failure_Policy_true -->
</suite> <!-- Suite_With_Config_Failure_Policy_true -->


===============================================
Suite_With_Config_Failure_Policy_true
Total tests run: 20, Passes: 20, Failures: 0, Skips: 0
Configuration Failures: 20, Skips: 0
===============================================

Running Suite: Suite_With_Config_Failure_Policy_false
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="2" name="Suite_With_Config_Failure_Policy_false">
  <test thread-count="2" name="Test_With_Config_Failure_Policy_false">
    <groups>
      <run>
        <include name="issue"/>
      </run>
    </groups>
    <classes>
      <class name="samples.TestingSoftAssert1Test"/>
      <class name="samples.TestingSoftAssert2Test"/>
      <class name="samples.TestingSoftAssert3Test"/>
      <class name="samples.TestingSoftAssert4Test"/>
    </classes>
  </test> <!-- Test_With_Config_Failure_Policy_false -->
</suite> <!-- Suite_With_Config_Failure_Policy_false -->


===============================================
Suite_With_Config_Failure_Policy_false
Total tests run: 20, Passes: 4, Failures: 0, Skips: 16
Configuration Failures: 20, Skips: 0
===============================================

Exception in thread "main" java.lang.AssertionError: Suite_With_Config_Failure_Policy_false expected [60] but found [44]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotEquals(Assert.java:1413)
	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
	at org.testng.Assert.assertEquals(Assert.java:131)
	at org.testng.Assert.assertEquals(Assert.java:911)
	at run.TestRunner.runTest(TestRunner.java:43)
	at run.TestRunner.runTestWithConfigFailurePolicyDisabled(TestRunner.java:33)
	at run.TestRunner.main(TestRunner.java:24)

Process finished with exit code 1
```

**Comment by mstrahinski** [comment]
@krmahadevan good point, thank you. It's exactly working as expected when set to "continue" and not the default "skip" 

Just small addition for the people that think how they can set that if they are using Maven and Surefire plugin, you can simply put:

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M7</version>
                <configuration>
                    <testFailureIgnore>false</testFailureIgnore>
                    <properties>
                        <property>
                            <name>configfailurepolicy</name>
                            <value>continue</value>
                        </property>
                    </properties>
                </configuration>
            </plugin>

and that will change it on TestNG during execution with Maven command in Jenkins for example.
