### ISSUE TITLE
Facing this issue while running testnG class

### ISSUE THREAD

**Issue by mrinalinitiwari** [cbeust/testng#2930]
Console Error

[RemoteTestNG] detected TestNG version 7.8.0
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.testng.log4testng.Logger.lambda$getLogger$0(Logger.java:30)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.testng.log4testng.Logger.getLogger(Logger.java:30)
	at org.testng.TestNG.<clinit>(TestNG.java:113)
	at org.testng.remote.support.RemoteTestNGFactory7_8.createRemoteTestNG(RemoteTestNGFactory7_8.java:16)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:67)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 6 more

**Comment by juherr** [comment]
Slf4j is missing from your classpath.
Just add it.

Please share a full and runnable sample if you want more help.
