### ISSUE TITLE
Failure in junit runner does not fail build

### ISSUE THREAD

**Issue by krosenvold** [cbeust/testng#311]
http://jira.codehaus.org/browse/SUREFIRE-931 has two components to it. One is a bug in surefire (which has been fixed in 2.13-SNAPSHOT), but this is really just a secondary bug, the real bug being shown by this stacktrace:

Failure in JUnit mode for class com.mycompany.testfailed.AppTest: could not create/run JUnit test suite: null
        at org.testng.junit.JUnitTestRunner.runFailed(JUnitTestRunner.java:274)
Listening for transport dt_socket at address: 5005
        at org.testng.junit.JUnitTestRunner.start(JUnitTestRunner.java:267)
        at org.testng.junit.JUnitTestRunner.run(JUnitTestRunner.java:248)
        at org.testng.TestRunner$1.run(TestRunner.java:682)
        at org.testng.TestRunner.runWorkers(TestRunner.java:1012)
        at org.testng.TestRunner.privateRunJUnit(TestRunner.java:713)
        at org.testng.TestRunner.run(TestRunner.java:614)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
        at org.testng.SuiteRunner.run(SuiteRunner.java:240)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
        at org.testng.TestNG.run(TestNG.java:1031)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:126)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:117)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:158)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 91.309 sec

This whole exception is swallowed in TestRunner line 685 with a nice printStackTrace. The problem is that the build does not fail, only runs zero tests.

There is a sample project in surefire-integration-tests\src\test\resources\surefire-931-provider-failure if you need it.

**Comment by krmahadevan** [comment]
Tried reproducing this using TestNG `6.14.3` and surefire plugin version `2.19.1`. Unable to reproduce the issue.

Build fails.

**Test class**
```java
package com.rationaleemotions.github.issue1405;

import org.junit.Test;

public class JUnitTest {
  @Test
  public void testMethod() {
    System.out.println("testMethod() invoked");
    throw new RuntimeException("Simulating a failure");
  }
}
```

**Suite xml**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="1405_Suite" junit="true" verbose="3">
    <test name="1405_test" >
        <classes>
            <class name="com.rationaleemotions.github.issue1405.JUnitTest"/>
        </classes>
    </test>
</suite>

```

**Command line output**

```bash
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ testbed ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
...
... TestNG 6.14.3 by Cédric Beust (cedric@beust.com)
...

testMethod() invoked
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.435 sec <<< FAILURE! - in TestSuite
testMethod on testMethod(com.rationaleemotions.github.issue1405.JUnitTest)(com.rationaleemotions.github.issue1405.JUnitTest)  Time elapsed: 0.009 sec  <<< FAILURE!
java.lang.RuntimeException: Simulating a failure
	at com.rationaleemotions.github.issue1405.JUnitTest.testMethod(JUnitTest.java:9)


Results :

Failed tests:
  JUnitTest.testMethod:9 Runtime Simulating a failure

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.556 s
[INFO] Finished at: 2018-05-27T11:23:15+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project testbed: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/krmahadevan/githome/PlayGround/testbed/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
