### ISSUE TITLE
NPE when test parameter return null on toString()

### ISSUE THREAD

**Issue by Eckaaaaaat** [cbeust/testng#366]
Hi,

when I use a data provider for calling a test method and an returned object returns null when its toString() method is called I'll receive a NPE with the following stacktrace.

```
TestNG] Reporter org.testng.reporters.XMLReporter@35b220a3 failed
java.lang.NullPointerException
    at org.testng.reporters.XMLStringBuffer.addCDATA(XMLStringBuffer.java:297)
    at org.testng.reporters.XMLSuiteResultWriter.addParameter(XMLSuiteResultWriter.java:266)
    at org.testng.reporters.XMLSuiteResultWriter.addTestMethodParams(XMLSuiteResultWriter.java:250)
    at org.testng.reporters.XMLSuiteResultWriter.addTestResult(XMLSuiteResultWriter.java:154)
    at org.testng.reporters.XMLSuiteResultWriter.addTestResults(XMLSuiteResultWriter.java:130)
    at org.testng.reporters.XMLSuiteResultWriter.writeAllToBuffer(XMLSuiteResultWriter.java:74)
    at org.testng.reporters.XMLSuiteResultWriter.writeSuiteResult(XMLSuiteResultWriter.java:52)
    at org.testng.reporters.XMLReporter.writeSuiteToBuffer(XMLReporter.java:120)
    at org.testng.reporters.XMLReporter.writeSuite(XMLReporter.java:86)
    at org.testng.reporters.XMLReporter.generateReport(XMLReporter.java:63)
    at org.testng.TestNG.generateReports(TestNG.java:1115)
    at org.testng.TestNG.run(TestNG.java:1074)
    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
```

The problem results from the line 

```
xmlBuffer.addCDATA(parameter.toString());
```

of XMLSuiteResultWriter. The parameter was a mocked object. The workaround is to provide toString() also. This behavior might already be documented but I didn't found.

EDIT: I'm using version 6.8.1

Greetings
Eck

**Comment by juherr** [comment]
Fixed by #367
