### ISSUE TITLE
FWK005 parse may not be called while parsing

### ISSUE THREAD

**Issue by nicmc** [cbeust/testng#368]
I've created a service that executes TestNG tests using suite XMLs as input. When 2+ tests are executed near the same time the tests can fail (they aren't executed) with the following error:

FWK005 parse may not be called while parsing

Here's the trace:

Caused by: org.xml.sax.SAXException: FWK005 parse may not be called while parsing.
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1245)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:522)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:395)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:198)
        at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:17)
        at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:10)
        at org.testng.xml.Parser.parse(Parser.java:172)
        at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:311)
        ... 27 more

Thanks for looking into it.

**Comment by krmahadevan** [comment]
This was fixed by https://github.com/cbeust/testng/pull/393. Closing this issue.
