### ISSUE TITLE
Dependent methods with alwaysRun=true cause NPE

### ISSUE THREAD

**Issue by ddimtirov** [cbeust/testng#383]
Consider the following test:

```
import org.testng.annotations.Test;

class T {
    @Test 
    public void x() { }

    @Test(dependsOnMethods = 'x', alwaysRun = true) 
    public void y() { }

    @Test(dependsOnMethods = 'x') 
    public void z() { }
}
```

If we create a suite including only method y(), TestNG refuses to run and tells us that it is dependent method and we need to include the dependency. 

If we try to run only method z(), TestNG fails with NPE while trying to resolve the dependency. I would have expected it to ignore the dependency and just run the method.

**Comment by krmahadevan** [comment]
Tried reproducing this with TestNG 6.12 and cannot recreate this issue.
Here's what I used 

**Test class**
```java
import org.testng.annotations.Test;

public class Issue383TestclassSample {
    @Test
    public void x() {
    }

    @Test(dependsOnMethods = "x", alwaysRun = true)
    public void y() {
    }

    @Test(dependsOnMethods = "x")
    public void z() {
    }
}
```

**Test runner**
```java
import org.testng.TestNG;
import org.testng.annotations.Test;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlInclude;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlTest;

import java.util.Collections;

public class Issue383TestRunner {
    @Test
    public void testMethod() {
        XmlSuite suite = new XmlSuite();
        suite.setName("suite");
        XmlTest xmlTest = new XmlTest(suite);
        xmlTest.setName("test");
        XmlClass xmlClass = new XmlClass(Issue383TestclassSample.class);
        xmlClass.setIncludedMethods(Collections.singletonList(new XmlInclude("z")));
        xmlTest.setXmlClasses(Collections.singletonList(xmlClass));
        suite.setTests(Collections.singletonList(xmlTest));
        TestNG testng = new TestNG();
        testng.setXmlSuites(Collections.singletonList(suite));
        System.err.println(suite.toXml());
        testng.setVerbose(2);
        testng.run();
    }
}
```

**Output**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="suite">
  <test name="test">
    <classes>
      <class name="com.rationaleemotions.github.issue383.Issue383TestclassSample">
        <methods>
          <include name="z"/>
        </methods>
      </class> <!-- com.rationaleemotions.github.issue383.Issue383TestclassSample -->
    </classes>
  </test> <!-- test -->
</suite> <!-- suite -->


org.testng.TestNGException: 
com.rationaleemotions.github.issue383.Issue383TestclassSample.z() is depending on method public void com.rationaleemotions.github.issue383.Issue383TestclassSample.x(), which is not annotated with @Test or not included.

	at org.testng.internal.MethodHelper.findDependedUponMethods(MethodHelper.java:111)
	at org.testng.internal.MethodHelper.topologicalSort(MethodHelper.java:216)
	at org.testng.internal.MethodHelper.sortMethods(MethodHelper.java:292)
	at org.testng.internal.MethodHelper.collectAndOrderMethods(MethodHelper.java:59)
	at org.testng.TestRunner.initMethods(TestRunner.java:504)
	at org.testng.TestRunner.init(TestRunner.java:282)
	at org.testng.TestRunner.init(TestRunner.java:252)
	at org.testng.TestRunner.<init>(TestRunner.java:192)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:625)
	at org.testng.SuiteRunner.init(SuiteRunner.java:230)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:173)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1400)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1380)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1234)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at com.rationaleemotions.github.issue383.Issue383TestRunner.testMethod(Issue383TestRunner.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)


===============================================
Default Suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================


Process finished with exit code 0
```
