### ISSUE TITLE
Test stuck in JDK15AnnotationFinder.findAnnotation

### ISSUE THREAD

**Issue by wastevenson** [cbeust/testng#394]
I've got a test run that got stuck in the HashMap.get call in JDK15AnnotationFinder.findAnnotation. Looking at the CPU usage it looks like its in an infinite loop. Looking at the code I suspect the problem is that the m_annotations map is not synchronized and that parallel updates have corrupted its internal state.

The stack trace is:
        at java.util.HashMap.getEntry(HashMap.java:446)
        at java.util.HashMap.get(HashMap.java:405)
        at org.testng.internal.annotations.JDK15AnnotationFinder.findAnnotation(JDK15AnnotationFinder.java:185)
        at org.testng.internal.annotations.JDK15AnnotationFinder.findAnnotation(JDK15AnnotationFinder.java:100)
        at org.testng.internal.Parameters.findDataProvider(Parameters.java:324)
        at org.testng.internal.Parameters.findDataProvider(Parameters.java:262)
        at org.testng.internal.Parameters.handleParameters(Parameters.java:414)
        at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
        at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)

**Comment by juherr** [comment]
A ConcurrentHashMap is used now.
