### ISSUE TITLE
TestNG Eclipse plugin SocketException issue

### ISSUE THREAD

**Issue by sunyue79** [cbeust/testng#402]
Hi,
I develop a Eclipse RCP application based on Eclipse 3.7.1. And install the TestNG Eclipse plugin (6.8.6.20130607_0745) on the RCP product. It always throw an exception as following whatever test suites I run by the TestNG plugin. Then I install another version of TestNG plugin (6.8.0.20121120_1820), everything is ok.
Is it a bug of TestNG or just the plugin  (6.8.6.20130607_0745) ?
Thank you!

java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1857)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1766)
	at java.io.ObjectOutputStream.<init>(ObjectOutputStream.java:246)
	at org.testng.remote.strprotocol.SerializedMessageSender.sendMessage(SerializedMessageSender.java:24)
	at org.testng.remote.strprotocol.MessageHub.sendMessage(MessageHub.java:44)
	at org.testng.remote.RemoteTestNG$RemoteSuiteListener.onFinish(RemoteTestNG.java:250)
	at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:200)
	at org.testng.SuiteRunner.run(SuiteRunner.java:243)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

**Comment by krishna81m** [comment]
Just installed and it is disturbing!!

Eclipse Versions: 
Mars (4.5), Luna (4.4), Kepler (4.3), Juno (4.2, 3.8), Previous to Juno (<=4.1)
Platform Support: 
Windows, Mac, Linux/GTK
Organization Name: 
Cédric Beust
Date Created: 
June 24, 2010 - 09:51
Development Status: 
Production/Stable
License: 
Apache 2.0
Date Updated: 
April 21, 2015 - 11:19
Submitted by: 
Cedric Beust
- See more at: http://marketplace.eclipse.org/content/testng-eclipse?mpc=true&mpc_state=#sthash.J28h98az.dpuf

**Comment by sdeuvarow** [comment]
I have same issue with Eclipse Mars. I had with eclipse Kepler, so I migrate to Mars hoping it's fixed in the new version but I have no luck. 

In the new Eclipse, I reinstall testng plugin but still get the exception.
The test runs, but I see the exception in the console and it's really annoying:

java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(Unknown Source)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(Unknown Source)
	at java.io.ObjectOutputStream.<init>(Unknown Source)
	at org.testng.remote.strprotocol.SerializedMessageSender.sendMessage(SerializedMessageSender.java:20)
	at org.testng.remote.strprotocol.MessageHub.sendMessage(MessageHub.java:44)
	at org.testng.remote.strprotocol.RemoteTestListener.onTestSuccess(RemoteTestListener.java:88)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1827)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1807)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:746)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(Unknown Source)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(Unknown Source)
	at java.io.ObjectOutputStream.<init>(Unknown Source)
	at org.testng.remote.strprotocol.SerializedMessageSender.sendMessage(SerializedMessageSender.java:20)
	at org.testng.remote.strprotocol.MessageHub.sendMessage(MessageHub.java:44)
	at org.testng.remote.strprotocol.RemoteTestListener.onFinish(RemoteTestListener.java:34)
	at org.testng.TestRunner.fireEvent(TestRunner.java:1459)
	at org.testng.TestRunner.afterRun(TestRunner.java:1205)
	at org.testng.TestRunner.run(TestRunner.java:612)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)

java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(Unknown Source)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(Unknown Source)
	at java.io.ObjectOutputStream.<init>(Unknown Source)
	at org.testng.remote.strprotocol.SerializedMessageSender.sendMessage(SerializedMessageSender.java:20)
	at org.testng.remote.strprotocol.MessageHub.sendMessage(MessageHub.java:44)
	at org.testng.remote.RemoteTestNG$RemoteSuiteListener.onFinish(RemoteTestNG.java:249)
	at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:199)
	at org.testng.SuiteRunner.run(SuiteRunner.java:243)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)

**Comment by missedone** [comment]
link to https://github.com/cbeust/testng-eclipse/issues/91

**Comment by missedone** [comment]
potential workaround: https://github.com/cbeust/testng-eclipse/issues/91#issuecomment-126371813

**Comment by missedone** [comment]
@juherr 
this one can be closed
