### ISSUE TITLE
[maven using JDK7] java.lang.RuntimeException: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.google.inject.Module not found

### ISSUE THREAD

**Issue by juliohm1978** [cbeust/testng#405]
Once we moved from JDK6 to jdk1.7.0_25, our project no longer compiles. The maven compiler fails at the `testCompile` phase with the following exception as the root cause.

```
Caused by: java.lang.RuntimeException: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.google.inject.Module not found
    at org.eclipse.persistence.internal.jpa.modelgen.CanonicalModelProcessor.process(CanonicalModelProcessor.java:407)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
    at com.sun.tools.javac.main.Main.compile(Main.java:439)
    ... 32 more

```

We googled across [this issue](https://github.com/dwdyer/reportng/issues/28) with a similar problem. Their workaround works fine. Since the `guice` dependency on testng's pom.xml is marked as `provided`, we can workaround the error by adding Guice as a dependency explicitely in our project.

```
<dependency>
    <groupId>com.google.inject</groupId>
    <artifactId>guice</artifactId>
    <version>2.0</version>
    <scope>test</scope>
</dependency>
```

So we decided to post the issue here to get a feedback. Is this a known issue?

Kind regards.

**Comment by juliohm1978** [comment]
Issue has gone stale for months now. Will gladly reopen if anyone is interested.
