### ISSUE TITLE
@AfterClass method is executed after a @Test method failed even though alwaysRun=false

### ISSUE THREAD

**Issue by vadipp** [cbeust/testng#415]
I'm trying this with TestNG 6.1.1 and then TestNG 6.8.5 with the same results:

``` java
import org.testng.annotations.AfterClass;
import org.testng.annotations.Test;

public class TestTest {
    @Test
    public void test() {
        throw new RuntimeException();
    }


    @AfterClass(alwaysRun = false)
    public void runOnSuccess() {
        System.err.println("success");
    }

    @AfterClass(alwaysRun = true)
    public void runAlways() {
        System.err.println("always");
    }
}
```

Expected output:

```
always
```

Actual output:

```
always
success
```

**Comment by krmahadevan** [comment]
This is not a bug. TestNG is working as designed.

As per the Javadocs 

>    For after methods (afterSuite, afterClass, ...): If set to true, this configuration method will be run even if one or more methods invoked previously failed or was skipped.

So for a sample such as the one below, the `@AfterClass` would be skipped because `@AfterMethod` failed, when `alwaysRun=false`

```java
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;

public class Issue415TestClass {
  @Test
  public void test() {
    throw new RuntimeException("test failed");
  }

  @AfterMethod
  public void aftermethod() {
    throw new RuntimeException("aftermethod failed");
  }

  @AfterClass
  public void runOnSuccess() {
    System.err.println("success");
  }
}
```

**output**

```
java.lang.RuntimeException: test failed

	at rationale.emotions.issue415.Issue415TestClass.test(Issue415TestClass.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:626)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:757)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1031)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:141)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:121)
	at org.testng.TestRunner.privateRun(TestRunner.java:652)
	at org.testng.TestRunner.run(TestRunner.java:509)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:453)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:448)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:413)
	at org.testng.SuiteRunner.run(SuiteRunner.java:362)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1132)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1061)
	at org.testng.TestNG.runSuites(TestNG.java:991)
	at org.testng.TestNG.run(TestNG.java:959)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)


java.lang.RuntimeException: aftermethod failed

	at rationale.emotions.issue415.Issue415TestClass.aftermethod(Issue415TestClass.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:502)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:231)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:684)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:757)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1031)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:141)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:121)
	at org.testng.TestRunner.privateRun(TestRunner.java:652)
	at org.testng.TestRunner.run(TestRunner.java:509)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:453)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:448)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:413)
	at org.testng.SuiteRunner.run(SuiteRunner.java:362)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1132)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1061)
	at org.testng.TestNG.runSuites(TestNG.java:991)
	at org.testng.TestNG.run(TestNG.java:959)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)


===============================================
Default Suite
Total tests run: 1, Failures: 1, Skips: 0
Configuration Failures: 1, Skips: 1
===============================================


Process finished with exit code 0
```

But with the same sample, and with `alwaysRun=true` the `@AfterClass` runs.

```java
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;

public class Issue415TestClass {
  @Test
  public void test() {
    throw new RuntimeException("test failed");
  }

  @AfterMethod
  public void aftermethod() {
    throw new RuntimeException("aftermethod failed");
  }

  @AfterClass(alwaysRun = true)
  public void runOnSuccess() {
    System.err.println("success");
  }
}
```

**output**

```
java.lang.RuntimeException: test failed

	at rationale.emotions.issue415.Issue415TestClass.test(Issue415TestClass.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:626)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:757)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1031)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:141)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:121)
	at org.testng.TestRunner.privateRun(TestRunner.java:652)
	at org.testng.TestRunner.run(TestRunner.java:509)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:453)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:448)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:413)
	at org.testng.SuiteRunner.run(SuiteRunner.java:362)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1132)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1061)
	at org.testng.TestNG.runSuites(TestNG.java:991)
	at org.testng.TestNG.run(TestNG.java:959)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

success

java.lang.RuntimeException: aftermethod failed

	at rationale.emotions.issue415.Issue415TestClass.aftermethod(Issue415TestClass.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:502)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:231)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:684)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:757)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1031)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:141)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:121)
	at org.testng.TestRunner.privateRun(TestRunner.java:652)
	at org.testng.TestRunner.run(TestRunner.java:509)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:453)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:448)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:413)
	at org.testng.SuiteRunner.run(SuiteRunner.java:362)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1132)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1061)
	at org.testng.TestNG.runSuites(TestNG.java:991)
	at org.testng.TestNG.run(TestNG.java:959)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)


===============================================
Default Suite
Total tests run: 1, Failures: 1, Skips: 0
Configuration Failures: 1, Skips: 0
===============================================


Process finished with exit code 0

```

**Comment by AdirDayan1** [comment]
> This is not a bug. TestNG is working as designed.
> 
> As per the Javadocs
> 
> > For after methods (afterSuite, afterClass, ...): If set to true, this configuration method will be run even if one or more methods invoked previously failed or was skipped.
> 
> So for a sample such as the one below, the `@AfterClass` would be skipped because `@AfterMethod` failed, when `alwaysRun=false`
> 
> ```java
> import org.testng.annotations.AfterClass;
> import org.testng.annotations.AfterMethod;
> import org.testng.annotations.Test;
> 
> public class Issue415TestClass {
>   @Test
>   public void test() {
>     throw new RuntimeException("test failed");
>   }
> 
>   @AfterMethod
>   public void aftermethod() {
>     throw new RuntimeException("aftermethod failed");
>   }
> 
>   @AfterClass
>   public void runOnSuccess() {
>     System.err.println("success");
>   }
> }
> ```
> 
> **output**
> 
> ```
> java.lang.RuntimeException: test failed
> 
> 	at rationale.emotions.issue415.Issue415TestClass.test(Issue415TestClass.java:10)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
> 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:626)
> 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:757)
> 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1031)
> 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:141)
> 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:121)
> 	at org.testng.TestRunner.privateRun(TestRunner.java:652)
> 	at org.testng.TestRunner.run(TestRunner.java:509)
> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:453)
> 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:448)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:413)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:362)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1132)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1061)
> 	at org.testng.TestNG.runSuites(TestNG.java:991)
> 	at org.testng.TestNG.run(TestNG.java:959)
> 	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
> 	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
> 
> 
> java.lang.RuntimeException: aftermethod failed
> 
> 	at rationale.emotions.issue415.Issue415TestClass.aftermethod(Issue415TestClass.java:15)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
> 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:502)
> 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:231)
> 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:684)
> 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:757)
> 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1031)
> 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:141)
> 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:121)
> 	at org.testng.TestRunner.privateRun(TestRunner.java:652)
> 	at org.testng.TestRunner.run(TestRunner.java:509)
> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:453)
> 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:448)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:413)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:362)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1132)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1061)
> 	at org.testng.TestNG.runSuites(TestNG.java:991)
> 	at org.testng.TestNG.run(TestNG.java:959)
> 	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
> 	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
> 
> 
> ===============================================
> Default Suite
> Total tests run: 1, Failures: 1, Skips: 0
> Configuration Failures: 1, Skips: 1
> ===============================================
> 
> 
> Process finished with exit code 0
> ```
> 
> But with the same sample, and with `alwaysRun=true` the `@AfterClass` runs.
> 
> ```java
> import org.testng.annotations.AfterClass;
> import org.testng.annotations.AfterMethod;
> import org.testng.annotations.Test;
> 
> public class Issue415TestClass {
>   @Test
>   public void test() {
>     throw new RuntimeException("test failed");
>   }
> 
>   @AfterMethod
>   public void aftermethod() {
>     throw new RuntimeException("aftermethod failed");
>   }
> 
>   @AfterClass(alwaysRun = true)
>   public void runOnSuccess() {
>     System.err.println("success");
>   }
> }
> ```
> 
> **output**
> 
> ```
> java.lang.RuntimeException: test failed
> 
> 	at rationale.emotions.issue415.Issue415TestClass.test(Issue415TestClass.java:10)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
> 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:626)
> 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:757)
> 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1031)
> 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:141)
> 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:121)
> 	at org.testng.TestRunner.privateRun(TestRunner.java:652)
> 	at org.testng.TestRunner.run(TestRunner.java:509)
> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:453)
> 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:448)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:413)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:362)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1132)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1061)
> 	at org.testng.TestNG.runSuites(TestNG.java:991)
> 	at org.testng.TestNG.run(TestNG.java:959)
> 	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
> 	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
> 
> success
> 
> java.lang.RuntimeException: aftermethod failed
> 
> 	at rationale.emotions.issue415.Issue415TestClass.aftermethod(Issue415TestClass.java:15)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
> 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:502)
> 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:231)
> 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:684)
> 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:757)
> 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1031)
> 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:141)
> 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:121)
> 	at org.testng.TestRunner.privateRun(TestRunner.java:652)
> 	at org.testng.TestRunner.run(TestRunner.java:509)
> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:453)
> 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:448)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:413)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:362)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1132)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1061)
> 	at org.testng.TestNG.runSuites(TestNG.java:991)
> 	at org.testng.TestNG.run(TestNG.java:959)
> 	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
> 	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
> 
> 
> ===============================================
> Default Suite
> Total tests run: 1, Failures: 1, Skips: 0
> Configuration Failures: 1, Skips: 0
> ===============================================
> 
> 
> Process finished with exit code 0
> ```

I did some checks, it seems like if an exception is thrown from "config methods" like `@BeforeClass`, `@AfterMethod` etc, then the `@AfterClass` will be skipped, unless flag `runAlways` is 'true'
