### ISSUE TITLE
IRetryAnalyser weird behaviour

### ISSUE THREAD

**Issue by hseffler** [cbeust/testng#444]
I am using IRetryAnalyser to execute flaky tests a 2nd and 3rd time. 

My expectation would be that in case of an ultimate failure I get ONE test failure reported. When a test succeeds on the 2nd or 3rd try I would expect ONE successful result.

Instead I get each single result reported in the final result, which makes the IRetryAnalyser kinda useless.

I understand this is a experimental feature, but it would be nice to have it working again. I worked for be in TestNG 5.8 AFAIR.

**Comment by krmahadevan** [comment]
This is working fine in TestNG `7.3.0`

Sample

```java
import org.testng.Assert;
import org.testng.IRetryAnalyzer;
import org.testng.ITestResult;
import org.testng.annotations.Test;

public class SampleTestClass {

  public static int counter = 1;

  @Test(retryAnalyzer = LocalRetry.class)
  public void testMethod() {
    if (counter++ != 4) {
      Assert.fail("Counter is still not 3");
    }
  }

  public static class LocalRetry implements IRetryAnalyzer {

    @Override
    public boolean retry(ITestResult result) {
      return counter <= 4;
    }
  }

}

```

Reports

Emailable report
![image](https://user-images.githubusercontent.com/909773/99272088-5f378900-284d-11eb-89bf-bd6c9d137317.png)

Html report

![image](https://user-images.githubusercontent.com/909773/99272149-78d8d080-284d-11eb-8283-96f1a013a9d6.png)


`testng-results.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" retried="3" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default Suite" duration-ms="301" started-at="2020-11-16T20:47:55 IST" finished-at="2020-11-16T20:47:55 IST">
    <groups>
    </groups>
    <test name="testbed" duration-ms="301" started-at="2020-11-16T20:47:55 IST" finished-at="2020-11-16T20:47:55 IST">
      <class name="com.rationaleemotions.github.issue444.SampleTestClass">
        <test-method status="SKIP" signature="testMethod()[pri:0, instance:com.rationaleemotions.github.issue444.SampleTestClass@21e360a]" name="testMethod" duration-ms="102" retried="true" started-at="2020-11-16T20:47:55 IST" finished-at="2020-11-16T20:47:55 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Counter is still not 3]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Counter is still not 3
at org.testng.Assert.fail(Assert.java:99)
at com.rationaleemotions.github.issue444.SampleTestClass.testMethod(SampleTestClass.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod -->
        <test-method status="SKIP" signature="testMethod()[pri:0, instance:com.rationaleemotions.github.issue444.SampleTestClass@21e360a]" name="testMethod" duration-ms="3" retried="true" started-at="2020-11-16T20:47:55 IST" finished-at="2020-11-16T20:47:55 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Counter is still not 3]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Counter is still not 3
at org.testng.Assert.fail(Assert.java:99)
at com.rationaleemotions.github.issue444.SampleTestClass.testMethod(SampleTestClass.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod -->
        <test-method status="SKIP" signature="testMethod()[pri:0, instance:com.rationaleemotions.github.issue444.SampleTestClass@21e360a]" name="testMethod" duration-ms="4" retried="true" started-at="2020-11-16T20:47:55 IST" finished-at="2020-11-16T20:47:55 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Counter is still not 3]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Counter is still not 3
at org.testng.Assert.fail(Assert.java:99)
at com.rationaleemotions.github.issue444.SampleTestClass.testMethod(SampleTestClass.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod -->
        <test-method status="PASS" signature="testMethod()[pri:0, instance:com.rationaleemotions.github.issue444.SampleTestClass@21e360a]" name="testMethod" duration-ms="3" started-at="2020-11-16T20:47:55 IST" finished-at="2020-11-16T20:47:55 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod -->
      </class> <!-- com.rationaleemotions.github.issue444.SampleTestClass -->
    </test> <!-- testbed -->
  </suite> <!-- Default Suite -->
</testng-results>

```
