### ISSUE TITLE
Cannot instantiate class exception

### ISSUE THREAD

**Issue by testautomationengr** [cbeust/testng#484]
I have a suite of selenium tests divided as java classes. I have driver script wherein, I create the testng xml suite programmatically and run it. It all works fine when invoked from eclipse or ant. I wanted to replace ant with maven and run the tests. But getting this exception.

[TestRunner] Running the tests in 'TestClass10' with parallel mode:false
[RunInfo] Adding method selector: org.testng.internal.XmlMethodSelector@6076ab2f priority: 10
ERROR::org.testng.TestNGException: 
Cannot instantiate class com.portico.regressionsuite.tests.TestClass10
===== Invoked methods
    TestDriver.runTestSuite()[pri:0, instance:com.portico.driver.TestDriver@5c73a7ab] 1551083435

Searched online forums but could not any solution to this. Please advice on this.

**Comment by krmahadevan** [comment]
Not much information available for debugging. Closing this issue. Please feel free to re-open and add more context.

**Comment by smote25** [comment]
------------Help me to resolve this issue-----------
Throwing below-mentioned error while executing a test script using TestNG


[RemoteTestNG] detected TestNG version 7.0.1
org.testng.TestNGException: 
**_An error occurred while instantiating class 
Check to make sure it can be instantiated
	at org.testng.internal.InstanceCreator.createInstanceUsingObjectFactory(InstanceCreator.java:134)_**
	at org.testng.internal.InstanceCreator.createInstance(InstanceCreator.java:79)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:109)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:167)
	at org.testng.TestClass.getInstances(TestClass.java:102)
	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:82)
	at org.testng.TestClass.init(TestClass.java:74)
	at org.testng.TestClass.<init>(TestClass.java:39)
	at org.testng.TestRunner.initMethods(TestRunner.java:459)
	at org.testng.TestRunner.init(TestRunner.java:338)
	at org.testng.TestRunner.init(TestRunner.java:291)
	at org.testng.TestRunner.<init>(TestRunner.java:222)
	at org.testng.remote.support.RemoteTestNG6_12$1.newTestRunner(RemoteTestNG6_12.java:33)
	at org.testng.remote.support.RemoteTestNG6_12$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_12.java:66)
	at org.testng.ITestRunnerFactory.newTestRunner(ITestRunnerFactory.java:55)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:676)
	at org.testng.SuiteRunner.init(SuiteRunner.java:178)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:112)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1275)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1251)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1100)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
