### ISSUE TITLE
ClassCastException with primitive arrays in data providers

### ISSUE THREAD

**Issue by dimo414** [cbeust/testng#535]
Consider the following test:

    import org.testng.annotations.DataProvider;
    import org.testng.annotations.Test;
    
    public class ArrayToStringTest {
        @DataProvider
        protected Object[][] data() {
            return new Object[][] {
                {new int[]{1,2,3}}
            };
        }
        
        @Test(dataProvider="data")
        public void test(int[] arr) {
            // pass
        }
    }

I would expect this test to pass trivially, however instead I get a `ClassCastException`:

    FAILED: test
    java.lang.ClassCastException: [I cannot be cast to [Ljava.lang.Object;
    	at org.testng.remote.strprotocol.TestResultMessage.toString(TestResultMessage.java:313)
    	at org.testng.remote.strprotocol.TestResultMessage.<init>(TestResultMessage.java:108)
    	at org.testng.remote.strprotocol.TestResultMessage.<init>(TestResultMessage.java:126)
    	at org.testng.remote.strprotocol.RemoteTestListener.onTestFailure(RemoteTestListener.java:72)
    	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1895)
    ...

Looking at `TestResultMessage:313`, it seems the code erroneously assumes that if `o.getClass().isArray()` it can safely be cast to an `Object[]`, which fails for primitive arrays.  Given that the only purpose of this block is to construct a string, we could catch the `ClassCastException` and call `Arrays.toString(o)` to properly handle primitive arrays.

I'd be happy to put together a pull request, but I'm still waiting on [a pull request](https://github.com/cbeust/testng/pull/519) I submitted a month ago.

**Comment by dimo414** [comment]
This passes with an updated jar and Eclipse plugin.  I'll note there's still a link to the 6.8 on the download page, linked from the text "here for ant users".
