### ISSUE TITLE
TestNG eclipse issue after clicking on Runas --> TestNG Test

### ISSUE THREAD

**Issue by raghav2329** [cbeust/testng#738]
After creating TestNG script with selenium webdriver and when i try to run the script from Runas--> TestNG Test. I am getting the issue. Kindly find the attachment.
![testng issue](https://cloud.githubusercontent.com/assets/12811132/8224628/624000fa-15a7-11e5-80f1-47f1779c2386.jpg)

**Comment by raghav2329** [comment]
Please find the below detailed error report :
!ENTRY org.eclipse.ui 4 4 2015-06-19 09:56:40.162
!MESSAGE Unable to initialize part
!STACK 0
java.lang.NullPointerException
	at org.testng.eclipse.ui.TestRunnerViewPart.newSuiteRunInfo(TestRunnerViewPart.java:418)
	at org.testng.eclipse.ui.TestRunnerViewPart.updateResultThread(TestRunnerViewPart.java:404)
	at org.testng.eclipse.ui.TestRunnerViewPart.init(TestRunnerViewPart.java:219)
	at org.eclipse.ui.internal.ViewReference.initialize(ViewReference.java:140)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:305)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:888)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:869)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:120)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:337)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:258)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:104)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:73)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:55)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:127)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:983)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:662)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$6.run(PartRenderingEngine.java:547)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:531)
	at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.createWidget(ElementReferenceRenderer.java:69)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:983)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:662)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:766)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$2(PartRenderingEngine.java:737)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$7.run(PartRenderingEngine.java:731)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:715)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.createElement(PartServiceImpl.java:1188)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1149)
	at org.eclipse.ui.internal.WorkbenchPartReference.getPart(WorkbenchPartReference.java:417)
	at org.eclipse.ui.internal.ViewReference.getView(ViewReference.java:85)
	at org.eclipse.ui.internal.WorkbenchPage.findView(WorkbenchPage.java:1993)
	at org.testng.eclipse.TestNGPlugin.findTestRunnerViewPartInActivePage(TestNGPlugin.java:261)
	at org.testng.eclipse.TestNGPlugin.connectTestRunner(TestNGPlugin.java:210)
	at org.testng.eclipse.TestNGPlugin$2.run(TestNGPlugin.java:201)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4147)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3764)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

!ENTRY org.eclipse.ui 4 4 2015-06-19 09:56:40.179
!MESSAGE Unable to create part

!ENTRY org.eclipse.ui 4 0 2015-06-19 09:56:40.180
!MESSAGE

**Comment by cbeust** [comment]
@missedone This it's related to the recent changes?

**Comment by missedone** [comment]
looks like it's the same issue as https://github.com/cbeust/testng-eclipse/issues/157
will look into it later

**Comment by missedone** [comment]
@raghav2329 
could you share a small sample project so that we can reproduce this issue?

BTW, what if you have the TestNG view opened before "right click -> run as", do you see the same issue?
(to open the TestNG view, click "Window (on top-level menu) -> Show View -> Other... -> Java -> TestNG")

thanks

**Comment by Sachleen-Singh** [comment]
@raghav2329 
It happens because of your recent changes in test output folder or by adding Velocity, Guice JARS.
You may create new folder to get test output.
You can try this : 
Windows>Preferences>TestNG>Exclude Stack Trace and put > org.testng.internal org.testng.TestRunner org.testng.SuiteRunner org.testng.remote.RemoteTestNG org.testng.TestNG sun.reflect java.lang
Now close your eclipse and run again.
PS : Try to close and start again instead of restarting eclipse. And don't forget to refresh your project and make sure all the JAR files are available and added.

**Comment by juherr** [comment]
@Sachleen-Singh Thank for the answer :)

Closed: use cbeust/testng-eclipse#157 instead

**Comment by missedone** [comment]
@raghav2329 , @Sachleen-Singh 
could you help verify the latest beta of testng-eclipse fixed this issue or not:
http://testng.org/doc/download.html

thanks
