### ISSUE TITLE
NullPointerException throwns by Assert.assertEquals()

### ISSUE THREAD

**Issue by archiecobbs** [cbeust/testng#748]
TestNG 6.8.7 (same code exists in 6.8.21)

There is a missing null check, causing `assertEquals()` to throw an NPE. This happens when `assertEquals()` is invoked with `actual == null` and `expected` an array type.

```
java.lang.NullPointerException
        at org.testng.Assert.assertArrayEquals(Assert.java:135)
        at org.testng.Assert.assertEquals(Assert.java:117)
        at org.testng.Assert.assertEquals(Assert.java:165)
```

**Comment by krmahadevan** [comment]
Verified in TestNG 6.12. Issue is no longer re-producible.
