### ISSUE TITLE
Running test suite from eclipse doesn't work when there are white spaces in file path.

### ISSUE THREAD

**Issue by nedeljko** [cbeust/testng#76]
Steps to reproduce: 
1. Create simple test class and testng xml file for it. Make sure that 
white-space exist in file path (for example project/Client A/test/ 
test.xml) 
2. Open Eclipse run configurations and create new TestNG run 
configuration by selecting Suite radio button and browse to mentioned 
xml file. 
3. Run configuration. The following error occurs: 
java.io.FileNotFoundException: D:\Workspaces\EclipseGalileo 
\TestNGWhitespaceBug\test\Client (The system cannot find the file 
specified) 
        at java.io.FileInputStream.open(Native Method) 
        at java.io.FileInputStream.<init>(FileInputStream.java:106) 
        at java.io.FileInputStream.<init>(FileInputStream.java:66) 
        at org.testng.xml.Parser.parse(Parser.java:165) 
        at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:304) 
        at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:86) 
        at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:199) 
        at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:170) 
java.io.FileNotFoundException: D:\Workspaces\EclipseGalileo 
\TestNGWhitespaceBug\A\clienta-test.xml (The system cannot find the 
path specified) 
        at java.io.FileInputStream.open(Native Method) 
        at java.io.FileInputStream.<init>(FileInputStream.java:106) 
        at java.io.FileInputStream.<init>(FileInputStream.java:66) 
        at org.testng.xml.Parser.parse(Parser.java:165) 
        at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:304) 
        at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:86) 
        at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:199) 
        at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:170) 

---

Eclipse: Indigo Release 
TestNG: 6.1.1 

Example project can be found at:
http://testng-whitespace-bug.googlecode.com/svn/trunk/

**Comment by krmahadevan** [comment]
Tried with TestNG 6.12. Cannot reproduce this problem anymore. 

Here's the details of what I used 

**Issue76TestRunner.java**

```java
import org.testng.TestNG;
import org.testng.annotations.Test;

import java.util.Collections;

public class Issue76TestRunner {
    @Test
    public void testMethod() {
        String xmlLocation = "src/test/resources/76/whitespaced folder/white spaced suite.xml";
        TestNG testng = new TestNG();
        testng.setTestSuites(Collections.singletonList(xmlLocation));
        testng.setVerbose(2);
        testng.run();
    }
}
```

**SampleTestClass.java**
```java
import org.testng.annotations.Test;

public class SampleTestClass {
    @Test
    public void testMethod() {
        System.err.println("Hello World");
    }
}
```

**TestNG xml being used**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="76_Suite" verbose="2">
    <test name="76_Test">
        <classes>
            <class name="com.rationaleemotions.github.issue76.SampleTestClass"/>
        </classes>
    </test>
</suite>
```

**Test folder hierarchy**
```shell
✔ ~/githome/PlayGround/testbed/src/test/resources 
08:23 $ tree 76
76
└── whitespaced\ folder
    └── white\ spaced\ suite.xml

1 directory, 1 file
```

**Test run output**
```
...
... TestNG 6.12 by Cédric Beust (cedric@beust.com)
...

Hello World
PASSED: testMethod

===============================================
    76_Test
    Tests run: 1, Failures: 0, Skips: 0
===============================================
```
