### ISSUE TITLE
timeout is ignored at test level

### ISSUE THREAD

**Issue by cktech529** [cbeust/testng#779]
I am only to get a suite level <suite timeout="60000"> to respond. 

When I do NOT put the suite level timeout and put a 

<test timeout="5000">  entry,

It doesn't timeout.

**Comment by juherr** [comment]
What is the question/issue?

Could you share your use case?

**Comment by cktech529** [comment]
When you have a suite with n test entries and the tests have
timeout="20000" and the suite does NOT have a timeout set and parallel is
"tests" at the suite level, the timeout is ignored at the test level. When
you set timeout at the suite level, tests that timeout fail testng and
reports aren't correctly generated.

**Comment by juherr** [comment]
Ok, it's a bit clearer. But could you share a minimal project we can run and the result you expect?

**Comment by cktech529** [comment]
Will do,

Was on the road when I saw this.

Thanks,

Chris

**Comment by krmahadevan** [comment]
Tried reproducing this in the latest codebase from `master` branch (Cannot use TestNG 6.12 because of the issue https://github.com/cbeust/testng/issues/1493). Cannot reproduce this issue any more.

Here's what I used 
**Test class sample 1**
```java
import org.testng.annotations.Test;

import java.util.concurrent.TimeUnit;

public class Issue779TestcaseSample1 {
    @Test
    public void testMethod() throws InterruptedException {
        TimeUnit.SECONDS.sleep(15);
    }
}
```

**Test class sample 2**
```java
import org.testng.annotations.Test;

import java.util.concurrent.TimeUnit;

public class Issue779TestcaseSample2 {
    @Test
    public void testMethod() throws InterruptedException {
        TimeUnit.SECONDS.sleep(20);
    }
}
```

**Test runner**
```java
import org.assertj.core.api.Assertions;
import org.testng.ITestNGListener;
import org.testng.ITestResult;
import org.testng.TestListenerAdapter;
import org.testng.TestNG;
import org.testng.annotations.Test;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlTest;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class Issue779TestRunner {
    @Test
    public void testMethod() {
        XmlSuite suite = new XmlSuite();
        suite.setName("suite");
        XmlTest test1 = create(suite, 16 * 1000, Issue779TestcaseSample1.class);
        test1.setName("Will_Pass_Test");
        XmlTest test2 = create(suite, 15 * 1000, Issue779TestcaseSample2.class);
        test2.setName("Will_Fail_Test");
        suite.setTests(Arrays.asList(test1, test2));
        TestNG testng = new TestNG();
        testng.setXmlSuites(Collections.singletonList(suite));
        testng.setVerbose(2);
        testng.setParallel(XmlSuite.ParallelMode.TESTS);
        TestListenerAdapter tla = new TestListenerAdapter();
        testng.addListener((ITestNGListener) tla);
        testng.run();
        Set<String> passedTests = extractTestNames(tla.getPassedTests());
        Set<String> failedTests = extractTestNames(tla.getFailedTests());
        Assertions.assertThat(failedTests).containsExactly("Will_Fail_Test");
        Assertions.assertThat(passedTests).containsExactly("Will_Pass_Test");
    }

    private static Set<String> extractTestNames(List<ITestResult> results) {
        Set<String> names = new HashSet<>();
        for (ITestResult result : results) {
            names.add(result.getTestContext().getName());
        }
        return names;
    }

    private static XmlTest create(XmlSuite suite, long timeout, Class<?> clazz) {
        XmlTest xmlTest = new XmlTest(suite);
        xmlTest.setTimeOut(timeout);
        xmlTest.setXmlClasses(Collections.singletonList(new XmlClass(clazz)));
        return xmlTest;
    }
}
```

**Test output**
```
PASSED: testMethod

===============================================
    Will_Pass_Test
    Tests run: 1, Failures: 0, Skips: 0
===============================================

FAILED: testMethod
org.testng.internal.thread.ThreadTimeoutException: Method rationale.emotions.issue779.Issue779TestcaseSample2.testMethod() didn't finish within the time-out 15000
	at java.lang.Thread.interrupt(Thread.java:919)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:64)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)


===============================================
    Will_Fail_Test
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
suite
Total tests run: 2, Failures: 1, Skips: 0
===============================================


===============================================
Default Suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================


Process finished with exit code 0
```
