### ISSUE TITLE
TestNG should check params of configuration methods, and provides a clear error message

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#901]
From: http://stackoverflow.com/q/33996836/4234729

**Comment by krmahadevan** [comment]
Revisited this on TestNG 6.12 and this is no longer a problem.

**Sample used**
```java
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import java.lang.reflect.Method;

public class Issue901TestclassSample {
    @BeforeSuite
    public void configureEnvironment() {
        // does some basic tasks
    }

    @BeforeTest
    public void configureTest(Method m) {
        System.out.println("Test Case Name : " + m.getName());
    }

    @Test
    public void TestABC() {
    }

    @Test
    public void TestXYZ() {
    }

    @AfterTest
    public void testCleanUp() {
        //performs test clean up activities
    }
}
```

**Output**
```
org.testng.TestNGException: 
Can inject only one of <ITestContext, XmlTest> into a @BeforeTest annotated configureTest.
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection

	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:334)
	at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:274)
	at org.testng.internal.Parameters.createParameters(Parameters.java:562)
	at org.testng.internal.Parameters.createConfigurationParameters(Parameters.java:150)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:206)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.TestRunner.beforeRun(TestRunner.java:658)
	at org.testng.TestRunner.run(TestRunner.java:626)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```
