### ISSUE TITLE
Iterating over Reporter.getOutput() leads to ConcurrentModificationException

### ISSUE THREAD

**Issue by akajla09** [cbeust/testng#905]
Reporter.getOutput() returns a ref to the internal log Vector. Reporters like the XMLReporter iterate over this list in order to produce their output:

``` java
List<String> output = Reporter.getOutput();
    for (String line : output) {
      if (line != null) {
        xmlBuffer.push(XMLReporterConfig.TAG_LINE);
        xmlBuffer.addCDATA(line);
        xmlBuffer.pop();
      }
    }
```

However, the log vector can be modified by another thread leading to a ConcurrentModificationException while iterating in the reporter:

``` java
java.util.ConcurrentModificationException
        at java.util.Vector$Itr.checkForComodification(Vector.java:1184)
        at java.util.Vector$Itr.next(Vector.java:1137)
        at org.testng.reporters.XMLReporter.writeReporterOutput(XMLReporter.java:73)
        at org.testng.reporters.XMLReporter.generateReport(XMLReporter.java:61)
        at org.testng.TestNG.generateReports(TestNG.java:1115)
        at org.testng.TestNG.run(TestNG.java:1074)
```

**Comment by juherr** [comment]
Do you have any sample that reproduce the problem every time?

**Comment by akajla09** [comment]
I have a use case where I initialize multiple TestNG instances programmatically (in separate threads), each with a XMLReporter. Each test that is run outputs a custom message via Reporter.log(). If one of the TestNG instances reaches the reporter stage and starts generating output, it runs the risk of iterating over Reporter.getOutput() while another instance is still executing tests that call Reporter.log().

**Comment by juherr** [comment]
> where I initialize multiple TestNG instances programmatically

It doesn't sound good. Why do you do that? 

Could you share something we can run in order to reproduce on our side?

**Comment by akajla09** [comment]
> It doesn't sound good. Why do you do that?

I need to run the same suites/tests in different environments/contexts. But our test context is configured outside of TestNG making it difficult to run everything together in one TestNG instance.


Here is a sample that starts multiple TestNG instances that run tests that log to the Reporter. A few of the threads should step on each other during the reporter phase (might need to change num threads/num logs):

```java
public class Sample {

    public static class Test1 {
        @Test(groups = { "sample.group" }, invocationCount = 50)
        public void test1() {
        	for (int i = 0; i < 100; i ++) {
        		Reporter.log(Thread.currentThread() + " output from test1");
        	}
        }

        @Test(groups = { "sample.group" }, invocationCount = 50)
        public void test2() {
        	for (int i = 0; i < 100; i++) {
        		Reporter.log(Thread.currentThread() + " output from test2");
        	}
        }

        @Test(groups = { "sample.group" }, invocationCount = 50)
        public void test3() {
        	for (int i = 0; i < 100; i++) {
        		Reporter.log(Thread.currentThread() + " output from test3");
        	}
        }
    }

    static final int THREADS = 40;

    public static void main(final String[] args) {

        List<Thread> threads = new ArrayList<Thread>();
        for (int i = 0; i < THREADS; i++) {
            final File dir = new File(System.getProperty("user.dir") + File.separator + "thread" + i);
            dir.mkdir();
            Thread t = new Thread(new Runnable() {

                @Override
                public void run() {
                    final TestNG testNG = new TestNG();
                    testNG.setOutputDirectory(dir.getAbsolutePath());
                    final XmlSuite suite = new XmlSuite();
                    suite.setParallel("tests");
                    suite.setThreadCount(2);
                    suite.setVerbose(10);
                    suite.setName("SampleSuite");
                    suite.setIncludedGroups(Arrays.asList("sample.group"));

                    final XmlTest test = new XmlTest(suite);
                    final XmlClass testClass = new XmlClass(Test1.class);
                    test.setClasses(Arrays.asList(testClass));
                    test.setName("SampleTest");

                    testNG.setXmlSuites(Arrays.asList(suite));
                    testNG.run();
                }

            });
            t.start();
            threads.add(t);
        }
        int status = 0;
        for (Thread t : threads) {
            if (t.isAlive()) {
                try {
                    t.join();
                } catch (InterruptedException e) {
                	System.out.println(e.getMessage());
                    status = 1;
                }
            }
        }
        System.exit(status);
    }
}
```

**Comment by juherr** [comment]
Ok, clear! And why not using the [`suite-files` element](http://testng.org/testng-1.0.dtd.php)?
https://github.com/cbeust/testng/pull/829 will allow you to have duplicate suite in the next release.
It means you will be able to have only one TestNG instance, which is recommanded. What do you think about it?

**Comment by krmahadevan** [comment]
Closing this based on the suggestion from @juherr. Please comment if this is still a problem
