### ISSUE TITLE
set the serialVersionUID

### ISSUE THREAD

**Issue by missedone** [cbeust/testng#912]
we need set the serialVersionUID to avoid object serialization issue:
```
java.io.InvalidClassException: org.testng.remote.strprotocol.GenericMessage; local class incompatible: stream classdesc serialVersionUID = -3655718067
544856041, local class serialVersionUID = 1440074281953763545
[BaseMessageSender] Sending ACK 0
    at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:616)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
    at org.testng.remote.strprotocol.SerializedMessageSender.receiveMessage(SerializedMessageSender.java:39)
    at org.testng.remote.strprotocol.MessageHub.receiveMessage(MessageHub.java:52)
    at org.testng.remote.strprotocol.AbstractRemoteTestRunnerClient$ServerConnection.run(AbstractRemoteTestRunnerClient.java:179)
```

the serialVersionUID should be extracted from the original value so that we can make it's consistent

**Comment by juherr** [comment]
Closed by #913
