### ISSUE TITLE
ClassNotFoundException regression between 6.9.9 and 6.9.10

### ISSUE THREAD

**Issue by jponge** [cbeust/testng#916]
I tried upgrading the dependency of `eclipse/golo-lang` from 6.9.9 to 6.9.10 but now some tests fail due to the Guice `Injector` class not being found, as in:

```
java.lang.NoClassDefFoundError: com/google/inject/Injector
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at org.eclipse.golo.runtime.Module.metadata(Module.java:23)
	at org.eclipse.golo.runtime.Module.augmentations(Module.java:38)
	at org.eclipse.golo.runtime.AugmentationMethodFinder$SimpleAugmentationStrategy.targets(AugmentationMethodFinder.java:103)
	at org.eclipse.golo.runtime.AugmentationMethodFinder.findInClasses(AugmentationMethodFinder.java:214)
	at org.eclipse.golo.runtime.AugmentationMethodFinder.findInCallStackImports(AugmentationMethodFinder.java:249)
	at org.eclipse.golo.runtime.AugmentationMethodFinder.find(AugmentationMethodFinder.java:276)
	at org.eclipse.golo.runtime.MethodInvocationSupport.findTarget(MethodInvocationSupport.java:228)
	at org.eclipse.golo.runtime.MethodInvocationSupport.lookupTarget(MethodInvocationSupport.java:136)
	at org.eclipse.golo.runtime.MethodInvocationSupport.fallback(MethodInvocationSupport.java:155)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.eclipse.golo.runtime.MethodInvocationSupportTest.check_bogus(MethodInvocationSupportTest.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:136)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:80)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.google.inject.Injector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 62 more
```

We are using a straightforward Gradle dependency.

```groovy
dependencies {
  testCompile 'org.testng:testng:6.9.10'
  // ...
}
```

and:

```groovy
test {
  useTestNG()
  // ...
}
```

We don't play much with excluding dependencies in our build, except:

```groovy
configurations.all {
  exclude module: 'junit'
}
```

Any idea of why there is a regression?

**Comment by juherr** [comment]
I can't remember changes on guice between 6.9.9 and 6.9.10.
And the dependency was already declared `<scope>provided</scope>` before 6.9.10.

Did you try to add guice as test dependency? 
As the stacktrace doesn't help, do you know what is asking for Injector?

**Comment by cbeust** [comment]
That's really odd, there were really no changes in that area in a long time.

I'm going to say it's a bug in golo ;-)

Just kidding, I'm not sure what's going on right now.

-- 
Cédric

**Comment by jponge** [comment]
I just did a quick `./gradlew dependencies` with 6.9.9 then 6.9.10, and the diff shows that Guice is gone:

```diff
--- deps-old	2015-12-17 16:57:54.000000000 +0100
+++ deps-new	2015-12-17 16:58:13.000000000 +0100
@@ -1,3 +1,4 @@
+[versioning] WARNING - the working copy has unstaged or uncommitted changes.
 :dependencies
 
 ------------------------------------------------------------
@@ -78,16 +79,9 @@
 +--- org.hamcrest:hamcrest-all:1.3
 +--- org.skyscreamer:jsonassert:1.2.3
 |    \--- org.json:json:20090211
-\--- org.testng:testng:6.9.9
-     +--- org.apache.ant:ant:1.7.0
-     |    \--- org.apache.ant:ant-launcher:1.7.0
+\--- org.testng:testng:6.9.10
      +--- org.beanshell:bsh:2.0b4
-     +--- com.google.inject:guice:4.0
-     |    +--- javax.inject:javax.inject:1
-     |    +--- aopalliance:aopalliance:1.0
-     |    \--- com.google.guava:guava:16.0.1
-     +--- com.beust:jcommander:1.48
-     \--- org.yaml:snakeyaml:1.15
+     \--- com.beust:jcommander:1.48
 
 testRuntime - Runtime classpath for source set 'test'.
 +--- org.ow2.asm:asm:5.0.4
@@ -102,19 +96,12 @@
 +--- org.hamcrest:hamcrest-all:1.3
 +--- org.skyscreamer:jsonassert:1.2.3
 |    \--- org.json:json:20090211
-\--- org.testng:testng:6.9.9
-     +--- org.apache.ant:ant:1.7.0
-     |    \--- org.apache.ant:ant-launcher:1.7.0
+\--- org.testng:testng:6.9.10
      +--- org.beanshell:bsh:2.0b4
-     +--- com.google.inject:guice:4.0
-     |    +--- javax.inject:javax.inject:1
-     |    +--- aopalliance:aopalliance:1.0
-     |    \--- com.google.guava:guava:16.0.1
-     +--- com.beust:jcommander:1.48
-     \--- org.yaml:snakeyaml:1.15
+     \--- com.beust:jcommander:1.48
 
 (*) - dependencies omitted (listed previously)
 
 BUILD SUCCESSFUL
 
-Total time: 1.424 secs
+Total time: 3.121 secs
```

**Comment by juherr** [comment]
The diff can be explained for `ant` and `yaml` because these dependencies (and `junit` you've already excluded) are now `<optional>true</optional>`.

Another strange dependency was `aopalliance` as the GAV of `guice` is (but maybe gradle ignores classifier):

```xml
<dependency>
  <groupId>com.google.inject</groupId>
  <artifactId>guice</artifactId>
  <version>4.0</version>
  <classifier>no_aop</classifier>
  <scope>provided</scope>
</dependency>
```

But as the scope is `provided`, you should add the guice dependency yourself.

BTW, @cbeust will say gradle is broken and you should use kobalt instead! ;)

**Comment by juherr** [comment]
I still don't understand why guice was present before (gradle issue?), because:

```diff
diff testng-6.9.9.pom testng-6.9.10.pom
***************
*** 4,10 ****
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
!   <version>6.9.9</version>
--- 4,10 ----
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
!   <version>6.9.10</version>
***************
*** 32,37 ****
--- 32,38 ----
      <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.10</version>
        <scope>compile</scope>
+       <optional>true</optional>
      </dependency>
***************
*** 44,49 ****
--- 45,51 ----
      <dependency>
        <groupId>org.apache.ant</groupId>
        <artifactId>ant</artifactId>
        <version>1.7.0</version>
        <scope>compile</scope>
+       <optional>true</optional>
      </dependency>
***************
*** 63,68 ****
--- 65,71 ----
      <dependency>
        <groupId>org.yaml</groupId>
        <artifactId>snakeyaml</artifactId>
        <version>1.15</version>
        <scope>compile</scope>
+       <optional>true</optional>
      </dependency>
```

BTW,

```diff
diff --git a/build.gradle b/build.gradle
index 0ba0cf5..fcee811 100644
--- a/build.gradle
+++ b/build.gradle
@@ -77,7 +77,8 @@ dependencies {
   testCompile 'org.ow2.asm:asm-analysis:5.0.4'
   testCompile 'org.hamcrest:hamcrest-all:1.3'
   testCompile 'org.skyscreamer:jsonassert:1.2.3'
-  testCompile 'org.testng:testng:6.9.9'
+  testCompile 'org.testng:testng:6.9.10'
+  testCompile 'com.google.inject:guice:4.0:no_aop'
 }
```

is fixing the issue on golo tests.
And, as guice is `<scope>provided</scope>`, I think it is cleaner to add it too.
