### ISSUE TITLE
ConcurrentModificationException at test cleanup

### ISSUE THREAD

**Issue by Linder76** [cbeust/testng#983]
Hi,

In the project I am working in we get the following error when running unit tests with TestNG and JMockIt.
It is a maven project sing surefire to execute the tests.
Versions used are
Surefire: 2.18.1
TestNG: 6.9.9
JMockIt: 1.13

```
08:23:19 java.util.ConcurrentModificationException: null
08:23:19    at java.util.IdentityHashMap$IdentityHashMapIterator.remove(IdentityHashMap.java:746)
08:23:19    at java.util.IdentityHashMap$EntryIterator.remove(IdentityHashMap.java:845)
08:23:19    at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
08:23:19    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:129)
08:23:19    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
08:23:19    at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
08:23:19    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
08:23:19    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
08:23:19    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

Surefire config looks like this

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <parallel>suitesAndClasses</parallel>
                    <threadCount>1</threadCount>
                    <forkCount>2C</forkCount>
                    <reuseForks>false</reuseForks>
                    <systemPropertyVariables>
                        <!-- The '0' seems somehow necessary to get this to be an actual number, 
                            otherwise it will be empty -->
                        <mavenForkNumber>0${surefire.forkNumber}</mavenForkNumber>
                    </systemPropertyVariables>
                    <!-- Skips unit tests if the value of skip.unit.tests property is true -->
                    <skipTests>${skip.unit.tests}</skipTests>
                    <excludes>
                        <!-- Excludes integration tests when unit tests are run -->
                        <exclude>**/IT*.java</exclude>
                        <!-- Excludes inner classes -->
                        <exclude>**/*$*.java</exclude>
                    </excludes>
                </configuration>
            </plugin>
```

Is this something anyone has seen before? Googling it doesn't give much information at all.

Thanks,

**Comment by juherr** [comment]
Looks like a surefire issue.

Ping @Tibor17

**Comment by Tibor17** [comment]
@Linder76 
`IdentityHashMap`, such loop and `.remove()`does not exist in current code. Please check it out with the latest Version `2.19.1`.
As a hint, these do not have effect: parallel, threadCount, excludes.

**Comment by krmahadevan** [comment]
Closing this issue since there has been no update on this and this is not related to TestNG
