### ISSUE TITLE
packages test (<package name="package"> inside testng.xml) initiates subpackages classes. It can make problems if subpackages classes throw exception on init.

### ISSUE THREAD

**Issue by astafev** [cbeust/testng#996]
In case we have test for package inside testng.xml and if some classes inside subpackage can't be inited (throw ClassNotFoundException for example), then tests will fail on start.

It can be bypassed using exclude in testng.xml:
```
<test name="test-success">
        <packages>
            <package name="package">
                <exclude name="package.subpackage.*"/>
            </package>
        </packages>
    </test>
```

I created a simple project to demonstrate it: https://github.com/astafev/testng-packages-bug

Looks like a bug for me.
example of exception:
```
[[ClassInfoMap]] Unable to open class org.springframework.aop.AopInvocationException - unable to resolve class reference org/springframework/core/NestedRuntimeException
java.lang.NoClassDefFoundError: org/springframework/core/NestedRuntimeException
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.testng.internal.ClassHelper.forName(ClassHelper.java:94)
	at org.testng.xml.XmlClass.loadClass(XmlClass.java:78)
	at org.testng.xml.XmlClass.getSupportClass(XmlClass.java:89)
	at org.testng.internal.ClassInfoMap.<init>(ClassInfoMap.java:25)
	at org.testng.internal.ClassInfoMap.<init>(ClassInfoMap.java:18)
	at org.testng.TestRunner.initMethods(TestRunner.java:408)
	at org.testng.TestRunner.init(TestRunner.java:235)
	at org.testng.TestRunner.init(TestRunner.java:205)
	at org.testng.TestRunner.<init>(TestRunner.java:153)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:536)
	at org.testng.SuiteRunner.init(SuiteRunner.java:159)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:113)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1299)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1286)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: org.springframework.core.NestedRuntimeException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 35 more
```

**Comment by cbeust** [comment]
What dependencies did you declare in your build file? Could it be that some
of them are `provided` but you didn't actually provide them?

-- 
Cédric

**Comment by astafev** [comment]
@cbeust yes, I did, it's the reason of ClassNotFoundException. And of course ClassNotFoundException is another problem that's needed to be solved.

But what I think is a bug here is that testng tries to init not only package classes but also subpackages.

Again:
This variant throws exception:
```
<test name="test-success">
        <packages>
            <package name="package"/>
        </packages>
    </test>
```
This variant is successful:
```
<test name="test-success">
        <packages>
            <package name="package">
                <exclude name="package.subpackage.*"/>
            </package>
        </packages>
    </test>
```
At least it's unexpected, as ```<package name="package">``` should run only classes inside package.

**Comment by juherr** [comment]
The DTD says:

```xml
<!-- The package description.
     If the package name ends with .* then subpackages are included too.
-->
<!ELEMENT package (include?,exclude?)*>
<!ATTLIST package
    name CDATA #REQUIRED >
```

Then, I think `<package name="package"/>` and `<package name="package.*"/>` should not be equivalent, and `<package name="package"/>` should not include subpackages.

What do you think @cbeust ?

**Comment by cbeust** [comment]
Agreed, if there’s no .*, then only packages named exactly as specified
(not sub packages) should be included.
​

-- 
Cédric

**Comment by astafev** [comment]
Tests from subpackages aren't run and if classes inside subpackages are ok, everything works well.

From my point of view, the problem is inside org.testng.internal.PackageUtils - it returns all classes including subpackages. Subpackages are removed somewhere else later, I think PackageUtils should filter it.

**Comment by juherr** [comment]
+1 It makes sense for me.

Could you pull-request a test case that shows the problem, and why not, a fix for it?

**Comment by astafev** [comment]
it already was fixed with https://github.com/cbeust/testng/commit/84a155a8aefdfa32796b3dfed8964bdf4bd097f4
We used old version. Sorry, closing ticket.
